/* Isolated v5 I–M acceptance. 6.4 is a dummy correction, never a validated extraction. */
const {chromium}=require(process.env.DATAEX_PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const url=process.env.DATAEX_URL||'http://127.0.0.1:8766/dataex-chatgpt.html',pdf=process.env.DATAEX_CHERKIN_PDF,rawFile=process.env.DATAEX_CHERKIN_RAW,out=process.env.DATAEX_ARTIFACT_DIR;
assert.equal(new URL(url).origin,'http://127.0.0.1:8766');assert.ok(pdf&&rawFile&&out);fs.mkdirSync(out,{recursive:true});
const original=JSON.parse(fs.readFileSync(rawFile,'utf8')),rawHash=crypto.createHash('sha256').update(fs.readFileSync(rawFile)).digest('hex');
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await context.newPage(),checks=[],errors=[],requests=[];
 await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:new URL(url).origin});
 const pass=(name,detail)=>{checks.push({name,detail});console.log('PASS '+name);},snapshot=()=>page.evaluate(()=>DataExReview.snapshot()),idle=()=>page.waitForFunction(()=>DataExReview.ready());
 const card=()=>page.locator('.outcome-card[data-outcome-id="O1"]'),set=()=>card().locator('.paper-current-result .result-set-decisions').first();
 const clickAction=async action=>{await idle();await set().locator('[data-result-set-action="'+action+'"]').click();await idle();};
 const dialog=()=>page.locator('.decision-dialog[open]');
 const atTime=async time=>{await card().locator('.paper-time-button[data-timepoint="'+time+'"]').click();};
 const csv=async()=>{await page.locator('.accepted-data-csv').click();const d=page.locator('.decision-dialog[open][data-basket-csv]');await d.locator('.accepted-csv-text').waitFor();await page.waitForFunction(()=>document.querySelector('.accepted-csv-text')?.textContent.length>0);return d;};
 try{
  await page.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){registeredTools[t.name]=t;}}});});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({method:r.method(),url:r.url()}));
  await page.goto(url);await page.waitForFunction(()=>window.DataExReview&&window.DataExPaperModel);await page.locator('#pdf-file').setInputFiles(pdf);await page.waitForFunction(()=>DataExFuzzy.brief().pdfLoaded);
  const brief=await page.evaluate(()=>DataExFuzzy.brief()),input={...structuredClone(original),requestId:brief.requestId};assert.equal(brief.pdfId,input.pdfId);assert.ok((await page.evaluate(p=>registeredTools.dataex_set_results.execute(p),input)).ok);await idle();assert.equal(Object.keys((await snapshot()).points).length,163);
  const options=await card().locator('.paper-comparison-choice option').evaluateAll(nodes=>nodes.map(n=>({value:n.value,text:n.textContent}))),choice=options.find(o=>/Standardized/i.test(o.text));assert.ok(choice,JSON.stringify(options));await card().locator('.paper-comparison-choice select').selectOption(choice.value);await atTime('8 weeks');
  const cellId='t2-O1-A2-1';await card().locator('.paper-current-result [data-raw-id="'+cellId+'"]').click();await page.waitForFunction(()=>document.querySelector('#page-number').value==='21'&&document.querySelector('#evidence-message').textContent.includes('値を特定'));await idle();assert.equal((await snapshot()).points[cellId].decision.status,'REVIEWED');await page.screenshot({path:path.join(out,'01-source-before-edit.png')});pass('I source: 6.3 (5.7) navigates to Cherkin Table 2 on p.21');
  const firstSetId=await set().getAttribute('data-result-set-id');await clickAction('edit');const editDialog=dialog();await editDialog.locator('[data-point-field="'+cellId+':mean"]').fill('6.4');await editDialog.getByLabel('修正理由（任意）').first().fill('受入テスト専用ダミー6.4。原著の検証済み値として利用しない。');await editDialog.getByRole('button',{name:'修正を保存',exact:true}).click();await editDialog.waitFor({state:'hidden'});await idle();
  let r=await snapshot();assert.equal(r.points[cellId].raw.mean,6.3);assert.equal(r.points[cellId].decision.finalValue.mean,6.4);assert.equal(r.resultSets[firstSetId].status,'EDITED_DRAFT');assert.equal(await page.evaluate(()=>DataExDecision.basket([DataExReview.snapshot()]).length),0);assert.deepEqual(r.snapshot.raw,input);pass('I edit: Final becomes dummy 6.4, exact Raw remains 6.3, draft is absent from basket');
  await clickAction('accept');r=await snapshot();assert.equal(r.resultSets[firstSetId].status,'ACCEPTED');assert.equal(r.confirmedAt,null);assert.equal((await page.evaluate(()=>DataExReviewStore.get(DataExReview.snapshot().id))).resultSets[firstSetId].status,'ACCEPTED');await page.waitForFunction(()=>document.querySelector('#accepted-data-count').textContent.includes('1件'));pass('J accept: selected Result set is immediately saved without Outcome/Study confirmation');
  await page.locator('.accepted-data-open').click();await dialog().locator('[data-accepted-set]').waitFor();assert.equal(await dialog().locator('[data-accepted-set]').count(),1);assert.match(await dialog().innerText(),/6\.4/);await page.screenshot({path:path.join(out,'02-basket-immediate.png')});await dialog().getByRole('button',{name:'閉じる',exact:true}).click();pass('K basket: count and list show only the selected 8-week comparison');
  let d=await csv(),preview=await d.locator('.accepted-csv-text').textContent(),expected=await page.evaluate(()=>DataExDecision.exportBasket([DataExReview.snapshot()]));assert.equal(preview,expected.csv);assert.equal(expected.rows.length,2);assert.ok(expected.rows.some(x=>x.mean===6.4));await d.getByRole('button',{name:'CSVをコピー',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#decision-message').textContent.includes('CSV全文をコピー'));assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),preview);pass('L CSV copy: clipboard exactly equals complete CSV preview with Final 6.4');
  await d.getByRole('button',{name:'TSVをコピー',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#decision-message').textContent.includes('TSV全文をコピー'));assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),expected.tsv);pass('L TSV copy: clipboard contains the complete accepted TSV');
  const event=page.waitForEvent('download');await d.getByRole('button',{name:'CSVを保存',exact:true}).click();const download=await event,save=path.join(out,download.suggestedFilename());await download.saveAs(save);assert.equal(fs.readFileSync(save,'utf8'),preview);assert.ok(fs.statSync(save).size>100);pass('L CSV save: real downloaded file exists and matches full preview',save);await page.screenshot({path:path.join(out,'03-csv-full-preview.png')});
  await page.evaluate(()=>{window.savedClipboardWrite=navigator.clipboard.writeText;Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:async()=>{throw Error('isolated clipboard failure');}});window.copyFallbackText=null;const old=document.execCommand.bind(document);document.execCommand=function(command){if(command==='copy')window.copyFallbackText=document.activeElement.value;return old(command);};});await d.getByRole('button',{name:'CSVをコピー',exact:true}).click();await page.waitForFunction(()=>window.copyFallbackText!==null);assert.equal((await page.evaluate(()=>window.copyFallbackText)).replace(/\r?\n/g,'\r\n'),preview);assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),preview);await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:window.savedClipboardWrite}));pass('L fallback: forced Clipboard API failure copies through selected textarea');
  await d.getByRole('button',{name:'閉じる',exact:true}).click();await atTime('26 weeks');await clickAction('accept');const secondSetId=await set().getAttribute('data-result-set-id');assert.notEqual(firstSetId,secondSetId);await atTime('52 weeks');await clickAction('hold');let thirdSetId=await set().getAttribute('data-result-set-id');r=await snapshot();assert.equal(r.resultSets[firstSetId].status,'ACCEPTED');assert.equal(r.resultSets[secondSetId].status,'ACCEPTED');assert.equal(r.resultSets[thirdSetId].status,'HOLD');await clickAction('exclude');r=await snapshot();assert.equal(r.resultSets[thirdSetId].status,'EXCLUDED');assert.equal(await page.evaluate(()=>DataExDecision.basket([DataExReview.snapshot()]).length),2);pass('Result-set scope: hold/exclude 52 weeks preserves adopted 8 and 26 weeks');
  await atTime('8 weeks');await clickAction('edit');d=dialog();await d.locator('[data-point-field="'+cellId+':mean"]').fill('6.5');await d.getByRole('button',{name:'修正を保存',exact:true}).click();await d.waitFor({state:'hidden'});await idle();r=await snapshot();assert.equal(r.resultSets[firstSetId].status,'EDITED_DRAFT');assert.equal(r.resultSets[secondSetId].status,'ACCEPTED');assert.equal(await page.evaluate(()=>DataExDecision.basket([DataExReview.snapshot()]).length),1);await clickAction('accept');pass('Editing adopted data removes only that set from export until explicit re-adoption');
  d=await csv();await page.evaluate(async()=>{const r=DataExReview.snapshot(),next=DataExDecision.apply(r,{type:'POINT',id:'t2-O1-A2-1',status:'EDITED',patch:{mean:6.6},note:'isolated concurrent dummy edit'});await DataExReviewStore.put(next,r.revision);});await d.getByRole('button',{name:'CSVをコピー',exact:true}).click();await d.getByText('採用内容が更新されています。プレビューを更新してください。',{exact:true}).waitFor();assert.equal(await d.locator('.accepted-csv-text').textContent(),'');assert.ok(await d.getByRole('button',{name:'CSVを保存',exact:true}).isDisabled());await d.getByRole('button',{name:'閉じる',exact:true}).click();await page.locator('#review-workspace').getByRole('button',{name:/Cherkin 2009/}).click();await idle();pass('Stale preview: concurrent saved edit prevents copying/downloading obsolete accepted data');
  const before=await page.evaluate(()=>DataExReview.all());assert.equal(before.length,1);await page.locator('#new-paper').click();await page.locator('#new-paper-dialog input[value=keep]').check();const chooserEvent=page.waitForEvent('filechooser');await page.locator('#new-paper-confirm').click();const chooser=await chooserEvent;await chooser.setFiles([]);await page.waitForFunction(()=>DataExReview.snapshot()===null&&!DataExFuzzy.brief().pdfLoaded);const after=await page.evaluate(()=>DataExReview.all());assert.deepEqual(after,before);assert.equal(await page.locator('.outcome-card').count(),0);await page.waitForFunction(()=>document.querySelector('#accepted-data-count').textContent.includes('1件'));await page.screenshot({path:path.join(out,'04-new-paper-basket-retained.png')});pass('M new paper: PDF/candidate cleared while saved Review and accepted result sets remain exact');
  await page.setViewportSize({width:375,height:1000});await page.locator('.accepted-data-open').click();assert.ok((await dialog().boundingBox()).width<=375);await dialog().getByRole('button',{name:'閉じる',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('375px: basket remains reachable after starting a new paper');
  // A clearly synthetic HR paper exercises Derived adoption without altering Cherkin's Raw.
  await page.setViewportSize({width:1440,height:1100});const {PDFDocument,StandardFonts}=require(process.env.DATAEX_PDFLIB_MODULE||'pdf-lib'),{fixture}=require('./dataex-fuzzy-fixture.cjs'),name='v5-synthetic-HR.pdf',hr=fixture('synthetic-hr',name),text='SYNTHETIC: Treatment versus Control overall survival at 12 months: HR 0.74, 95% CI 0.60 to 0.91.';
  hr.study.label='Synthetic HR conversion acceptance';hr.study.design='Parallel-group randomized controlled trial';hr.study.arms=hr.study.arms.filter(a=>['A1','A4'].includes(a.id));hr.outcomes=[{...hr.outcomes[0],reportedName:'Overall survival',conceptCandidate:'Overall survival',instrument:'Survival',dataType:'time-to-event',timepoints:['12 months'],confidence:1}];
  hr.rawValues=[{...hr.rawValues[0],id:'synthetic-HR',outcomeId:hr.outcomes[0].id,armId:'A1',comparatorArmId:'A4',timepoint:'12 months',resultType:'effect',statistics:{estimate:.74,ciLow:.6,ciHigh:.91,ciLevel:95},effectMeasure:'HR',adjustment:'unadjusted',nBasis:'OUTCOME_ANALYZED',confidence:1,sourceRefs:{estimate:'hr-source',ciLow:'hr-source',ciHigh:'hr-source',ciLevel:'hr-source'}}];hr.sources=[{...hr.sources[0],id:'hr-source',pdfFile:name,pdfPage:1,printedPage:'1',section:'Synthetic Results',tableFigure:null,row:null,column:null,directValue:'HR 0.74, 95% CI 0.60 to 0.91',evidenceText:text,kind:'TEXT'}];hr.proposals=[];hr.limitations=['Synthetic fixture only.'];
  function remapSourceRefs(object){if(!object||typeof object!=='object')return;for(const key of Object.keys(object))if(key==='sourceRefs'||key==='sourceIds'){const refs=object[key];object[key]=Array.isArray(refs)?['hr-source']:Object.fromEntries(Object.keys(refs||{}).map(k=>[k,'hr-source']));}else remapSourceRefs(object[key]);}remapSourceRefs(hr);
  const document=await PDFDocument.create(),font=await document.embedFont(StandardFonts.Helvetica),sheet=document.addPage([1000,700]);sheet.drawText(text,{x:25,y:620,size:11,font});const hrPdf=path.join(out,name);fs.writeFileSync(hrPdf,await document.save());await page.locator('#pdf-file').setInputFiles(hrPdf);await page.waitForFunction(()=>DataExFuzzy.brief().pdfLoaded);const hb=await page.evaluate(()=>DataExFuzzy.brief());hr.pdfId=hb.pdfId;hr.requestId=hb.requestId;const hrResult=await page.evaluate(p=>registeredTools.dataex_set_results.execute(p),hr);assert.ok(hrResult.ok,JSON.stringify(hrResult));await idle();let hrRecord=await snapshot();assert.equal(hrRecord.derivedCandidates.length,1);assert.equal(hrRecord.derivedCandidates[0].status,'PROPOSED');assert.equal(hrRecord.derivedCandidates[0].statistics.estimate,Math.log(.74));assert.equal((await page.evaluate(()=>DataExReviewStore.get(DataExReview.snapshot().id))).derivedCandidates.length,1);pass('Derived persistence: synthetic HR/CI conversion is saved separately as PROPOSED with provenance');
  const hrSet=page.locator('.paper-current-result .result-set-decisions').first();await hrSet.locator('[data-result-set-action=accept]').click();await idle();assert.equal(await page.evaluate(()=>DataExDecision.exportBasket([DataExReview.snapshot()],{format:'giv'}).rows.length),0);await hrSet.locator('[data-result-set-action=derive]').click();d=page.locator('.decision-dialog[open][data-derived-set]');assert.match(await d.innerText(),/Wald/);assert.match(await d.innerText(),/ln/);await page.screenshot({path:path.join(out,'05-derived-confirmation.png')});await d.getByRole('button',{name:'この換算値を採用',exact:true}).click();await d.waitFor({state:'hidden'});await idle();hrRecord=await snapshot();const hrOutput=await page.evaluate(()=>DataExDecision.exportBasket([DataExReview.snapshot()],{format:'giv'}));assert.equal(hrOutput.rows.length,1);assert.equal(hrOutput.rows[0].Effect_Type,'log(HR)');assert.equal(hrOutput.rows[0].Effect,Math.log(.74));assert.equal(hrOutput.rows[0].SE,(Math.log(.91)-Math.log(.6))/3.92);assert.deepEqual(hrRecord.snapshot.raw,hr);assert.ok(Object.values(hrRecord.resultSets)[0].acceptedDerived.length);pass('Derived adoption: explicit confirmation enables log(HR)+SE GIV while original HR/CI remains exact Raw');
  d=await csv();await d.getByLabel('形式',{exact:true}).selectOption('giv');await page.waitForFunction(()=>document.querySelector('.accepted-csv-text')?.textContent.includes('log(HR)'));await d.getByRole('button',{name:'CSVをコピー',exact:true}).click();const givPreview=await d.locator('.accepted-csv-text').textContent();await page.waitForFunction(async()=> (await navigator.clipboard.readText()).includes('log(HR)'));assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),givPreview);const derivedDownloadEvent=page.waitForEvent('download');await d.getByRole('button',{name:'CSVを保存',exact:true}).click();const derivedDownload=await derivedDownloadEvent,derivedPath=path.join(out,derivedDownload.suggestedFilename());await derivedDownload.saveAs(derivedPath);assert.equal(fs.readFileSync(derivedPath,'utf8'),givPreview);await page.screenshot({path:path.join(out,'06-derived-giv-csv.png')});await d.getByRole('button',{name:'閉じる',exact:true}).click();pass('Derived GIV CSV: real clipboard and saved file exactly match the complete adopted conversion preview',derivedPath);
  await hrSet.locator('[data-result-set-action=edit]').click();d=dialog();await d.locator('[data-point-field="synthetic-HR:effect"]').fill('.8');await d.getByRole('button',{name:'修正を保存',exact:true}).click();await d.waitFor({state:'hidden'});await idle();assert.equal(await page.evaluate(()=>DataExDecision.exportBasket([DataExReview.snapshot()],{format:'giv'}).rows.length),0);assert.deepEqual((await snapshot()).snapshot.raw,hr);pass('Derived invalidation: editing source Final removes adopted conversion from GIV until re-confirmed');
  assert.equal(crypto.createHash('sha256').update(fs.readFileSync(rawFile)).digest('hex'),rawHash);assert.deepEqual(errors,[]);assert.equal(requests.filter(r=>r.method!=='GET').length,0);fs.writeFileSync(path.join(out,'v5-basket-acceptance.json'),JSON.stringify({url,pdf,checks,errors,requests,rawHash,testEdits:'Dummy corrections only in an isolated browser profile; original Raw unchanged'},null,2));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.message,stack:e.stack,checks,errors},null,2));throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
