const {chromium}=require(process.env.DATAEX_PLAYWRIGHT_MODULE||'playwright');
const {PDFDocument,StandardFonts}=require(process.env.DATAEX_PDFLIB_MODULE||'pdf-lib');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {fixture}=require('./dataex-fuzzy-fixture.cjs');
const url=process.env.DATAEX_URL||'http://127.0.0.1:8766/dataex-chatgpt.html',source=process.env.DATAEX_SOURCE_DIR;
const out=process.env.DATAEX_ARTIFACT_DIR||path.join(__dirname,'test-artifacts'),assets=process.env.DATAEX_PDF_DIR;
assert.equal(new URL(url).origin,'http://127.0.0.1:8766');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1450,height:1150}}),page=await context.newPage();
 const errors=[],requests=[],passes=[];const pass=name=>{passes.push(name);console.log('PASS '+name);};
 try {
  if(source)await context.route('http://127.0.0.1:8766/**',route=>{const name=decodeURIComponent(new URL(route.request().url()).pathname).slice(1);const file=path.join(source,name);if(!name.includes('..')&&fs.existsSync(file)&&fs.statSync(file).isFile())return route.fulfill({status:200,contentType:name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css':'text/javascript; charset=utf-8',body:fs.readFileSync(file)});return route.continue();});
  await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:new URL(url).origin});
  await page.addInitScript(()=>{window.registeredTools={};window.fuzzyNetwork=[];Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.registeredTools[t.name]=t;}}});
   const fetch=window.fetch;window.fetch=function(...args){window.fuzzyNetwork.push(['fetch',String(args[0])]);return fetch.apply(this,args);};
   const open=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(...args){window.fuzzyNetwork.push(['xhr',String(args[1])]);return open.apply(this,args);};
   const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){window.fuzzyNetwork.push(['ws',String(args[0])]);super(...args);}};
  });
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
  await page.goto(url);await page.waitForFunction(()=>Object.keys(window.registeredTools).length===10 && window.DataExFuzzy);
  const call=(name,args={})=>page.evaluate(({name,args})=>window.registeredTools[name].execute(args),{name,args});
  const brief=()=>call('dataex_get_extraction_brief'),snapshot=()=>page.evaluate(()=>window.DataExFuzzy.snapshot());
  const openContext=async()=>{if(!await page.locator('#sr-context').evaluate(e=>e.open))await page.locator('#sr-context > summary').click();};
  const load=async file=>{await openContext();await page.locator('#pdf-file').setInputFiles(file);await page.waitForFunction(()=>window.DataExFuzzy.brief().pdfLoaded);};
  const bind=(payload,b)=>({...structuredClone(payload),requestId:b.requestId,pdfId:b.pdfId});
  assert.equal(await page.locator('#builder-advanced,#timepoint,#population-rule,#extra-rules,#profile-dialog,#builder-study-design').count(),0);
  assert.equal(await page.locator('input[type=password]').count(),0);assert.equal(await page.locator('#fuzzy-prompt').getAttribute('readonly'),'');
  assert.equal(await page.locator('#outcomes').getAttribute('required'),null);assert.ok(await page.locator('#fuzzy-extract').isVisible());
  assert.match(await page.evaluate(()=>window.registeredTools.dataex_set_selection_result.description),/完全一致は要求しない/);
  pass('Simplified standard screen has optional PICO, no advanced/old profile/Core editor/API key');
  await page.locator('#fuzzy-extract').click();assert.match(await page.locator('#extract-message').innerText(),/PDFを選択/);assert.equal(await page.locator('#extract-message.error').count(),0);
  const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),sheet=pdf.addPage([1250,950]);
  const original=fixture();original.sources.forEach((s,i)=>sheet.drawText(s.evidenceText,{x:25,y:900-i*52,size:8,font}));
  const file=path.join(out,'fuzzy-fixture.pdf');fs.writeFileSync(file,await pdf.save());
  await openContext();await page.locator('#population').fill('Adults with chronic low back pain');await page.locator('#intervention').fill('Acupuncture');await page.locator('#comparator').fill('Usual care');
  await load(file);assert.equal(await page.locator('#pdf-page-1 canvas').count(),1);
  let b=await brief();assert.equal(b.mode,'DISCOVERY');assert.equal(b.extractionBlocked,false);assert.equal(b.reviewContext.outcomes.length,0);assert.equal(b.pdfManifest.length,1);
  pass('PDF + PICO with empty outcomes gives a Discovery request, no specification blocking');
  await page.evaluate(()=>{window.fuzzyNetwork=[];});const requestIndex=requests.length;
  await page.locator('#fuzzy-extract').click();await page.waitForFunction(()=>document.querySelector('#extract-message').textContent.includes('チャット'));assert.equal(await snapshot(),null);assert.equal((await brief()).status,'awaiting_agent');
  const clipboard=await page.evaluate(()=>navigator.clipboard.readText());assert.match(clipboard,/Fuzzy抽出/);assert.equal((await page.evaluate(()=>window.fuzzyNetwork)).length,0);
  pass('Extract prepares the real site-tool request; waiting is explicit and no fabricated AI result/network send occurs');
  const map=await call('dataex_get_document_map');assert.equal(map.pages.length,1);assert.equal(map.allPages.length,1);
  let text='',offset=0;do{const p=await call('dataex_get_page_text',{page:1,offset,maxChars:180});assert.ok(!p.isError);text+=p.normalizedText;offset=p.nextOffset;}while(offset!==null);
  assert.match(text,/VAS pain intensity/);assert.equal((await brief()).completedPages.length,1);
  pass('Document map and paginated page reading preserve complete source text and coverage');
  b=await brief();let payload=bind(original,b);let response=await call('dataex_set_results',payload);assert.ok(response.ok,JSON.stringify(response));
  assert.equal(response.outcomeCount,5);assert.equal(response.rawValueCount,12);assert.equal(await page.locator('#fuzzy-outcome-inventory .outcome-card').count(),5);
  await page.locator('#fuzzy-study-summary summary').first().click();await page.locator('#fuzzy-study-summary tbody tr').first().waitFor();assert.equal(await page.locator('#fuzzy-study-summary tbody tr').count(),4);
  await page.locator('#fuzzy-raw > summary').click();await page.locator('#fuzzy-raw tbody tr').first().waitFor();assert.equal(await page.locator('#fuzzy-raw tbody tr').count(),12);
  pass('A structured AI response populates study summary, discovered cards and paginated Raw/candidate details');
  let saved=await snapshot();assert.equal(saved.raw.study.arms.length,4);assert.equal(saved.raw.rawValues.filter(r=>r.outcomeId==='O1').length,8);assert.equal(saved.proposals[0].status,'PROPOSED');
  assert.equal(saved.normalizedCandidates.find(n=>n.id==='R1:scale-100').statistics.mean,30);assert.equal(saved.raw.rawValues[0].statistics.mean,3);assert.equal(saved.raw.rawValues.at(-1).statistics.events,0);
  pass('Four arms, both timepoints, 0–10/0–100 scale proposal, SE-to-SD and zero events keep Raw intact');
  const repeated=await call('dataex_set_results',payload);assert.ok(repeated.ok);const changed=structuredClone(payload);changed.rawValues[0].statistics.mean=999;assert.ok((await call('dataex_set_results',changed)).isError);assert.equal((await snapshot()).raw.rawValues[0].statistics.mean,3);
  pass('Repeated identical submission is idempotent; different payload cannot overwrite a completed Raw request');
  await page.locator('#fuzzy-raw button[data-source-id="source-R1"]').first().click();assert.ok(await page.locator('.bbox-highlight').count()>0);
  pass('Source Trace invokes the existing PDF focus and yellow highlight successfully');
  await page.locator('#fuzzy-prompt-details').evaluate(e=>{e.open=true;});await page.waitForFunction(()=>document.querySelector('#fuzzy-prompt').value.length>1000);
  assert.match(await page.locator('#fuzzy-prompt').inputValue(),/Adults with chronic low back pain/);await page.locator('#fuzzy-copy-prompt').click();await page.waitForFunction(()=>document.querySelector('#extract-message').textContent.includes('プロンプト全文をコピー'));assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n')===await page.locator('#fuzzy-prompt').inputValue(),'Clipboard text matches the full prompt after Windows newline normalization');
  await page.evaluate(()=>{navigator.clipboard.writeText=async()=>{throw Error('Test clipboard denial');};window.copyFallbackCalled=false;document.execCommand=cmd=>{window.copyFallbackCalled=cmd==='copy';return true;};});
  await page.locator('#fuzzy-copy-prompt').click();assert.ok(await page.evaluate(()=>window.copyFallbackCalled));assert.equal(await page.locator('#fuzzy-prompt').evaluate(e=>e.selectionEnd-e.selectionStart),await page.locator('#fuzzy-prompt').evaluate(e=>e.value.length));
  pass('Fixed Core appears only in details; full copy and selected-text fallback work');
  const storage=await page.evaluate(()=>Object.fromEntries(Object.keys(localStorage).map(k=>[k,localStorage.getItem(k)])));
  assert.ok(Object.keys(storage).some(k=>k.startsWith('dataex:fuzzy:v1:study:')));assert.ok(!JSON.stringify(storage).includes('# DataEx Fuzzy Extraction Core'));assert.ok(!JSON.stringify(storage).includes('data:application/pdf'));
  pass('Local storage saves review context and source-linked results, never Core or PDF bytes');
  await page.locator('#outcomes').fill('Pain');b=await brief();assert.equal(b.mode,'TARGETED_FUZZY');assert.ok((await call('dataex_set_results',payload)).isError);
  const targeted=bind(original,b);for(const o of targeted.outcomes){o.mapping={target:'Pain',relation:o.id==='O1'||o.id==='O2'?'COMPATIBLE':'RELATED',reason:o.id==='O1'||o.id==='O2'?'Pain intensity by VAS/NRS':'Different clinical concept; retain separately'};}
  assert.ok((await call('dataex_set_results',targeted)).ok);saved=await snapshot();assert.equal(saved.raw.outcomes[0].mapping.relation,'COMPATIBLE');assert.equal(saved.raw.outcomes[3].mapping.relation,'RELATED');assert.equal(saved.analysisReadyCandidates.find(r=>r.outcomeId==='O4').status,'NEEDS_REVIEW');
  pass('Pain target accepts semantic VAS/NRS candidates and keeps pressure threshold separate; stale requests are rejected');
  await page.locator('#outcomes').fill('Pain\nDisability');b=await brief();const invalid=bind(original,b);invalid.sources[0].pdfPage=99;assert.ok((await call('dataex_set_results',invalid)).isError);assert.equal((await snapshot()).raw.requestId,targeted.requestId);assert.deepEqual((await snapshot()).extractionContext.outcomes,['Pain']);
  const injected=bind(original,b);injected.study.label='<img src=x onerror="window.injected=true">';assert.ok((await call('dataex_set_results',injected)).ok);assert.equal(await page.locator('#fuzzy-study-summary img').count(),0);assert.equal(await page.evaluate(()=>window.injected),undefined);
  pass('Malformed results fail atomically and untrusted AI strings render as text without HTML execution');
  await page.setViewportSize({width:375,height:1000});await page.locator('#fuzzy-extract').scrollIntoViewIfNeeded();assert.ok(await page.locator('#fuzzy-extract').isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'fuzzy-375.png')});
  await page.locator('#fuzzy-outcome-inventory').scrollIntoViewIfNeeded();const firstCard=page.locator('#fuzzy-outcome-inventory .outcome-card').first();if(await firstCard.locator('.outcome-card-body').isVisible())await firstCard.locator('.outcome-toggle').click();await firstCard.locator('.outcome-toggle').focus();await page.keyboard.press('Enter');assert.ok(await firstCard.locator('.outcome-card-body').isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  pass('375px retains primary operations and keyboard-accessible compact outcome cards without page overflow');
  await page.setViewportSize({width:1450,height:1150});await page.reload();await page.waitForFunction(()=>window.DataExFuzzy);assert.equal((await brief()).pdfLoaded,false);assert.equal(await page.locator('#outcomes').inputValue(),'Pain\nDisability');
  await load(file);assert.equal((await snapshot()).raw.requestId,injected.requestId);assert.equal((await snapshot()).sourceChecks.every(s=>s.status==='TEXT_MATCH'),true);
  pass('Reload restores context; selecting the same PDF restores and rechecks saved source-linked results');
  const second=path.join(out,'second-fixture.pdf');fs.writeFileSync(second,fs.readFileSync(file));const oldBrief=await brief();await load([second,file]);assert.equal(await page.locator('#fuzzy-pdf-queue button').count(),2);assert.equal((await brief()).pdfManifest[0].filename,'second-fixture.pdf');
  assert.ok((await call('dataex_set_results',{...injected,requestId:oldBrief.requestId,pdfId:oldBrief.pdfId})).isError);assert.equal(await snapshot(),null);
  pass('Multiple PDF selection stays local, switches the current document, and rejects previous-PDF results');
  assert.equal((await page.evaluate(()=>window.fuzzyNetwork)).filter(x=>/openai|anthropic|generativelanguage/.test(x[1])).length,0);
  assert.equal(requests.slice(requestIndex).filter(r=>r.method!=='GET').length,0);
  pass('No AI API, upload, fetch/XHR/WebSocket send is added to extraction or result submission');
  if(assets){
   await load(path.join(assets,'Holz 2020.pdf'));await page.locator('#pdf-query').fill('Figure 2');await page.locator('#search-form button').click();await page.waitForFunction(()=>document.querySelectorAll('.bbox-highlight').length>0);assert.ok((await page.locator('#search-results').innerText()).includes('P.5'));
   await page.setViewportSize({width:1550,height:1750});await page.locator('#page-number').fill('5');await page.locator('#page-number').dispatchEvent('change');await page.waitForFunction(()=>document.querySelector('#pdf-page-5 canvas'));await page.locator('#pdf-page-5').scrollIntoViewIfNeeded();
   await page.locator('#selection-region').click();const box=await page.locator('#pdf-page-5').boundingBox(),rect={x:.06,y:.635,width:.88,height:.28};
   await page.mouse.move(box.x+rect.x*box.width,box.y+rect.y*box.height);await page.mouse.down();await page.mouse.move(box.x+(rect.x+rect.width)*box.width,box.y+(rect.y+rect.height)*box.height,{steps:8});await page.mouse.up();await page.waitForFunction(()=>window.DataExSelection.getActiveSelection());
   await page.locator('#selection-preview').click();await page.locator('#selection-dialog').waitFor({state:'visible'});await page.locator('#crop-use').click();
   let selectionContext=await call('dataex_get_selection_context');assert.equal(selectionContext.captionStatus,'MATCHED');assert.ok(selectionContext.nearbyMetadata.some(s=>/Figure 2|Fig\. 2/i.test(s.label)));assert.equal(selectionContext.extractionBlocked,false);
   assert.equal(await page.locator('.manual-selection').count(),1);assert.ok(await page.locator('.bbox-highlight').count()>0);await page.screenshot({path:path.join(out,'fuzzy-viewer-caption.png')});
   const prepared=await call('dataex_prepare_selection_for_ai',{selectionId:selectionContext.selectionId});assert.ok(prepared.ok);assert.equal((await call('dataex_get_selection_context')).cropVisible,true);
   await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.DataExSelection.getActiveSelection()),null);await page.locator('#selection-text').click();
   const span=page.locator('#pdf-page-5 .textLayer span').filter({hasText:'Mean change from baseline'}).first();await span.scrollIntoViewIfNeeded();const sb=await span.boundingBox();assert.ok(sb);await page.mouse.move(sb.x+2,sb.y+sb.height/2);await page.mouse.down();await page.mouse.move(sb.x+Math.min(sb.width-2,210),sb.y+sb.height/2,{steps:12});await page.mouse.up();assert.ok((await page.evaluate(()=>getSelection().toString())).trim().length>0);
   pass('New Fuzzy screen retains real PDF rendering/search/text selection/figure crop/caption and yellow highlight');
   await page.locator('#outcomes').fill('');await page.locator('#pdf-page-5').scrollIntoViewIfNeeded();await page.locator('#selection-region').click();
   const tb=await page.locator('#pdf-page-5').boundingBox(),tr={x:.065,y:.062,width:.88,height:.263};
   await page.mouse.move(tb.x+tr.x*tb.width,tb.y+tr.y*tb.height);await page.mouse.down();await page.mouse.move(tb.x+(tr.x+tr.width)*tb.width,tb.y+(tr.y+tr.height)*tb.height,{steps:8});await page.mouse.up();
   await page.locator('#selection-preview').click();await page.locator('#selection-dialog').waitFor({state:'visible'});await page.locator('#crop-use').click();
   const visualContext=await call('dataex_get_selection_context');assert.ok((await call('dataex_prepare_selection_for_ai',{selectionId:visualContext.selectionId})).ok);
   const visualInput=JSON.parse(fs.readFileSync(path.join(__dirname,'dataex-fuzzy-visual-fixture.json'),'utf8'));visualInput.selectionId=visualContext.selectionId;
   const visualResponse=await call('dataex_set_selection_result',visualInput);assert.ok(visualResponse.ok,JSON.stringify(visualResponse));
   assert.equal(await page.locator('#result-cards .visual-result-card').count(),1);assert.ok((await page.locator('#result-cards').innerText()).includes('228'));
   await page.reload();await page.waitForFunction(()=>window.DataExFuzzy);await load(path.join(assets,'Holz 2020.pdf'));assert.equal(await page.locator('#result-cards .visual-result-card').count(),1);
   pass('Existing visual extraction result hooks, review display and same-PDF persistence work on the new page');
  }
  assert.deepEqual(errors,[]);pass('No JavaScript page errors through the complete new-screen flow');
  fs.writeFileSync(path.join(out,'fuzzy-browser-result.json'),JSON.stringify({url,source:source||null,passes,errors,aiMode:'Synthetic structured AI responses; model inference accuracy is not measured by these tests.',pdfSentExternally:false},null,2));
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
