/* Restores an exported saved Moffett record; never calls extraction or changes the user's browser profile. */
const {chromium}=require(process.env.DATAEX_PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const url=process.env.DATAEX_URL||'http://127.0.0.1:8766/dataex-chatgpt.html';
const out=process.env.DATAEX_ARTIFACT_DIR,recordFile=process.env.DATAEX_MOFFETT_RECORD,pdf=process.env.DATAEX_MOFFETT_PDF;
assert.ok(out&&recordFile&&pdf);assert.equal(new URL(url).origin,'http://127.0.0.1:8766');fs.mkdirSync(out,{recursive:true});
const record=JSON.parse(fs.readFileSync(recordFile,'utf8'))[0],raw=record.snapshot.raw;
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex'),rawHash=hash(raw);
const ids=['m99-r15','m99-r36','m99-r45','m99-r18','m99-r39','m99-r48'];
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
 await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:new URL(url).origin});
 const page=await context.newPage(),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const pass=name=>{checks.push(name);console.log('PASS '+name);};
 const idle=()=>page.waitForFunction(()=>window.DataExReview?.ready());
 const snapshot=()=>page.evaluate(()=>DataExReview.snapshot());
 const effect=id=>page.locator('.paper-effect-candidate[data-effect-raw-id="'+id+'"]');
 const dialog=()=>page.locator('.decision-dialog[open]');
 const expand=async()=>{for(const id of ['O1','O2']){const card=page.locator('.outcome-card[data-outcome-id="'+id+'"]');await card.getByText('調整済み効果を表示',{exact:true}).click();await effect(id==='O1'?ids[0]:ids[3]).waitFor();}};
 try{
  await page.goto(url);await page.waitForFunction(()=>window.DataExReview&&window.DataExReviewStore);await page.evaluate(()=>DataExReview.whenIdle());
  await page.evaluate(r=>DataExReviewStore.put(r,-1),record);await page.evaluate(r=>DataExReview.openRecord(r),record);await idle();
  let r=await snapshot();assert.equal(r.derivedCandidateVersion,'5.0.1');assert.equal(hash(r.snapshot.raw),rawHash);assert.deepEqual(r.points,record.points);assert.deepEqual(r.history.slice(0,record.history.length),record.history);assert.equal(r.history.at(-1).action,'DERIVED_CANDIDATE_CACHE');assert.deepEqual(r.resultSets,record.resultSets);pass('Saved record migration refreshes proposed conversions while preserving Raw, points, decisions and history');
  await page.locator('#pdf-file').setInputFiles(pdf);await page.waitForFunction(()=>DataExFuzzy.brief().pdfLoaded);await idle();assert.equal((await snapshot()).extractionId,record.extractionId);assert.equal((await snapshot()).studyId,record.studyId);pass('Original PDF reconnects to the same saved extraction without re-extraction');
  await expand();
  for(const id of ids){const row=raw.rawValues.find(v=>v.id===id),box=effect(id);for(const phrase of ['調整済み群間差','95% CIからSEを算出可能','Generic inverse varianceで使用候補'])assert.ok((await box.innerText()).includes(phrase));assert.equal(await box.locator('[data-readiness="UNUSABLE"]').count(),0);
   assert.ok((await box.locator('.paper-giv-summary').innerText()).includes('Derived SE = '+((row.statistics.ciHigh-row.statistics.ciLow)/(2*1.959964)).toFixed(3)));await box.locator('[data-result-set-action="derive"]').click();const detail=JSON.parse(await dialog().locator('pre').textContent());
   assert.equal(detail['Raw effect'],row.statistics.estimate);assert.equal(detail['CI low'],row.statistics.ciLow);assert.equal(detail['CI high'],row.statistics.ciHigh);assert.equal(detail['confidence level'],'95%');assert.equal(detail['Derived SE'],(row.statistics.ciHigh-row.statistics.ciLow)/(2*1.959964));assert.equal(detail['comparison direction'],'Control minus Intervention');assert.match(detail.formula,/1\.959964/);assert.equal(await box.locator('[data-result-set-action="derive"]').isVisible(),true);await dialog().getByRole('button',{name:'戻る',exact:true}).click();pass(id+' individually displays the full CI → Derived SE → GIV guidance');
  }
  assert.equal(await page.evaluate(()=>DataExDecision.basket([DataExReview.snapshot()]).length),0);assert.equal(hash((await snapshot()).snapshot.raw),rawHash);pass('Viewing six conversion previews does not adopt or mutate Raw');
  await effect(ids[0]).locator('[data-raw-id="'+ids[0]+'"]').click();await page.waitForFunction(()=>document.querySelector('#page-number').value==='4'&&document.querySelector('#evidence-message').textContent.includes('値を特定'));await page.screenshot({path:path.join(out,'01-six-week-source-and-conversion.png')});pass('Adjusted effect Click-to-Source still jumps to p4 Table2 and resolves the value');
  await effect(ids[0]).locator('[data-result-set-action="derive"]').click();assert.ok((await dialog().innerText()).includes('Control minus Intervention'));await dialog().getByRole('button',{name:'戻る',exact:true}).click();assert.equal(await page.evaluate(()=>DataExDecision.basket([DataExReview.snapshot()]).length),0);pass('Cancelling the explicit conversion confirmation leaves the GIV basket empty');
  for(const id of ids){await idle();await effect(id).locator('[data-result-set-action="derive"]').click();await dialog().getByRole('button',{name:'この換算値を採用',exact:true}).click();await idle();}
  r=await snapshot();assert.equal(hash(r.snapshot.raw),rawHash);for(const id of ids){assert.deepEqual(r.points[id].raw,record.points[id].raw);assert.equal(r.points[id].decision.finalValue.effect,record.points[id].raw.effect);assert.equal(r.points[id].decision.finalValue.se,null);}assert.equal(Object.values(r.resultSets).filter(s=>s.status==='ACCEPTED').length,6);pass('Six explicit Derived adoptions retain original effect/CI and keep Derived SE separate from Raw/Final');
  await page.locator('.accepted-data-open').click();await dialog().locator('[data-accepted-set]').first().waitFor();assert.equal(await dialog().locator('[data-accepted-set]').count(),6);assert.ok((await dialog().innerText()).includes('SE=0.482'));await dialog().getByRole('button',{name:'閉じる',exact:true}).click();pass('Accepted basket shows six GIV effects and their derived SE values');
  await page.locator('.accepted-data-csv').click();await dialog().getByLabel('形式',{exact:true}).selectOption('giv');await page.waitForFunction(()=>document.querySelector('.accepted-csv-text')?.textContent.includes('adjusted mean difference'));
  const preview=await dialog().locator('.accepted-csv-text').textContent(),expected=await page.evaluate(()=>DataExDecision.exportBasket([DataExReview.snapshot()],{format:'giv'}));assert.equal(expected.rows.length,6);assert.equal(expected.blocked,false);assert.equal(preview,expected.csv);for(const row of expected.rows){assert.equal(row.Comparison_Direction,'Control minus Intervention');assert.equal(row.Effect_Type,'adjusted mean difference');assert.ok(row.Effect>0&&row.SE>0);}pass('GIV preview has exactly six adjusted mean differences with unflipped direction');
  await dialog().getByRole('button',{name:'CSVをコピー',exact:true}).click();await page.waitForFunction(async()=> (await navigator.clipboard.readText()).includes('Control minus Intervention'));assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),preview);
  const event=page.waitForEvent('download');await dialog().getByRole('button',{name:'CSVを保存',exact:true}).click();const download=await event;await download.saveAs(path.join(out,'Moffett-1999-GIV-acceptance.csv'));assert.equal(fs.readFileSync(path.join(out,'Moffett-1999-GIV-acceptance.csv'),'utf8'),preview);await page.screenshot({path:path.join(out,'02-giv-csv-full.png')});pass('Full GIV CSV is copied and saved as an exact real file');
  await dialog().getByLabel('形式',{exact:true}).selectOption('continuous');await page.waitForFunction(()=>document.querySelector('.accepted-csv-text')?.textContent.includes('Intervention_Mean'));assert.ok(await dialog().getByRole('button',{name:'CSVを保存',exact:true}).isDisabled());assert.equal(await page.evaluate(()=>DataExDecision.exportBasket([DataExReview.snapshot()],{format:'continuous'}).rows.length),0);await dialog().getByRole('button',{name:'閉じる',exact:true}).click();pass('GIV effects cannot also export as arm-level pairwise Mean/SD rows');
  await page.reload();await page.getByRole('button',{name:'前回の結果を見る',exact:true}).click();await idle();r=await snapshot();assert.equal(hash(r.snapshot.raw),rawHash);assert.equal(await page.evaluate(()=>DataExDecision.exportBasket([DataExReview.snapshot()],{format:'giv'}).rows.length),6);pass('Reload restores six adopted GIV candidates without re-extraction or duplicate counting');
  await page.setViewportSize({width:375,height:1000});await expand();await effect(ids[0]).locator('[data-result-set-action="derive"]').click();assert.ok((await dialog().boundingBox()).width<=375);assert.ok((await dialog().innerText()).includes('1.959964'));await page.screenshot({path:path.join(out,'03-conversion-375.png')});await dialog().getByRole('button',{name:'戻る',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('375px layout keeps conversion details and confirmation controls reachable');
  assert.deepEqual(errors,[]);assert.equal(hash(JSON.parse(fs.readFileSync(recordFile,'utf8'))[0].snapshot.raw),rawHash);
  fs.writeFileSync(path.join(out,'acceptance.json'),JSON.stringify({url,checks,errors,rawHash,extractionId:record.extractionId,note:'Saved Moffett record restored into isolated browser storage. Test adoptions do not change the user Review.'},null,2));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.stack,checks,errors},null,2));throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
