// Local browser regression; PDFs remain in the browser, artifacts stay on disk.
const {chromium}=require(process.env.DATAEX_PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {PDFDocument,StandardFonts,degrees}=require(process.env.DATAEX_PDFLIB_MODULE||'pdf-lib');
const out=process.env.DATAEX_ARTIFACT_DIR||__dirname,assets=process.env.DATAEX_PDF_DIR||path.join(__dirname,'test-assets');
(async()=>{
 const browser=await chromium.launch({headless:true}),errors=[],passed=[],external=[];
 try {
 const page=await browser.newPage({viewport:{width:1550,height:1750}});
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 page.on('request',r=>{if(r.method()!=='GET')external.push({url:r.url(),method:r.method()});});
 await page.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.registeredTools[t.name]=t;}}});});
 const ready=()=>page.waitForFunction(()=>Object.keys(window.registeredTools).length===10);
 await page.goto(process.env.DATAEX_URL||'http://127.0.0.1:8771/dataex-chatgpt.html');await ready();
 const call=(name,args={})=>page.evaluate(({name,args})=>window.registeredTools[name].execute(args),{name,args});
 const selection=()=>page.evaluate(()=>window.DataExSelection.getActiveSelection());
 const load=async file=>{await page.locator('#pdf-file').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#pdf-status').textContent.startsWith('✓'));};
 const goto=async n=>{await page.locator('#page-number').fill(String(n));await page.locator('#page-number').dispatchEvent('change');await page.waitForFunction(n=>document.querySelector('#pdf-page-'+n+' canvas'),n);await page.locator('#pdf-page-'+n).scrollIntoViewIfNeeded();};
 const select=async(n,r)=>{await goto(n);await page.locator('#selection-region').click();const b=await page.locator('#pdf-page-'+n).boundingBox();await page.mouse.move(b.x+r.x*b.width,b.y+r.y*b.height);await page.mouse.down();await page.mouse.move(b.x+(r.x+r.width)*b.width,b.y+(r.y+r.height)*b.height,{steps:8});await page.mouse.up();await page.waitForFunction(()=>window.DataExSelection.getActiveSelection());};
 const crop=async name=>{await page.locator('#selection-preview').click();await page.locator('#selection-dialog').waitFor({state:'visible'});const bytes=await page.evaluate(async()=>Array.from(new Uint8Array(await window.DataExSelection.getActiveCropBlob().arrayBuffer())));fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(bytes));return Buffer.from(bytes);};
 assert.equal(await page.locator('#selection-region').isDisabled(),true);assert.equal(await page.locator('#selection-text').getAttribute('aria-pressed'),'true');
 await load(path.join(assets,'Holz 2020.pdf'));await goto(5);await page.locator('#pdf-page-5').screenshot({path:path.join(out,'holz-page5.png')});
 const table={x:.065,y:.062,width:.88,height:.263},figure={x:.06,y:.635,width:.88,height:.28};
 await select(5,table);let selected=await selection();assert.equal(selected.page,5);for(const k of Object.keys(table))assert.ok(Math.abs(selected.normalizedRect[k]-table[k])<.003,k);assert.ok(selected.pdfRect.x2>selected.pdfRect.x1);assert.ok(selected.pdfRect.y2>selected.pdfRect.y1);
 const tablePNG=await crop('holz-table2-crop');selected=await selection();assert.ok(selected.cropWidth>1400);assert.ok(selected.renderScale>=2.5);assert.equal(selected.mimeType,'image/png');assert.equal(selected.status,'READY');
 await page.setViewportSize({width:1450,height:1000});await page.screenshot({path:path.join(out,'crop-preview.png')});await page.locator('#crop-zoom-in').click();assert.match(await page.locator('.selection-preview-tools').first().innerText(),/125%/);await page.locator('#crop-use').click();assert.equal(await page.locator('#selection-active').isVisible(),true);assert.equal(await page.locator('#selection-text').getAttribute('aria-pressed'),'true');
 const focused=await call('dataex_focus_evidence',{page:5,query:'Mean change from baseline, ETDRS letters (SD)'});assert.ok(focused.ok);assert.ok(await page.locator('.bbox-highlight').count()>0);assert.equal(await page.locator('.manual-selection').count(),1);
 await page.locator('#clear-highlight').click();assert.equal(await page.locator('.manual-selection').count(),1);
 await page.locator('#pane-resizer').focus();const before=await page.locator('#pane-resizer').getAttribute('aria-valuenow');await page.keyboard.press('ArrowRight');assert.notEqual(await page.locator('#pane-resizer').getAttribute('aria-valuenow'),before);assert.equal(await page.locator('.manual-selection').count(),1);
 await goto(2);await page.locator('#selection-show').click();assert.equal(await selection().then(s=>s.page),5);
 passed.push('Table 2 high-resolution crop; preview zoom/use; yellow evidence coexistence; resizer; return to selected page');
 await page.setViewportSize({width:1550,height:1750});
 // Same normalized crop, independently selected at 75/100/150%; pixels should match.
 for(const target of [75,100,150]){
   await goto(5);while(parseInt(await page.locator('#zoom-value').innerText())!==target){const current=parseInt(await page.locator('#zoom-value').innerText());await page.locator(target>current?'#zoom-in':'#zoom-out').click();await page.waitForFunction(t=>parseInt(document.querySelector('#zoom-value').textContent)===t,current+(target>current?25:-25));await page.waitForTimeout(120);}
   await page.locator('#selection-show').click();await page.locator('.manual-selection').waitFor({state:'visible'});const overlay=await page.locator('.manual-selection').boundingBox(),host=await page.locator('#pdf-page-5').boundingBox();assert.ok(Math.abs((overlay.x-host.x)/host.width-table.x)<.004);
   await page.locator('#selection-clear').click();await select(5,table);const png=await crop('holz-table2-'+target);assert.ok(png.length>10000);const actual=await selection();assert.ok(Math.abs(actual.normalizedRect.x-table.x)<.003);assert.equal(actual.cropWidth,selected.cropWidth);assert.equal(actual.cropHeight,selected.cropHeight);await page.locator('#crop-use').click();
 }
 passed.push('75/100/150% selection coordinates and high-resolution crop dimensions independent of viewer zoom');
 // Return to 100% for figure and paragraph selection.
 for(let i=0;i<2;i++){await page.locator('#zoom-out').click();await page.waitForTimeout(180);}await page.locator('#selection-clear').click();await select(5,figure);await crop('holz-figure2-crop');await page.locator('#crop-redo').click();assert.equal(await selection(),null);assert.equal(await page.locator('#selection-region').getAttribute('aria-pressed'),'true');
 const p8=await call('dataex_get_page_text',{page:8,maxChars:16000}),paragraph=p8.normalizedText.slice(p8.normalizedText.indexOf('Frequency and type of systemic AEs'),p8.normalizedText.indexOf('Three patients discontinued')).trim();assert.ok(paragraph.length>100);
 const paragraphFocus=await call('dataex_focus_evidence',{page:8,evidenceText:paragraph});assert.ok(paragraphFocus.ok);const boxes=paragraphFocus.boundingBoxes;const left=Math.min(...boxes.map(b=>b.x))-.006,top=Math.min(...boxes.map(b=>b.y))-.001,right=Math.max(...boxes.map(b=>b.x+b.width))+.006,bottom=Math.max(...boxes.map(b=>b.y+b.height))+.001;
 await select(8,{x:left,y:top,width:right-left,height:bottom-top});await crop('holz-text-crop');await page.locator('#crop-close').click();assert.ok(await selection());await page.keyboard.press('Escape');assert.equal(await selection(),null);assert.equal(await page.evaluate(()=>window.DataExSelection.getActiveCropBlob()),null);
 passed.push('Figure 2 and Results paragraph crops; redo/close/Esc release selection and crop');
 // Tiny drag must not create a region. Normal text selection must remain available.
 await goto(5);await page.locator('#selection-region').click();let b=await page.locator('#pdf-page-5').boundingBox();await page.mouse.move(b.x+100,b.y+100);await page.mouse.down();await page.mouse.move(b.x+110,b.y+110);await page.mouse.up();assert.equal(await selection(),null);await page.locator('#selection-text').click();assert.equal(await page.locator('#pdf-page-5 .textLayer').evaluate(e=>getComputedStyle(e).pointerEvents),'auto');
 // Render failures must leave a recoverable selection, with a Japanese error.
 await select(5,table);await page.evaluate(()=>{window.originalToBlob=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(cb){cb(null);};});await page.locator('#selection-preview').click();await page.waitForFunction(()=>document.querySelector('#selection-message').textContent.includes('画像を作成できません'));assert.equal(await page.locator('#selection-dialog').isVisible(),false);await page.evaluate(()=>{HTMLCanvasElement.prototype.toBlob=window.originalToBlob;});await crop('holz-retry-crop');await page.locator('#crop-close').click();
 // Loading another PDF drops all selection/crop memory. No persisted selection.
 const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);const p=pdf.addPage([1800,1800]);p.drawText('Large page crop bound test',{x:40,y:1600,size:50,font});p.setRotation(degrees(90));const mixed=pdf.addPage([400,800]);mixed.drawText('Portrait page',{x:20,y:750,size:14,font});const file=path.join(out,'large-rotated.pdf');fs.writeFileSync(file,await pdf.save());await load(file);assert.equal(await selection(),null);assert.equal(await page.evaluate(()=>window.DataExSelection.getActiveCropBlob()),null);
 // At 50%, the synthetic 1800px page fits; max crop side/area are capped.
 await page.locator('#zoom-out').click();await page.waitForTimeout(150);await page.locator('#zoom-out').click();await page.waitForTimeout(150);await select(1,{x:.01,y:.01,width:.98,height:.98});await crop('large-crop');let capped=await selection();assert.ok(Math.max(capped.cropWidth,capped.cropHeight)<=4000);assert.ok(capped.cropWidth*capped.cropHeight<=8000000);assert.ok(capped.renderScale<2.5);await page.locator('#crop-use').click();await goto(2);await page.locator('#selection-show').click();assert.equal((await selection()).page,1);
 await page.locator('#selection-clear').click();await select(2,{x:.2,y:.2,width:.5,height:.5});await page.evaluate(()=>{const original=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(cb,...args){original.call(this,result=>setTimeout(()=>cb(result),600),...args);};});await page.locator('#selection-preview').click();await load(path.join(assets,'Holz 2020.pdf'));await page.waitForTimeout(900);assert.equal(await selection(),null);assert.equal(await page.evaluate(()=>window.DataExSelection.getActiveCropBlob()),null);assert.equal(await page.locator('#selection-dialog').isVisible(),false);
 await page.reload();await ready();assert.equal(await selection(),null);assert.equal(await page.locator('#selection-region').isDisabled(),true);
 passed.push('Tiny drag ignored; text mode restored; PNG failure/retry; rotated/large-page memory caps; PDF replacement and reload clear memory');
 const hd=await browser.newPage({viewport:{width:1450,height:1500},deviceScaleFactor:2});hd.on('pageerror',e=>errors.push(e.message));await hd.goto(process.env.DATAEX_URL||'http://127.0.0.1:8771/dataex-chatgpt.html');await hd.locator('#pdf-file').setInputFiles(path.join(assets,'Holz 2020.pdf'));await hd.waitForFunction(()=>document.querySelector('#pdf-status').textContent.startsWith('✓'));await hd.locator('#selection-region').click();const h=await hd.locator('#pdf-page-1').boundingBox();await hd.mouse.move(h.x+50,h.y+50);await hd.mouse.down();await hd.mouse.move(h.x+350,h.y+300,{steps:5});await hd.mouse.up();await hd.locator('#selection-preview').click();await hd.locator('#selection-dialog').waitFor({state:'visible'});assert.equal(await hd.evaluate(()=>window.DataExSelection.getActiveSelection().renderScale),3.5);await hd.close();passed.push('HiDPI devicePixelRatio 2 uses independent render scale 3.5');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);passed.push('10 site tools, zero console errors, no non-GET requests / image uploads');
 fs.writeFileSync(path.join(out,'phase31-test-result.json'),JSON.stringify({passed,consoleErrors:errors,externalWrites:external,table:{width:selected.cropWidth,height:selected.cropHeight,renderScale:selected.renderScale},large:{width:capped.cropWidth,height:capped.cropHeight}},null,2));passed.forEach(s=>console.log('PASS '+s));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
