const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={window:{},document:{getElementById(){}},structuredClone};
for(const file of ['dataex-caption.js','dataex-visual.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,file),'utf8'),ctx);
const captions=ctx.window.DataExCaptions,rect={x:.1,y:.3,width:.8,height:.37},selection={selectionId:'fixture',page:5,normalizedRect:rect};
const caption='Figure 2. Mean ± SD response (study population, full analysis set).';
const line=(text,x=.1,y=.7,width=.75)=>({text,x,y,width,height:.012});
const detect=(items,s=selection)=>captions.detectItems(items,s);
let bundle=detect([line(caption)]);assert.equal(bundle.captionStatus,'MATCHED');assert.equal(bundle.nearbyMetadataSources[0].number,'Figure 2');assert.ok(bundle.nearbyMetadataSources[0].distance<.04);
assert.equal(detect([]).captionStatus,'NOT_FOUND');assert.equal(detect([line(caption,.1,.9)]).captionStatus,'NOT_FOUND');
assert.equal(detect([line(caption,.65,.7,.3)],{...selection,normalizedRect:{...rect,width:.4}}).captionStatus,'NOT_FOUND');
assert.equal(detect([line('Figure 2 shows the responses.')]).captionStatus,'NOT_FOUND');
assert.equal(detect([line(caption),line('Fig. 3. Other response',.1,.74)]).captionStatus,'AMBIGUOUS');
assert.equal(detect([line(caption),line('FIGURE 2. Repeated number',.1,.1)]).captionStatus,'AMBIGUOUS');
assert.equal(detect([line('TABLE 2. Raw outcomes',.1,.275)]).captionStatus,'MATCHED');
assert.doesNotMatch(detect([line(caption),line('58',.1,.717,.02)]).nearbyMetadataSources[0].text,/58/,'page number is not a caption continuation');
const columns=[line(caption,.1,.7,.35),line('Figure 3. Right column',.55,.7,.35)];
assert.equal(detect(columns,{...selection,normalizedRect:{...rect,width:.37}}).captionStatus,'MATCHED');
assert.equal(detect(columns).captionStatus,'AMBIGUOUS');
const long=detect([line('Figure 2. '+('Caption words '.repeat(100))),line('Figure 3. '+('More caption '.repeat(100)),.1,.74)]);
assert.ok(long.nearbyMetadataSources.reduce((n,s)=>n+s.text.length,0)<1000);assert.ok(long.nearbyMetadataSources.every(s=>s.truncated));
console.log('PASS bounded vertical proximity, caption anchors, number uniqueness, column alignment, ambiguity and text budget');

const visual=ctx.window.createDataExVisual({state:{},selection:{setExtractHandler(){}},getExtraction(){},tool:(name,description,inputSchema,execute)=>({name,inputSchema,execute}),schema:(properties,required=[])=>({type:'object',properties,required,additionalProperties:false})});
const input={selectionId:'fixture',sourceKind:'FIGURE_ESTIMATE',resultStatus:'READY',outcomes:[{outcome:'Response',timepoint:'week 24',population:null,unit:'points',analysisUnit:'participant',variableType:'continuous',arms:[{name:'Group A',valueText:'Approximately 69',numerator:null,denominator:null,mean:69,sd:null,se:null,nStatus:'NOT_SHOWN_FOR_TIMEPOINT',uncertaintyValueStatus:'UNKNOWN'}],directVisibleValues:['Study Week','Response (+SD)'],derivedValues:[],approximate:false,reason:'Crop contains no caption.',reviewFlags:[],figureMetadata:{figureNumber:null,population:null,errorBarType:'SD',xAxis:'Study Week',yAxis:'Response (+SD)',unit:'points',timepoint:'week 24',series:['Group A'],metadataVerification:'VISUALLY_VERIFIED_DIRECT_METADATA'}}],visualAudit:{valuesClearlyVisible:false,labelsClearlyVisible:true,unitsClearlyVisible:true,timepointClearlyVisible:true,uncertaintyTypeClearlyVisible:true,notes:'Synthetic image audit.'}};
const record={id:'fixture:Response',input,source:{sourceId:'visual-fixture',sourceType:'VISUAL_REGION',page:5,selectionId:'fixture',normalizedRect:rect},visualSourceBundle:bundle,review:{state:'NOT_REVIEWED'}};
const resolve=mutate=>{const r=structuredClone(record);mutate?.(r);visual.restore([r]);return visual.outcomes()[0];};
let o=resolve();assert.equal(o.figureMetadata.figureNumber,'Figure 2');assert.equal(o.population,'study population, full analysis set');assert.equal(o.figureMetadata.metadataVerification,'MIXED_DIRECT_METADATA');
assert.equal(o.metadataProvenance.population.sourceType,'PDF_TEXT_CAPTION');assert.equal(o.metadataProvenance.errorBarType.sourceType,'VISUAL_REGION');assert.equal(o.metadataProvenance.figureNumber.verification,'SOURCE_VERIFIED_TEXT');assert.equal(o.figureMetadata.caption,null);
assert.equal(o.arms[0].n,null);assert.equal(o.arms[0].sd,null);assert.equal(o.status,'CANDIDATE_ONLY');assert.equal(o.analysisAction,'REVIEW');assert.equal(o.approximate,true);assert.deepEqual(Array.from(o.unresolved),['week 24の対応n','SDの数値']);assert.match(o.figureSummary,/近接captionで確認/);
o=resolve(r=>{r.input.outcomes[0].figureMetadata.errorBarType=null;r.input.outcomes[0].figureMetadata.yAxis='Response';});assert.equal(o.figureMetadata.errorBarType,'SD');assert.equal(o.metadataProvenance.errorBarType.sourceType,'PDF_TEXT_CAPTION');
o=resolve(r=>{r.visualSourceBundle=detect([line('Figure 2. Response over time. SD is defined in the Methods.')]);r.input.outcomes[0].figureMetadata.errorBarType=null;r.input.outcomes[0].figureMetadata.yAxis='Response';});assert.equal(o.figureMetadata.errorBarType,null,'a mere SD mention does not define the error bars');
o=resolve(r=>{r.visualSourceBundle=detect([line(caption),line('Fig. 3. Different group',.1,.74)]);});assert.equal(o.population,null);assert.equal(o.figureMetadata.figureNumber,null);
assert.throws(()=>resolve(r=>{r.visualSourceBundle.captionStatus='AMBIGUOUS';r.input.outcomes[0].captionMetadata={sourceRef:bundle.nearbyMetadataSources[0].sourceId,population:'study population'};}),/MATCHED/);
assert.throws(()=>resolve(r=>{r.input.outcomes[0].captionMetadata={sourceRef:bundle.nearbyMetadataSources[0].sourceId,population:'invented population'};}),/原文/);
assert.throws(()=>resolve(r=>r.visualSourceBundle.nearbyMetadataSources[0].page=4),/不正/);
assert.throws(()=>resolve(r=>r.visualSourceBundle.selectionSource.selectionId='stale'),/不正/);
assert.throws(()=>resolve(r=>r.visualSourceBundle.nearbyMetadataSources[0].number='Figure 999'),/不正/);
assert.throws(()=>resolve(r=>r.visualSourceBundle.nearbyMetadataSources[0].normalizedRect.x=-1),/不正/);
o=resolve(r=>{r.input.outcomes[0].figureMetadata.errorBarType='SE';r.input.outcomes[0].figureMetadata.yAxis='Response (SE)';});assert.equal(o.figureMetadata.errorBarType,'SE');assert.ok(o.unresolved.some(x=>x.includes('一致していません')));
o=resolve(r=>{delete r.visualSourceBundle;});assert.equal(o.population,null);assert.equal(o.figureMetadata.metadataVerification,'VISUALLY_VERIFIED_DIRECT_METADATA');
console.log('PASS distinct image/text provenance, automatic caption metadata, null n/SD, no READY promotion, conflict guard, stale/ambiguous/forged sources rejected, legacy restore');
(async()=>{
  let active={...selection,accepted:true},release;const state={pdf:{},loading:false,generation:1};
  ctx.window.DataExSelection={getActiveSelection:()=>active};
  const delayed=ctx.window.createDataExVisual({state,selection:{setExtractHandler(){},isAIVisible:()=>false},getExtraction:()=>({getBrief:()=>({outcomes:['Response']})}),pageData:()=>new Promise(resolve=>release=resolve),tool:(name,description,inputSchema,execute)=>({name,execute}),schema:(properties,required=[])=>({type:'object',properties,required,additionalProperties:false})});
  const pending=delayed.tools.find(t=>t.name==='dataex_get_selection_context').execute({});
  state.generation++;active=null;
  release({page:{getViewport:()=>({width:600,height:800,scale:1,transform:[1,0,0,-1,0,800]})},textContent:{items:[{str:caption,width:450,transform:[10,0,0,10,60,240]}],styles:{}}});
  const result=await pending;assert.equal(result.selectionId,null);assert.equal(result.nearbyMetadata.length,0);assert.equal(result.captionStatus,'NOT_FOUND');
  console.log('PASS PDF/selection replacement during asynchronous caption lookup discards stale metadata');
})().catch(e=>{console.error(e);process.exitCode=1;});
