// The real workspace coordinator with in-memory DOM/store adapters; no PDF or user DB writes.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const core=require('./dataex-fuzzy-core.js'),ico=require('./dataex-ico-mapping.js');
class Node{constructor(){this.value='';this.hidden=false;this.open=false;this.children=[];this.events={};this.dataset={};this.classList={add(){},remove(){}};this.isConnected=true;}addEventListener(k,f){(this.events[k]||=[]).push(f);}async emit(k,e={}){for(const f of this.events[k]||[])await f(e);}append(...a){this.children.push(...a);}replaceChildren(...a){this.children=a;}setAttribute(){}scrollIntoView(){}focus(){}select(){}setSelectionRange(){}showModal(){this.open=true;}close(){this.open=false;}click(){this.clicks=(this.clicks||0)+1;}remove(){}}
const nodes=new Map(),$=id=>{if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id);},radios=['keep','clear','new-review'].map(value=>Object.assign(new Node(),{value,checked:value==='clear'}));
const select=value=>radios.forEach(r=>r.checked=r.value===value),doc={body:new Node(),createElement:()=>new Node(),querySelectorAll:s=>s.includes('next-paper-ico')?radios:[],querySelector:s=>s.includes(':checked')?radios.find(r=>r.checked):s.includes('value="clear"')?radios[1]:{after(){} }};
const state={generation:0,pdf:null,loading:false},stored=new Map(),projects=[{id:'test',label:'test'}];let releases=0,writes=0,active=projects[0],reviewHooks,ws;
const review={whenIdle:async()=>{},selectedProject:()=>active,projectForContext:()=>active,releaseCurrent:async()=>{releases++;return true;},saveContext:async c=>{writes++;},workspaceElement:()=>new Node(),mappingDecisions:()=>['old mapping'],preferredSnapshot:()=>null,createProject:async label=>{active={id:'new',label};projects.push(active);await reviewHooks.onProjectChange(active,{});return active;}};
const window={DataExFuzzyCore:core,DataExICO:ico,DataExJSONImport:require('./dataex-json-import.js'),DataExFuzzyCache:{readSnapshot:async()=>null,writeSnapshot:async()=>({backend:'IndexedDB'})},createDataExReview:h=>(reviewHooks=h,review),createDataExJSONImportUI:()=>({busy:()=>false}),dataexVisual:{snapshot:()=>[],outcomes:()=>[],clear(){},render(){}},addEventListener(){}};
const env={window,document:doc,crypto,structuredClone,console,queueMicrotask,localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},navigator:{clipboard:{writeText:async()=>{}}}};vm.createContext(env);vm.runInContext(fs.readFileSync(__dirname+'/dataex-fuzzy-workspace.js','utf8'),env);
ws=window.createDataExFuzzy({$,state,getState:()=>({}),pageData:async()=>({raw:''}),pageNumber(){},checkReady(){},checkGeneration(){},focusEvidence(){},navigation:{},tool:(name,d,s,f)=>({name,f}),schema:()=>({}),message:(id,text)=>$(id).textContent=text,clearPdf:async()=>{state.pdf=null;}});
const file=name=>({name:name+'.pdf',size:10,lastModified:100,type:'application/pdf'}),a=file('A'),b=file('B'),loaded=[];
const load=async f=>{loaded.push(f.name);state.generation++;state.pdf={numPages:2,fingerprints:[f.name]};await ws.onPdfLoaded(f);};
let n=0;async function test(name,fn){await fn();console.log('PASS '+name);n++;}
const plain=v=>JSON.parse(JSON.stringify(v)),context=()=>plain(window.DataExFuzzy.brief().reviewContext);
const guided=()=>{for(const k of ['intervention','comparator','outcomes','population'])$(k).value='old '+k;};
const cleared=()=>{const c=context();for(const k of ['intervention','comparator','population'])assert.equal(c[k],'');assert.deepEqual(c.outcomes,[]);assert.deepEqual(plain(window.DataExFuzzy.brief().mappingDecisions),[]);};
(async()=>{
 await test('empty SR permits first PDF, no configuration dialog',async()=>{await ws.loadFiles([a],load);assert.deepEqual(loaded,['A.pdf']);assert.equal($('new-paper-dialog').open,false);cleared();});
 await test('direct replacement prompts before changing PDF; default clear',async()=>{guided();await ws.loadFiles([b],load);assert.equal(loaded.length,1);assert.equal($('new-paper-dialog').open,true);assert.equal(radios.find(r=>r.checked).value,'clear');});
 await test('cancel keeps current PDF and all conditions',async()=>{const before=context();await $('new-paper-cancel').emit('click');assert.deepEqual(context(),before);assert.equal(window.DataExFuzzy.brief().pdfManifest[0].filename,'A.pdf');});
 await test('clear then open removes PICO and temporary mapping',async()=>{await ws.loadFiles([b],load);await $('new-paper-confirm').emit('click');cleared();assert.equal(loaded.at(-1),'B.pdf');});
 await test('explicit keep applies all four conditions and displays them',async()=>{guided();await ws.loadFiles([a],load);select('keep');await $('new-paper-confirm').emit('click');assert.equal(context().intervention,'old intervention');assert.match($('fuzzy-mode').textContent,/適用中.*old intervention/);});
 await test('queued PDF uses same guard instead of bypassing it',async()=>{await $('fuzzy-pdf-queue').children.flatMap(n=>n.children).find(n=>n.textContent==='B.pdf').emit('click');assert.equal($('new-paper-dialog').open,true);assert.equal(loaded.at(-1),'A.pdf');await $('new-paper-cancel').emit('click');});
 await test('new PDF choice waits until file is selected before changing conditions',async()=>{await $('new-paper').emit('click');select('clear');const before=context();await $('new-paper-confirm').emit('click');assert.deepEqual(context(),before);await ws.loadFiles([b],load);cleared();});
 await test('file chooser cancel + new input cannot reuse an old keep intent',async()=>{guided();await $('new-paper').emit('click');select('keep');await $('new-paper-confirm').emit('click');await $('conditions').emit('input');await ws.loadFiles([a],load);assert.equal($('new-paper-dialog').open,true);await $('new-paper-cancel').emit('click');});
 await test('explicit new Review preserves old Review and has empty conditions',async()=>{await $('new-paper').emit('click');select('new-review');$('new-review-name').value='new review';await $('new-paper-confirm').emit('click');await ws.loadFiles([a],load);assert.equal(projects.length,2);assert.equal(active.label,'new review');cleared();});
 await test('same PDF reconnect retains explicitly set current conditions',async()=>{guided();const before=context();await ws.loadFiles([a],load);assert.deepEqual(context(),before);assert.equal($('new-paper-dialog').open,false);});
 await test('same name size and timestamp cannot silently identify a new file',async()=>{await ws.loadFiles([{...a}],load);assert.equal($('new-paper-dialog').open,true);await $('new-paper-cancel').emit('click');});
 console.log(JSON.stringify({checks:n,passed:true,releases,projects:projects.length}));
})().catch(e=>{console.error(e);process.exitCode=1;});

