const assert=require('node:assert/strict'),fs=require('fs'),Cache=require('./dataex-presentation-cache.js'),F=require('./dataex-fuzzy-core.js'),M=require('./dataex-results-model.js'),P=require('./dataex-paper-model.js'),{fixture}=require('./dataex-fuzzy-fixture.cjs');
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
const raw=fixture(),study=F.buildStudy(raw,{pdfId:raw.pdfId,filename:raw.sources[0].pdfFile,pageCount:30},[]),context={outcomes:[],intervention:'',comparator:''};
const build=(s=study,c=context)=>{const view=M.build(s,c);return {view,paper:P.build(view,c)};};
test('cold and cached complete presentation semantic diff = 0',()=>{const c=Cache.create(),a=c.get(study,context,build),b=c.get(study,context,build);assert.deepEqual(a,b);assert.deepEqual(a,build());assert.deepEqual(c.metrics(),{hits:1,misses:1});});
test('caller mutations cannot poison cached candidates',()=>{const c=Cache.create(),a=c.get(study,context,build);a.view.raw.rawValues[0].statistics.mean=99999;const b=c.get(study,context,build);assert.deepEqual(b,build());b.paper.resultSets.length=0;assert.deepEqual(c.get(study,context,build),build());});
test('changed Raw input invalidates rather than reuses stale result',()=>{const c=Cache.create(),s=structuredClone(study);c.get(s,context,()=>build(s));s.raw.rawValues[0].population+=' updated';const result=c.get(s,context,()=>build(s));assert.deepEqual(result,build(s));assert.equal(c.metrics().misses,2);});
test('changed source text invalidates',()=>{const c=Cache.create(),s=structuredClone(study);c.get(s,context,()=>build(s));s.raw.sources[0].evidenceText+=' changed';assert.deepEqual(c.get(s,context,()=>build(s)),build(s));assert.equal(c.metrics().hits,0);});
test('changed ICO context invalidates',()=>{const c=Cache.create();c.get(study,context,build);const different={...context,outcomes:['Disability']};assert.deepEqual(c.get(study,different,()=>build(study,different)),build(study,different));assert.equal(c.metrics().misses,2);});
test('different studies do not share entries',()=>{const c=Cache.create();c.get(study,context,build);c.get(structuredClone(study),context,build);assert.equal(c.metrics().hits,0);});
test('source checks and derived candidate inputs are in invalidation key',()=>{const c=Cache.create(),s=structuredClone(study);c.get(s,context,()=>build(s));s.sourceChecks=[{sourceId:'changed',status:'not found'}];c.get(s,context,()=>build(s));s.normalizedCandidates.push({id:'new'});c.get(s,context,()=>build(s));assert.equal(c.metrics().misses,3);});
if(process.env.DATAEX_IMPORT_PAYLOAD)test('VITAL complete cached model and all semantic output unchanged across 30 hits',()=>{const raw=JSON.parse(fs.readFileSync(process.env.DATAEX_IMPORT_PAYLOAD,'utf8').replace(/^\uFEFF/,'')),s=F.buildStudy(raw,{pdfId:raw.pdfId,filename:raw.sources[0].pdfFile,pageCount:12},[]),before=structuredClone(s),c=Cache.create(),expected=build(s);for(let i=0;i<30;i++)assert.deepEqual(c.get(s,context,()=>build(s)),expected);assert.deepEqual(s,before);assert.equal(c.metrics().hits,29);});
console.log(JSON.stringify({checks,passed:true}));
