const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const T=require('./dataex-extraction-timing.js');let checks=0;
const test=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
const meta={requestId:'request-1',pdfId:'pdf-1',reviewId:'review-1'};
function setup(options={}){let wall=1700000000000,mono=0,origin=1699999999999,stored=[];const model=T.create({clock:()=>({wall,mono,origin}),read:()=>stored,write:x=>{stored=x;},...options});return {model,tick:ms=>{wall+=ms;mono+=ms;},wall:value=>{wall=value;},stored:()=>stored};}
test('records copy, result arrival and import completion separately',()=>{const x=setup(),m=x.model;m.copied(meta);x.tick(5000);const ticket=m.receive(meta);x.tick(250);m.complete(ticket);const r=m.current();assert.equal(r.status,'complete');assert.equal(r.waitMs,5000);assert.equal(r.localMs,250);assert.equal(r.totalMs,5250);assert.equal(r.received.wall-r.copied.wall,5000);assert.equal(r.completed.wall-r.received.wall,250);});
test('re-copy does not shorten the same request',()=>{const x=setup(),m=x.model;m.copied(meta);const t=m.current().copied;x.tick(5000);m.copied(meta);assert.deepEqual(m.current().copied,t);assert.equal(m.current().waitMs,5000);});
test('no copy timestamp means unknown wait and total',()=>{const x=setup(),m=x.model;const ticket=m.receive(meta);x.tick(80);m.complete(ticket);assert.equal(m.current().waitMs,null);assert.equal(m.current().totalMs,null);assert.equal(m.current().localMs,80);});
test('copy after received cannot invent an earlier start',()=>{const x=setup(),m=x.model;const t=m.receive(meta);x.tick(20);m.copied(meta);m.complete(t);assert.equal(m.current().copied,null);});
test('PDF or review change hides unrelated timing without deleting it',()=>{const x=setup(),m=x.model;m.copied(meta);m.select({...meta,pdfId:'other'});assert.equal(m.current(),null);m.select({...meta,reviewId:'other'});assert.equal(m.current(),null);m.select(meta);assert.equal(m.current().status,'waiting');});
test('missing or stale receive token has no effect',()=>{const x=setup(),m=x.model;m.copied(meta);assert.equal(m.receive(null),null);m.complete(null);m.fail({key:'different',attempt:1});assert.equal(m.current().status,'waiting');});
test('duplicate result calls preserve original completion',()=>{const x=setup(),m=x.model;m.copied(meta);const t=m.receive(meta);m.complete(t);const before=m.current();x.tick(100);assert.equal(m.receive(meta),null);m.complete(t);assert.deepEqual(m.current(),before);});
test('import failure does not record a completion time',()=>{const x=setup(),m=x.model;m.copied(meta);x.tick(20);const t=m.receive(meta);x.tick(2);m.fail(t);const r=m.current();assert.equal(r.status,'failed');assert.equal(r.completed,null);assert.equal(r.localMs,null);assert.equal(r.totalMs,null);});
test('retry cannot be finished by an old token',()=>{const x=setup(),m=x.model;m.copied(meta);const old=m.receive(meta);m.fail(old);const next=m.receive(meta);m.complete(old);assert.equal(m.current().status,'importing');m.complete(next);assert.equal(m.current().status,'complete');});
test('wall-clock correction does not change duration in one page',()=>{const x=setup(),m=x.model;m.copied(meta);x.tick(500);x.wall(1600000000000);const t=m.receive(meta);x.tick(25);m.complete(t);assert.equal(m.current().waitMs,500);assert.equal(m.current().localMs,25);assert.equal(m.current().totalMs,525);});
test('session storage or timing display failure cannot throw into extraction',()=>{const x=setup({read:()=>{throw Error('blocked');},write:()=>{throw Error('quota');},changed:()=>{throw Error('UI');}}),m=x.model;assert.doesNotThrow(()=>{m.copied(meta);const t=m.receive(meta);m.complete(t);});assert.equal(m.current().status,'complete');});
test('only last 20 measurements are stored',()=>{const x=setup();for(let i=0;i<25;i++)x.model.copied({...meta,requestId:'r'+i});assert.equal(x.stored().length,20);assert.ok(x.stored().every(x=>Object.keys(x).every(k=>['key','copied','received','completed','status','saveWarning','attempt'].includes(k))));});
test('restored incomplete import remains visibly incomplete',()=>{const x=setup(),m=x.model;m.copied(meta);m.receive(meta);const next=T.create({clock:()=>({wall:1700000000300,mono:0,origin:1700000000200}),read:x.stored});next.select(meta);assert.equal(next.current().status,'failed');assert.equal(next.current().completed,null);});
test('existing snapshot save warning does not become successful durable storage claim',()=>{const x=setup(),m=x.model;const t=m.receive(meta);m.complete(t,true);assert.equal(m.current().saveWarning,true);assert.equal(m.current().status,'complete');});
test('short times retain millisecond precision; unknown is not zero',()=>{assert.equal(T.duration(null),'—');assert.equal(T.duration(132),'0.132秒');assert.equal(T.duration(62000),'1分2.0秒');});
// Guard original source paths that must remain byte-for-byte identical.
const baseline=process.env.DATAEX_TIMING_BASELINE;
if(baseline){
 const before=fs.readFileSync(path.join(baseline,'dataex-fuzzy-workspace.js'),'utf8'),after=fs.readFileSync(path.join(__dirname,'dataex-fuzzy-workspace.js'),'utf8');
 const chunk=(s,start,end)=>s.slice(s.indexOf(start),s.indexOf(end,s.indexOf(start))).trim();
 test('existing setResults implementation is unchanged',()=>assert.equal(chunk(before,'  async function setResults(input)','  function summary()'),chunk(after,'  async function setResults(input)','  async function timedSetResults(input)')));
 for(const [start,end,label]of [['  function brief()','  async function copyText','brief and Prompt'],['  async function pageText','  async function persist','PDF page reading and document map'],['  function summary()','  function render()','semantic tool response'],['  window.DataExFuzzy =','  return {tools','published snapshot schema']])test(label+' unchanged',()=>assert.equal(chunk(before,start,end),chunk(after,start,end)));
 for(const name of ['dataex-fuzzy-core.js','dataex-paper-model.js','dataex-effect-type.js','dataex-arm-ontology.js','dataex-results-model.js','dataex-decisions.js','dataex-source-navigation.js','dataex-selection.js','dataex-caption.js','dataex-visual.js'])test(name+' byte-identical',()=>assert.deepEqual(fs.readFileSync(path.join(baseline,name)),fs.readFileSync(path.join(__dirname,name))));
}
console.log(JSON.stringify({checks,passed:true}));
