const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const B=require('./dataex-decisions.js'),C=require('./dataex-confirmation.js'),D=C.wrap(B),F=require('./dataex-fuzzy-core.js'),M=require('./dataex-results-model.js'),P=require('./dataex-paper-model.js'),{fixture}=require('./dataex-fuzzy-fixture.cjs');
let checks=0;function test(label,fn){fn();checks++;console.log('PASS '+label);}
const fresh=()=>{const raw=fixture();return D.make(F.buildStudy(raw,{pdfId:raw.pdfId,filename:raw.sources[0].pdfFile,pageCount:30},[]));};
function spec(r){const a=Object.values(r.points).find(p=>p.raw.dataType==='continuous'&&p.raw.resultType==='endpoint'&&!p.raw.comparatorArmId),b=Object.values(r.points).find(p=>p.raw.outcomeId===a.raw.outcomeId&&p.raw.timepoint===a.raw.timepoint&&p.raw.resultType===a.raw.resultType&&p.raw.armId!==a.raw.armId&&!p.raw.comparatorArmId);return {id:'fixture-card',outcomeId:a.outcomeId,pointIds:[a.id,b.id],label:a.raw.outcome,comparison:{label:'Fixture comparison',intervention:a.raw.armId,comparator:b.raw.armId},timepoint:a.raw.timepoint,resultType:a.raw.resultType};}
const commit=r=>{const c=structuredClone(r);if(c.verification)c.verification.savedRevision=c.revision;return c;};
const action=(r,s=spec(r))=>({type:'UX_CONFIRM_ADOPT',resultSet:s,confirmed:true,operationId:'adopt-'+r.revision,expectedRevision:r.revision,evidence:Object.fromEntries(s.pointIds.map(id=>[id,{pdfId:r.studyId,page:r.points[id].raw.sourceAnchor.pdfPage,sourceIds:Object.values(r.points[id].raw.sourceRefs)}]))});
const adopt=r=>commit(D.apply(r,action(r)));
test('unconfirmed Raw never exports',()=>{const r=fresh();assert.equal(D.exportBasket([r]).rows.length,0);assert.equal(D.exportData([r],{confirmedStudies:false,confirmedOutcomes:false}).rows.length,0);});
test('legacy adoption retains basket/history but cannot bypass confirmation CSV gate',()=>{const r=B.apply(fresh(),{type:'RESULT_SET',resultSet:spec(fresh()),status:'ACCEPTED'});assert.equal(D.basket([r]).length,1);assert.equal(D.exportBasket([r]).rows.length,0);assert.ok(D.exportBasket([r]).warnings.some(w=>w.code==='HUMAN_CONFIRMATION_REQUIRED'));});
test('source location alone is not human confirmation',()=>{const r=fresh(),id=spec(r).pointIds[0],next=D.apply(r,{type:'POINT',id,status:'REVIEWED'});assert.equal(C.pointEligible(next,id),false);assert.equal(D.exportData([next],{confirmedStudies:false,confirmedOutcomes:false}).rows.length,0);});
test('human check is required',()=>{const r=fresh();assert.throws(()=>D.apply(r,{...action(r),confirmed:false}),/原著/);});
test('PDF hash mismatch fails closed',()=>{const r=fresh(),a=action(r);a.evidence[a.resultSet.pointIds[0]].pdfId='wrong';assert.throws(()=>D.apply(r,a),/PDF/);});
test('unresolved evidence can be manually recorded but not silently confirmed',()=>{const r=fresh(),a=action(r),e=a.evidence[a.resultSet.pointIds[0]];e.sourceIds=[];assert.throws(()=>D.apply(r,a),/手動/);e.manualNote='Fixture p.21 Table 2 inspected';assert.doesNotThrow(()=>D.apply(r,a));});
test('invalid manual page rejects whole card',()=>{for(const page of [0,31,NaN,1.5]){const r=fresh(),a=action(r);a.evidence[a.resultSet.pointIds[0]].page=page;assert.throws(()=>D.apply(r,a));assert.equal(r.revision,0);}});
test('not yet persisted is never eligible',()=>{const r=fresh(),n=D.apply(r,action(r));assert.equal(D.exportBasket([n]).rows.length,0);assert.equal(D.exportBasket([commit(n)]).rows.length,2);});
test('one card adoption changes exactly its point ids',()=>{const r=fresh(),a=action(r),n=commit(D.apply(r,a));assert.equal(D.exportBasket([n]).rows.length,2);assert.deepEqual(Object.values(n.points).filter(p=>C.pointEligible(n,p.id)).map(p=>p.id).sort(),a.resultSet.pointIds.sort());});
test('Raw snapshot, sources and original ids are lossless',()=>{const r=fresh(),n=adopt(r);assert.deepEqual(n.snapshot,r.snapshot);for(const id of Object.keys(r.points))assert.deepEqual(n.points[id].raw,r.points[id].raw);});
test('double click has one operation and one revision',()=>{const r=fresh(),a=action(r),n=D.apply(r,a),again=D.apply(n,a);assert.deepEqual(again,n);});
test('stale revision rejected',()=>{const r=adopt(fresh());assert.throws(()=>D.apply(r,{...action(r),expectedRevision:r.revision-1}),/更新/);});
for(const key of ['mean','sd','n','se','ciLow','ciHigh','unit'])test('editing '+key+' invalidates confirmation and export',()=>{const r=adopt(fresh()),id=spec(r).pointIds[0],n=commit(D.apply(r,{type:'POINT',id,status:'EDITED',patch:{[key]:key==='unit'?'new unit':key==='n'?33:key==='ciHigh'?100:key==='ciLow'?-10:1.25},operationId:'edit-'+key}));assert.equal(C.pointEligible(n,id),false);assert.equal(D.exportBasket([n]).rows.length,0);assert.deepEqual(n.snapshot.raw,r.snapshot.raw);});
test('undo retains previous event and restores exactly one operation',()=>{const r=fresh(),n=adopt(r),u=commit(D.apply(n,{type:'UX_UNDO',operationId:'undo',expectedRevision:n.revision}));assert.equal(D.exportBasket([u]).rows.length,0);assert.deepEqual(u.points,r.points);assert.equal(u.history.length,n.history.length+1);assert.equal(u.history.at(-1).undoOf,n.history.at(-1).operationId);assert.deepEqual(u.snapshot,r.snapshot);});
test('undo cannot silently cross another edit',()=>{let r=adopt(fresh());r=D.apply(r,{type:'POINT',id:spec(r).pointIds[0],status:'EDITED',patch:{mean:3}});assert.throws(()=>D.apply(r,{type:'UX_UNDO',operationId:'undo'}),/直前/);});
for(const status of ['HOLD','EXCLUDED'])test(status+' preserves Raw and history and leaves CSV',()=>{const r=adopt(fresh()),n=commit(D.apply(r,{type:'RESULT_SET',resultSet:spec(r),status,operationId:status}));assert.equal(D.exportBasket([n]).rows.length,0);assert.deepEqual(n.snapshot,r.snapshot);assert.equal(n.history.at(-1).resultSet.status,status);});
test('Master audit retains unreviewed values',()=>{const r=fresh();assert.equal(D.exportData([r],{format:'audit'}).rows.length,Object.keys(r.points).length);});
test('standard CSV never treats unknown n as zero',()=>{let r=fresh();r=D.apply(r,{type:'POINT',id:spec(r).pointIds[0],status:'EDITED',patch:{n:null}});r=adopt(r);const out=D.exportBasket([r],{format:'continuous'});assert.equal(out.rows.length,0);assert.ok(out.warnings.some(w=>/MISSING|PAIR/.test(w.code)));});
test('all Raw ids remain addressable in display cards',()=>{const r=fresh(),view=M.build(r.snapshot),cards=C.cards(P.build(view),view);assert.deepEqual([...new Set(cards.flatMap(c=>c.pointIds))].sort(),r.snapshot.raw.rawValues.map(v=>v.id).sort());});
test('cards separate time/result-type/population and retain original identifiers',()=>{const r=fresh(),view=M.build(r.snapshot),cards=C.cards(P.build(view),view);for(const c of cards){assert.equal(new Set(c.rows.map(r=>r.raw.timepoint)).size,1);assert.equal(new Set(c.rows.map(r=>r.raw.resultType)).size,1);assert.deepEqual(c.pointIds,c.rows.map(r=>r.raw.id));assert.ok(c.grouping.scale);}});
test('CSV formula strings escaped while negative numbers retain numeric sign',()=>{const r=adopt(fresh());r.snapshot.raw.study.label='=2+2';const out=D.exportBasket([r]);assert.ok(out.csv.includes("'=2+2"));assert.equal(r.snapshot.raw.study.label,'=2+2');assert.match(D.csv(['v'],[{v:-1.2}]),/"-1.2"/);});
test('unknown future fields survive decision and undo',()=>{const r=fresh();r.future={token:['preserve']};const n=adopt(r);assert.deepEqual(n.future,r.future);assert.deepEqual(D.apply(n,{type:'UX_UNDO',operationId:'undo'}).future,r.future);});
test('all mandatory versions and audit actor/time/id are recorded',()=>{const n=adopt(fresh()),h=n.history.at(-1);assert.ok(h.operationId&&h.at&&h.actor);assert.equal(n.verification.version,1);assert.equal(n.verification.savedRevision,n.revision);});
if(process.env.DATAEX_IMPORT_PAYLOAD)test('VITAL 238/65/59 and all semantic layers stay identical',()=>{const raw=JSON.parse(fs.readFileSync(process.env.DATAEX_IMPORT_PAYLOAD,'utf8').replace(/^\uFEFF/,'')),study=F.buildStudy(raw,{pdfId:raw.pdfId,filename:raw.sources[0].pdfFile,pageCount:12},[]),before=structuredClone(study),view=M.build(study),paper=P.build(view),cards=C.cards(paper,view);assert.equal(raw.rawValues.length,238);assert.equal(raw.outcomes.length,65);assert.equal(raw.sources.length,59);assert.equal(new Set(cards.flatMap(c=>c.pointIds)).size,238);assert.deepEqual(study,before);const r=D.make(study),a={...action(r,cards.find(c=>c.rows[0].raw.id==='vr3'))};const n=commit(D.apply(r,a));assert.deepEqual(n.snapshot,study);});

for(const key of ['timepoint','population','effectType','adjustment'])test('Final metadata '+key+' invalidates without rewriting Raw',()=>{const r=adopt(fresh()),id=spec(r).pointIds[0],n=commit(D.apply(r,{type:'RESULT_SET',resultSet:spec(r),status:'EDITED_DRAFT',edits:[{id,patch:{reviewerNote:'test correction'}}],metadataEdits:[{id,patch:{[key]:'corrected'}}],operationId:'metadata'}));assert.equal(C.pointEligible(n,id),false);assert.equal(D.exportBasket([n]).rows.length,0);assert.equal(n.points[id].decision.finalValue[key],'corrected');assert.deepEqual(n.snapshot,r.snapshot);});
for(const kind of ['NOT_EXTRACTED','NOT_REPORTED','ILLEGIBLE','NOT_APPLICABLE'])test('missing state '+kind+' requires explicit scope and reason',()=>{let r=fresh(),id=spec(r).pointIds[0];r=D.apply(r,{type:'POINT',id,status:'EDITED',patch:{n:null}});const a={type:'UX_MISSING',id,field:'n',kind,operationId:'missing'};assert.throws(()=>D.apply(r,a),/範囲/);const next=commit(D.apply(r,{...a,scope:'p.21 Table 2',reason:'fixture observation'}));assert.equal(next.points[id].missing.n.kind,kind);assert.deepEqual(next.snapshot,r.snapshot);assert.equal(D.exportBasket([next]).rows.length,0);const undo=commit(D.apply(next,{type:'UX_UNDO',operationId:'undo-missing'}));assert.deepEqual(undo.points[id],r.points[id]);});
test('lightweight UI state excludes raw extraction and retains only current card',()=>{const r=adopt(fresh()),ids=spec(r).pointIds,ui=C.focusState(r,ids);assert.equal(ui.snapshot,undefined);assert.equal(Object.keys(ui.points).length,ids.length);assert.equal(ui.verifiedCount,1);assert.ok(JSON.stringify(ui).length<JSON.stringify(r).length/10);});

test('corrected timepoint cannot pair with an unchanged timepoint',()=>{let r=fresh(),s=spec(r);r=D.apply(r,{type:'RESULT_SET',resultSet:s,status:'EDITED_DRAFT',edits:[{id:s.pointIds[0],patch:{reviewerNote:'fixture'}}],metadataEdits:[{id:s.pointIds[0],patch:{timepoint:'corrected time'}}]});assert.throws(()=>D.apply(r,action(r,s)),/時点/);assert.deepEqual(r.snapshot.raw,fresh().snapshot.raw);});
test('consistent corrected context can be reconfirmed without rewriting Raw',()=>{let r=fresh(),s=spec(r),before=structuredClone(r.snapshot.raw);r=D.apply(r,{type:'RESULT_SET',resultSet:s,status:'EDITED_DRAFT',edits:s.pointIds.map(id=>({id,patch:{reviewerNote:'fixture'}})),metadataEdits:s.pointIds.map(id=>({id,patch:{timepoint:'corrected time',population:'same corrected population'}}))});r=commit(D.apply(r,action(r,s)));assert.equal(r.resultSets[s.id].timepoint,'corrected time');assert.equal(D.exportBasket([r]).rows.length,2);assert.ok(D.exportBasket([r]).rows.every(row=>row.timepoint==='corrected time'));assert.deepEqual(r.snapshot.raw,before);for(const id of s.pointIds)assert.notEqual(r.points[id].raw.timepoint,'corrected time');});
test('manual source correction reconfirms Final source and retains original anchor',()=>{let r=fresh(),s=spec(r),id=s.pointIds[0],original=structuredClone(r.points[id].raw.sourceAnchor);r=D.apply(r,{type:'RESULT_SET',resultSet:s,status:'EDITED_DRAFT',edits:[{id,patch:{reviewerNote:'manual fixture check'}}],metadataEdits:[{id,patch:{sourceAnchor:{...original,pdfPage:2,pdfId:r.studyId,manualNote:'Table correction'}}}]});r=commit(D.apply(r,action(r,s)));assert.deepEqual(r.points[id].raw.sourceAnchor,original);assert.equal(D.exportBasket([r]).rows.find(row=>row.arm===r.points[id].raw.arm).source_page,2);});
test('legacy acceptance is visibly unverified in lightweight UI',()=>{const r=B.apply(fresh(),{type:'RESULT_SET',resultSet:spec(fresh()),status:'ACCEPTED'});assert.equal(C.focusState(r,spec(r).pointIds).resultSets['fixture-card'].verified,false);});
test('next skips accepted, held and excluded cards and keeps a pending candidate',()=>{const cards=['a','b','c','d','e'].map(id=>({id})),r={resultSets:{a:{status:'ACCEPTED'},b:{status:'HOLD'},c:{status:'EXCLUDED'},d:{status:'EDITED_DRAFT'}}};assert.equal(C.nextPending(r,cards,'a'),'d');assert.equal(C.nextPending(r,cards,'e'),'d');});
test('no pending card is not described as whole-paper coverage',()=>{const cards=['a','b'].map(id=>({id}));assert.equal(C.nextPending({resultSets:{a:{status:'ACCEPTED'},b:{status:'HOLD'}}},cards,'a'),null);});
test('multiple source matches remain explicit candidates, never located',()=>{const S=require('./dataex-source-navigation.js'),a={valueText:'3.2 (1.1)',pdfPage:2},result=C.sourceCandidates(a,{ok:true,resolutionStatus:'text',matchedText:'Group A 3.2 (1.1) baseline; Group B 3.2 (1.1) endpoint'},'',S.matches);assert.equal(result.status,'MULTIPLE');assert.equal(result.candidates.length,2);assert.ok(result.candidates.every(c=>c.label.includes('p.2')));});
test('failed source lookup stays unresolved, not not-reported',()=>{const S=require('./dataex-source-navigation.js');assert.equal(C.sourceCandidates({valueText:'missing'}, {ok:true,resolutionStatus:'page'},'Other source',S.matches).status,'UNRESOLVED');});
test('numeric sign and p value alone do not reorder cards',()=>{const r=fresh(),before=M.build(r.snapshot),changed=structuredClone(r.snapshot);for(const row of changed.raw.rawValues){if(row.statistics.mean!=null)row.statistics.mean=-row.statistics.mean;row.statistics.pValue=.999;}const after=M.build(changed);assert.deepEqual(C.cards(P.build(after),after).map(c=>c.id),C.cards(P.build(before),before).map(c=>c.id));});
test('unresolved and multiple evidence cannot bypass the persistence confirmation gate',()=>{for(const state of ['page','unresolved','multiple']){const r=fresh(),a=action(r),e=a.evidence[a.resultSet.pointIds[0]];e.sourceLocation=state;assert.throws(()=>D.apply(r,a),/手動確認/);e.manualNote='Fixture p.21 inspected manually';assert.doesNotThrow(()=>D.apply(r,a));}});
console.log(JSON.stringify({checks,passed:true}));
