'use strict';
const assert=require('node:assert/strict'),P=require('./dataex-paper-model.js'),D=require('./dataex-decisions.js'),F=require('./dataex-fuzzy-core.js'),{fixture,cases,footnote}=require('./dataex-recovery-effect.fixture.cjs');
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
const info=(raw,row=raw.rawValues[0])=>P.classify(row,raw.outcomes.find(o=>o.id===row.outcomeId),raw);
const freeze=x=>{if(x&&typeof x==='object'){Object.values(x).forEach(freeze);Object.freeze(x);}return x;};
function setup(){const raw=fixture(),record=D.make(F.buildStudy(raw,{pdfId:raw.pdfId,filename:raw.sources[0].pdfFile,pageCount:11},[]));record.derivedCandidates=raw.rawValues.map(row=>{const c=info(raw,row);return {...c.derived,id:'derived:'+row.id,rawId:row.id,readiness:c.readiness,baseStatistics:structuredClone(row.statistics)};});const specs=raw.rawValues.map(row=>({id:'set:'+row.id,outcomeId:record.points[row.id].outcomeId,pointIds:[row.id],label:raw.outcomes.find(o=>o.id===row.outcomeId).reportedName,comparison:{label:'Dexamethasone vs Usual care',intervention:'DEX',comparator:'UC'},timepoint:'28 days',resultType:'effect'}));return {raw,record,specs};}
const adopt=(record,spec,useDerived=true)=>D.apply(record,{type:'RESULT_SET',resultSet:spec,status:'ACCEPTED',...(useDerived?{useDerived:true,derivedCandidateIds:['derived:'+spec.pointIds[0]]}:{})});
for(const [id,name,estimate,lo,hi,rawType,kind]of cases)test('Saved '+name+' resolves '+kind+' without Raw mutation',()=>{
 const raw=freeze(fixture()),before=JSON.stringify(raw),row=raw.rawValues.find(r=>r.outcomeId===id),c=info(raw,row),d=c.derived;
 assert.equal(c.effectClassification.kind,kind);assert.equal(c.effectClassification.basis,'OUTCOME_SPECIFIC_SOURCE');assert.equal(c.readiness,'CONVERTIBLE');assert.match(c.effectClassification.reportedLabel,kind==='RATE_RATIO'?/^Age-adjusted rate ratio$/:/^Age-adjusted risk ratio$/);assert.ok(c.effectClassification.sourceIds.includes('rec-table2-ci'));
 assert.ok(!c.hint.includes('HRはRRではありません'));assert.ok(!/log\(HR\)/.test(c.hint));assert.match(c.hint,/Generic inverse variance候補/);assert.equal(d.statistics.estimate,Math.log(estimate));assert.equal(d.statistics.se,(Math.log(hi)-Math.log(lo))/(2*1.959964));assert.equal(d.effectType,kind==='RATE_RATIO'?'log Rate Ratio':'log Risk Ratio');assert.deepEqual(d.inputs,{estimate,ciLow:lo,ciHigh:hi,ciLevel:95});assert.deepEqual(d.sourceRefs,row.sourceRefs);assert.equal(row.effectMeasure,rawType);assert.equal(JSON.stringify(raw),before);
});
test('Cox estimation method does not replace the reported rate-ratio name',()=>{const c=info(fixture());assert.equal(c.effectClassification.estimationMethod,'Cox regression');assert.equal(c.effectClassification.kind,'RATE_RATIO');});
test('Mixed column without an outcome-scoped source remains unresolved',()=>{const raw=fixture();raw.sources.find(s=>s.id==='rec-table2-ci').evidenceText='Rate or Risk Ratio (95% CI)';const c=info(raw);assert.equal(c.readiness,'REVIEW');assert.equal(c.derived,undefined);assert.equal(c.effectClassification.status,'NEEDS_REVIEW');});
test('Conflicting outcome-specific source assignments require review',()=>{const raw=fixture();raw.sources[0].evidenceText+=' Risk ratios have been adjusted for age with respect to the outcome of 28-day mortality.';assert.equal(info(raw).effectClassification.status,'NEEDS_REVIEW');assert.equal(info(raw).derived,undefined);});
test('A footnote in another table does not classify this outcome',()=>{const raw=fixture();raw.rawValues[0].sourceRefs.ciLevel=raw.rawValues[0].sourceRefs.estimate;raw.sources[0].tableFigure='Table 99';assert.equal(info(raw).effectClassification.status,'NEEDS_REVIEW');});
test('An unrelated outcome does not inherit a table-wide rate or risk default',()=>{const raw=fixture();raw.sources.find(s=>s.id===raw.rawValues[0].sourceRefs.estimate).row='Renal replacement therapy';assert.equal(info(raw).effectClassification.status,'NEEDS_REVIEW');});
test('Unambiguous Rate Ratio column resolves a saved HR label',()=>{const raw=fixture();raw.sources[0].evidenceText='';raw.sources.find(s=>s.id===raw.rawValues[0].sourceRefs.estimate).column='Age-adjusted Rate Ratio (95% CI)';assert.equal(info(raw).effectClassification.kind,'RATE_RATIO');});
test('No paper name, ID, or effect-number lookup is needed',()=>{const raw=fixture();raw.study.label='Another report';raw.pdfId='other';raw.requestId='other';Object.assign(raw.rawValues[0].statistics,{estimate:.7,ciLow:.5,ciHigh:.98});assert.equal(info(raw).effectClassification.kind,'RATE_RATIO');});
test('Reported labels retain HR, OR, and distinguish rate from risk',()=>{for(const [label,kind]of [['HR','HR'],['OR','OR'],['RR','RISK_RATIO'],['Rate Ratio','RATE_RATIO'],['log Rate Ratio','RATE_RATIO'],['log Risk Ratio','RISK_RATIO']])assert.equal(P.parseEffectType(label).kind,kind);assert.equal(P.parseEffectType('Rate or Risk Ratio (95% CI)'),null);});
test('Rate CI with missing level, invalid endpoints, or strong asymmetry is not converted',()=>{for(const statistics of [{estimate:.83,ciLow:.75,ciHigh:.93},{estimate:.83,ciLow:0,ciHigh:.93,ciLevel:95},{estimate:.5,ciLow:.49,ciHigh:3,ciLevel:95}]){const raw=fixture();raw.rawValues[0].statistics=statistics;const c=info(raw);assert.equal(c.derived,undefined);assert.ok(!c.hint.includes('に変換可能'));}});
test('Already-log rate CI is not logged twice',()=>{const raw=fixture();raw.sources=[];raw.rawValues[0].effectMeasure='log Rate Ratio';raw.rawValues[0].statistics={estimate:Math.log(.83),ciLow:Math.log(.75),ciHigh:Math.log(.93),ciLevel:95};const d=info(raw).derived;assert.equal(d.statistics.estimate,Math.log(.83));assert.equal(d.statistics.se,(Math.log(.93)-Math.log(.75))/(2*1.959964));assert.match(d.formula,/reported log effect/);});
test('Proposed or Raw-only acceptance never silently enters GIV',()=>{let {record,specs}=setup();assert.equal(D.basket([record]).length,0);for(const s of specs)record=adopt(record,s,false);assert.equal(D.exportBasket([record],{format:'giv'}).rows.length,0);});
test('Human-adopted GIV exports two log Rate Ratios and three log Risk Ratios',()=>{let {record,specs}=setup();const before=JSON.stringify(record.snapshot.raw);for(const s of specs)record=adopt(record,s);const out=D.exportBasket([record],{format:'giv'});assert.equal(out.blocked,false);assert.equal(out.rows.length,5);assert.deepEqual(out.rows.map(r=>r.Effect_Type),['log Rate Ratio','log Rate Ratio','log Risk Ratio','log Risk Ratio','log Risk Ratio']);assert.ok(!out.csv.includes('log(HR)'));assert.equal(JSON.stringify(record.snapshot.raw),before);out.rows.forEach((r,i)=>{assert.equal(r.Effect,Math.log(cases[i][2]));assert.equal(r.SE,(Math.log(cases[i][4])-Math.log(cases[i][3]))/(2*1.959964));assert.match(r.Comparison_Direction,/Dexamethasone vs Usual care/);});assert.equal(D.exportBasket([record],{format:'binary'}).rows.length,0);});
test('Master and audit preserve original effect names, effect and CI after adoption',()=>{let {record,specs}=setup();for(const s of specs)record=adopt(record,s);const master=D.exportBasket([record],{format:'master'}),audit=D.exportData([record],{format:'audit'});assert.equal(master.rows.length,5);master.rows.forEach((r,i)=>{assert.equal(r.effect_type,cases[i][5]);assert.equal(r.effect,cases[i][2]);assert.equal(r.ci_low,cases[i][3]);assert.equal(r.ci_high,cases[i][4]);});assert.equal(audit.rows.length,5);assert.equal(record.history.filter(h=>h.action==='RESULT_SET').length,5);});
test('Previously adopted HR classification is held for re-adoption, not silently renamed',()=>{let {record,specs}=setup();record=adopt(record,specs[0]);const d=record.resultSets[specs[0].id].acceptedDerived[0];d.effectClassification.kind='HR';d.effectType='log(HR)';const before=JSON.stringify(record),out=D.exportBasket([record],{format:'giv'});assert.equal(out.rows.length,0);assert.equal(out.blocked,true);assert.ok(out.warnings.some(w=>w.code==='DERIVED_MEASURE'));assert.equal(JSON.stringify(record),before);});
test('Legacy accepted conversion without classification also detects old HR mismatch',()=>{let {record,specs}=setup();record=adopt(record,specs[0]);const d=record.resultSets[specs[0].id].acceptedDerived[0];delete d.effectClassification;delete d.effectType;assert.equal(D.exportBasket([record],{format:'giv'}).blocked,true);});
test('Raw rate ratio plus log-scale SE cannot bypass explicit conversion',()=>{const {record,specs}=setup();let r=adopt(record,specs[0],false);r.points[specs[0].pointIds[0]].decision.finalValue.effectType='Age-adjusted rate ratio';r.points[specs[0].pointIds[0]].decision.finalValue.se=.05;const out=D.exportData([r],{format:'giv',confirmedStudies:false,confirmedOutcomes:false,pairs:{[r.id]:{intervention:'DEX',comparator:'UC'}}});assert.equal(out.rows.length,0);assert.ok(out.warnings.some(w=>w.code==='LOG_EFFECT'));});
console.log(JSON.stringify({checks,ok:true}));
