const {chromium}=require(process.env.DATAEX_PLAYWRIGHT_MODULE||'playwright');
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1400,height:950}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.registeredTools[t.name]=t;}}});});
 const ready=()=>page.waitForFunction(()=>Object.keys(window.registeredTools).length===7);
 await page.goto(process.env.DATAEX_URL||'http://127.0.0.1:8767/dataex-chatgpt.html');await ready();
 const call=async(name,args={})=>page.evaluate(async({name,args})=>window.registeredTools[name].execute(args),{name,args});
 const load=async name=>{await page.locator('#pdf-file').setInputFiles(path.join(process.env.DATAEX_PDF_DIR||__dirname,name));await page.waitForFunction(()=>document.querySelector('#pdf-status').textContent.startsWith('✓'));};
 const field=k=>page.locator('#profile-form [data-field="'+k+'"]');
 await page.locator('#intervention').fill('Ketamine');await page.locator('#comparator').fill('Placebo');
 await page.locator('#profile-open').click();await field('profileName').fill('Pain review');await field('reviewOutcomeName').fill('Pain intensity');await field('targetTime').fill('Post Wk 1–2');await field('timeSelectionRule').selectOption('exact only');
 await field('preferredMeasures').fill('Overall pain level (NRS 0–10)');
 await page.locator('#profile-form > details > summary').click();await field('allowSEtoSD').check();
 await page.locator('#profile-form > details > summary').click();
 await page.locator('#profile-dialog').evaluate(e=>e.scrollTop=0);
 await page.screenshot({path:path.join(process.env.DATAEX_ARTIFACT_DIR||__dirname,'phase271-profile.png')});
 assert.equal(await field('interventionDefinition').count(),0);assert.equal(await field('comparatorDefinition').count(),0);for(const key of ['timeWindowLower','timeWindowUpper','timeUnit'])assert.equal(await field(key).count(),0);assert.equal(await field('preferredPopulation').isVisible(),false);assert.equal(await field('preferredMeasures').isVisible(),true);assert.deepEqual(await field('timeSelectionRule').locator('option').allTextContents(),['完全一致のみ','指定範囲内で最も近い時点','指定範囲内で最も早い時点','指定範囲内で最も遅い時点','原著の代表時点']);
 await page.locator('#profile-save').click();assert.equal(await page.locator('#profile-dialog').isVisible(),false);assert.equal(await page.locator('#intervention').inputValue(),'Ketamine');assert.equal(await page.locator('#comparator').inputValue(),'Placebo');
 assert.equal(await page.locator('#outcomes').inputValue(),'Pain intensity');assert.equal(await page.locator('#timepoint').inputValue(),'Post Wk 1–2');
 await load('schwartzman2009.pdf');let brief=await call('dataex_get_extraction_brief');assert.equal(brief.activeReviewProfile.profileName,'Pain review');assert.equal(brief.profileRulesApplied.outcomes[0].preferredMeasures[0],'Overall pain level (NRS 0–10)');assert.equal(brief.profileRulesApplied.outcomes[0].timeSelectionRule,'exact only');assert.equal(brief.profileRulesApplied.outcomes[0].applyTimeRule,true);
 await page.locator('#timepoint').fill('Post Wk 3–4');brief=await call('dataex_get_extraction_brief');assert.equal(brief.timepoint,'Post Wk 3–4');assert.equal(brief.activeReviewProfile.outcomes[0].targetTime,'Post Wk 1–2');assert.equal(brief.profileRulesApplied.outcomes[0].applyTimeRule,false);
 await page.reload();await ready();assert.equal(await page.locator('#timepoint').inputValue(),'Post Wk 3–4');await load('schwartzman2009.pdf');brief=await call('dataex_get_extraction_brief');assert.equal(brief.profileRulesApplied.fieldProvenance.timepoint,'current PDF form explicit input');
 await load('Lumanauw 2019.pdf');assert.equal(await page.locator('#timepoint').inputValue(),'Post Wk 1–2');await load('schwartzman2009.pdf');assert.equal(await page.locator('#timepoint').inputValue(),'Post Wk 3–4');
 // Reapply consciously after PDF-specific override, then export and duplicate.
 await page.locator('#profile-open').click();const downloadPromise=page.waitForEvent('download');await page.locator('#profile-export').click();const download=await downloadPromise;const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(exported.profiles[0].profile.allowSEtoSD,true);assert.equal('interventionDefinition' in exported.profiles[0].profile,false);assert.equal('comparatorDefinition' in exported.profiles[0].profile,false);exported.profiles[0].profile.interventionDefinition='OLD WRONG INTERVENTION';exported.profiles[0].profile.comparatorDefinition='OLD WRONG COMPARATOR';exported.profiles[0].profile.outcomes[0].timeSelectionRule='exact interval';
 await page.locator('#profile-duplicate').click();await field('profileName').fill('Pain review copy renamed');await page.locator('#profile-save').click();assert.match(await page.locator('#profile-bar').innerText(),/copy renamed/);
 await page.locator('#profile-open').click();await page.locator('#profile-delete').click();assert.match(await page.locator('#profile-bar').innerText(),/未設定/);
 const importFile=async data=>page.locator('#profile-import-file').setInputFiles({name:'profile.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});
 const corrupt=structuredClone(exported);corrupt.profiles[0].profile.requireExplicitMatchingNForSEtoSD=false;await importFile(corrupt);await page.waitForFunction(()=>document.querySelector('#profile-message').textContent.includes('インポートできません'));assert.match(await page.locator('#profile-message').innerText(),/変更できません/);
 await importFile(exported);await page.waitForFunction(()=>document.querySelector('#profile-message').textContent.includes('1件インポート'));await page.locator('#profile-apply').click();
 brief=await call('dataex_get_extraction_brief');assert.equal(brief.intervention,'Ketamine');assert.equal(brief.comparator,'Placebo');assert.equal('interventionDefinition' in brief.activeReviewProfile,false);assert.equal('comparatorDefinition' in brief.activeReviewProfile,false);assert.equal(brief.activeReviewProfile.outcomes[0].timeSelectionRule,'exact only');assert.equal('timeWindowLower' in brief.activeReviewProfile.outcomes[0],false);assert.equal('preferredPopulation' in brief.activeReviewProfile.outcomes[0],false);
 assert.equal(await page.locator('#timepoint').inputValue(),'Post Wk 1–2');
 // Explicit blank is unresolved, not permission to resurrect the profile time.
 await page.locator('#timepoint').fill('');brief=await call('dataex_get_extraction_brief');assert.equal(brief.timepoint,'');assert.equal(brief.profileRulesApplied.fieldProvenance.timepoint,'current PDF form explicit input');
 await page.locator('#profile-open').click();await page.locator('#profile-apply').click();
 // Real Schwartzman Table 2 text: profile resolves measure/time, never missing n.
 await call('dataex_get_document_map',{keywords:['Overall pain level','Table 2']});await call('dataex_search_pdf',{query:'Overall pain level',pageStart:5,pageEnd:5});await call('dataex_search_pdf',{query:'Post Wk 1–2',pageStart:5,pageEnd:5});
 const p5=await call('dataex_get_page_text',{page:5,maxChars:12000});assert.match(p5.normalizedText,/Overall pain level Placebo 7.62 ± 0.6 7.61 ± 0.6/);
 const src=(use,text,row='Overall pain level / Ketamine',column='Post Wk 1–2',page=5)=>({use,page,printedPage:null,section:'Table 2',tableFigure:'Table 2',row,column,evidenceText:text,focusQuery:text,verification:'SOURCE_VERIFIED_TEXT'});
 const o={outcome:'Pain intensity',compatibility:'EXACT',requestedValue:'Overall pain level (NRS 0–10), Post Wk 1–2',relatedEvidence:[],reason:'レビューの優先項目・時点に一致。対応n未解決のためSDは導出しない。',analysisAction:'REVIEW',searchAudit:{searchComplete:false,queries:[],pagesChecked:[5],sectionsChecked:['Table 2'],notes:null},timepoint:'Post Wk 1–2',population:'試験完了者；当該セルのnは未確定',analysisUnit:'participant',variableType:'continuous',status:'CANDIDATE_ONLY',arms:[{name:'Ketamine',valueText:'6.28 ± 0.9 (mean ± SE)',mean:6.28,se:.9,sd:null,numerator:null,denominator:null},{name:'Placebo',valueText:'7.61 ± 0.6 (mean ± SE)',mean:7.61,se:.6,sd:null,numerator:null,denominator:null}],effect:null,derivation:null,sources:[src('mean','Ketamine 7.76 ± 0.4 6.28 ± 0.9'),src('mean','Overall pain level Placebo 7.62 ± 0.6 7.61 ± 0.6','Overall pain level / Placebo'),src('se','The table entries are given as (means ± SE).')],note:null,reviewFlags:['対応n未解決']};
 const payload={study:'Schwartzman 2009 — Review Profile regression',summaryStatus:'NEEDS_REVIEW',outcomes:[o],unresolved:[]};let result=await call('dataex_set_results',payload);assert.equal(result.needsReview,1);assert.equal(result.ready,0);
 const unsafe=structuredClone(payload);unsafe.summaryStatus='READY';unsafe.outcomes[0].status='READY';result=await call('dataex_set_results',unsafe);assert.equal(result.isError,true);
 const converted=structuredClone(payload);converted.outcomes[0].arms.forEach((a,i)=>{a.denominator=i?10:9;a.sd=a.se*Math.sqrt(a.denominator);});converted.outcomes[0].derivation={label:'SE to SD',formula:'SD = SE × sqrt(n)',inputs:['completers 9/10'],assumption:'completer N'};result=await call('dataex_set_results',converted);assert.equal(result.isError,true);
 converted.outcomes[0].arms.forEach(a=>a.se=null);result=await call('dataex_set_results',converted);assert.equal(result.isError,true);
 assert.equal(await page.locator('.result-card .status-CANDIDATE_ONLY').count(),1);
 result=await call('dataex_focus_evidence',{page:5,query:'Ketamine 7.76 ± 0.4 6.28 ± 0.9'});assert.ok(result.ok&&result.highlightedCount>0);
 await page.screenshot({path:path.join(process.env.DATAEX_ARTIFACT_DIR||__dirname,'phase271-schwartzman.png')});
 // Capacity is checked before any write; malformed import is atomic.
 await page.locator('#profile-open').click();const before=await page.evaluate(()=>localStorage.getItem('dataex:review-profiles:v1'));await importFile({version:1,profiles:Array.from({length:20},()=>exported.profiles[0])});await page.waitForFunction(()=>document.querySelector('#profile-message').textContent.includes('インポートできません'));assert.equal(await page.evaluate(()=>localStorage.getItem('dataex:review-profiles:v1')),before);
 await page.locator('#profile-new').click();await field('profileName').fill('Multiple outcomes');await field('targetTime').fill('1–2 weeks');await field('reviewOutcomeName').fill('Pain');await page.locator('#profile-add-outcome').click();await field('reviewOutcomeName').nth(1).fill('Function');await page.locator('#profile-save').click();assert.equal(await page.locator('#outcomes').inputValue(),'Pain\nFunction');const savedProfile=await page.evaluate(()=>JSON.parse(localStorage.getItem('dataex:review-profiles:v1')).profiles.at(-1).profile);assert.equal(savedProfile.outcomes[0].timeWindowLower,'1');assert.equal(savedProfile.outcomes[0].timeWindowUpper,'2');assert.equal(savedProfile.outcomes[0].timeUnit,'weeks');assert.equal('interventionDefinition' in savedProfile,false);await page.locator('#profile-open').click();await page.locator('#profile-off').click();brief=await call('dataex_get_extraction_brief');assert.equal(brief.activeReviewProfile,null);assert.equal(brief.profileRulesApplied.fieldProvenance.outcomes,'current PDF form explicit input');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(process.env.DATAEX_ARTIFACT_DIR||__dirname,'phase271-test-result.json'),JSON.stringify({profileCRUD:true,importExport:true,temporaryOverrides:true,reload:true,newPdfDefaults:true,matchingNGuard:true,schwartzman:'CANDIDATE_ONLY',highlightedCount:result.highlightedCount,tools:7,consoleErrors:errors},null,2));
 const legacyPage=await browser.newPage();await legacyPage.addInitScript(({profile})=>{localStorage.setItem('dataex:review-profiles:v1',JSON.stringify({version:1,activeId:'legacy',profiles:[{id:'legacy',profile}]}));}, {profile:exported.profiles[0].profile});await legacyPage.goto(process.env.DATAEX_URL||'http://127.0.0.1:8767/dataex-chatgpt.html');await legacyPage.waitForSelector('#profile-open');assert.equal(await legacyPage.locator('#intervention').inputValue(),'');assert.equal(await legacyPage.locator('#comparator').inputValue(),'');assert.equal(await legacyPage.locator('#outcomes').inputValue(),'Pain intensity');await legacyPage.locator('#profile-open').click();assert.equal(await legacyPage.locator('[data-field=targetTime]').inputValue(),'Post Wk 1–2');await legacyPage.locator('#profile-save').click();const legacySaved=await legacyPage.evaluate(()=>JSON.parse(localStorage.getItem('dataex:review-profiles:v1')).profiles[0].profile);assert.equal('interventionDefinition' in legacySaved,false);assert.equal('comparatorDefinition' in legacySaved,false);await legacyPage.close();
 await browser.close();console.log('PASS Phase 2.7.1 simplified profile CRUD, export/import validation/capacity, PDF-scoped override/reload/reuse, brief precedence, Schwartzman candidate and n guard, highlight, 7 tools, no console errors');
})().catch(e=>{console.error(e);process.exit(1);});
