const assert=require('node:assert/strict'),fs=require('node:fs');
const D=require('./dataex-decisions.js'),F=require('./dataex-fuzzy-core.js'),M=require('./dataex-results-model.js'),ICO=require('./dataex-ico-mapping.js');
const {fixture}=require('./dataex-fuzzy-fixture.cjs');
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
const context={reviewName:'v4 unit test',intervention:'Acupuncture',comparator:'Usual care',outcomes:['Disability']};
function fresh(){const raw=fixture(),s=F.buildStudy(raw,{pdfId:raw.pdfId,filename:raw.sources[0].pdfFile,pageCount:10},[]);return D.make({...s,extractionContext:context});}
const finalize=(r,id='O3',edits=[])=>D.apply(r,{type:'FINALIZE_OUTCOME',id,edits,allowIncomplete:true});
test('SR Disability maps Roland without exact strings',()=>{const o=fixture().outcomes[2],m=ICO.outcome(o,context);assert.equal(m.reviewConcept,'Disability');assert.equal(m.relation,'COMPATIBLE');assert.equal(M.build(fresh().snapshot,context).primary.find(x=>x.id==='O3').reviewMapping.reviewConcept,'Disability');});
test('Distinct pain constructs never map to Disability or Pain',()=>{for(const name of ['Symptom bothersomeness','Pain interference','Pressure pain threshold','Analgesic medication use'])for(const target of ['Disability','Pain'])assert.equal(ICO.outcome({reportedName:name,mapping:{target,relation:'COMPATIBLE'}},{outcomes:[target]}),null);});
test('Known RMDQ and ODI terminology remains a candidate',()=>{for(const reportedName of ['RMDQ','Oswestry Disability Index','ODI'])assert.equal(ICO.outcome({reportedName},context).needsReview,true);});
test('AI semantic mapping supports unfamiliar instruments',()=>{assert.equal(ICO.outcome({reportedName:'Some original measure',mapping:{target:'Review concept',relation:'COMPATIBLE',reason:'Methods definition'}},{outcomes:['Review concept']}).reason,'Methods definition');});
test('All four arms stay separate and simulated is not intervention',()=>{const maps=ICO.arms(fixture(),context);assert.equal(maps.length,4);assert.deepEqual(maps.map(m=>m.reviewConcept),['Acupuncture','Acupuncture',null,'Usual care']);});
test('Free-text AI arm roles support Real acupuncture and Usual care control',()=>{const raw=fixture();raw.study.arms.forEach((a,i)=>a.role=['Real acupuncture','Real acupuncture','Non-insertive simulated acupuncture control','Usual care control'][i]);assert.deepEqual(ICO.arms(raw,context).map(m=>m.reviewConcept),['Acupuncture','Acupuncture',null,'Usual care']);});
test('Explicit sham comparator remains separate',()=>{const maps=ICO.arms(fixture(),{...context,comparator:'Sham acupuncture'});assert.equal(maps[2].reviewConcept,'Sham acupuncture');assert.equal(maps[2].armId,'A3');});
test('Mapping guidance appends the unchanged full Fuzzy Core',()=>{const base=F.prompt(context,[],[]),next=ICO.prompt(F,context,[],[]);assert.ok(next.prompt.startsWith(base.prompt));assert.equal(next.corePromptVersion,base.corePromptVersion);assert.ok(next.prompt.includes('Methods'));assert.ok(next.prompt.includes('not an exact-string filter'));});
test('Empty Outcomes preserves Discovery and automatic primary selection',()=>{const r=fresh(),c={...context,outcomes:[]};assert.equal(ICO.prompt(F,c,[],[]).mode,'DISCOVERY');assert.equal(ICO.outcome(r.snapshot.raw.outcomes[2],c),null);assert.equal(M.build(r.snapshot,c).rawCount,r.snapshot.raw.rawValues.length);});
test('Finalization atomically saves pending corrections and confirms',()=>{const r=fresh(),p=D.bulkPoints(r,'O3')[0],before=JSON.stringify(r),next=finalize(r,'O3',[{id:p.id,patch:{mean:6.4,n:null,reviewerNote:'test only'}}]);assert.equal(next.points[p.id].raw.mean,8);assert.equal(next.points[p.id].decision.finalValue.mean,6.4);assert.equal(next.points[p.id].decision.status,'EDITED');assert.equal(next.outcomes.O3.status,'CONFIRMED');assert.equal(JSON.stringify(r),before);assert.equal(next.revision,r.revision+1);assert.equal(next.history.at(-1).changes[0].before.finalValue,null);});
test('Invalid pending edit cannot partially adopt or finalize',()=>{const r=fresh(),id=D.bulkPoints(r,'O3')[0].id,original=JSON.stringify(r);assert.throws(()=>finalize(r,'O3',[{id,patch:{sd:-1}}]));assert.equal(JSON.stringify(r),original);});
test('Pending edits cannot target another Outcome',()=>{const r=fresh();assert.throws(()=>finalize(r,'O3',[{id:D.bulkPoints(r,'O1')[0].id,patch:{mean:6.4}}]));});
test('Missing n is retained with explicit finalization',()=>{let r=fresh(),id=D.bulkPoints(r,'O3')[0].id;r=finalize(r,'O3',[{id,patch:{n:null}}]);assert.equal(r.points[id].decision.finalValue.n,null);assert.ok(D.warnings(r,'O3').some(s=>s.includes('n')));});
test('Finalization preserves individually excluded and held points',()=>{let r=fresh(),ps=D.bulkPoints(r,'O1');r=D.apply(r,{type:'POINT',id:ps[0].id,status:'HOLD'});r=D.apply(r,{type:'POINT',id:ps[1].id,status:'EXCLUDED'});r=finalize(r,'O1');assert.equal(r.points[ps[0].id].decision.status,'HOLD');assert.equal(r.points[ps[1].id].decision.status,'EXCLUDED');});
test('Outcome reopen retains Raw, Final and prior confirmation history',()=>{let r=fresh(),id=D.bulkPoints(r,'O3')[0].id;r=finalize(r,'O3',[{id,patch:{mean:6.4}}]);r=D.apply(r,{type:'CONFIRM_STUDY'});const raw=JSON.stringify(r.snapshot.raw),final=JSON.stringify(r.points[id].decision);r=D.apply(r,{type:'REOPEN_OUTCOME',id:'O3'});assert.equal(r.outcomes.O3.status,'DRAFT');assert.equal(r.confirmedAt,null);assert.equal(JSON.stringify(r.snapshot.raw),raw);assert.equal(JSON.stringify(r.points[id].decision),final);assert.equal(r.history.at(-1).beforeOutcome.status,'CONFIRMED');});
test('Normal CSV uses Final and audit contains Raw plus Final',()=>{let r=fresh(),id=D.bulkPoints(r,'O3')[0].id;r=D.apply(finalize(r,'O3',[{id,patch:{mean:6.4}}]),{type:'CONFIRM_STUDY'});assert.equal(D.exportData([r]).rows[0].mean,6.4);const a=D.exportData([r],{format:'audit'}).rows.find(p=>p.raw_id===id);assert.equal(JSON.parse(a.raw_value).mean,8);assert.equal(JSON.parse(a.final_value).mean,6.4);});
test('Mapping is learned only after human Outcome confirmation',()=>{const r=fresh();assert.equal(ICO.learned([r],context).length,0);const saved=finalize(r);const m=ICO.learned([saved],context)[0];assert.equal(m.reviewConcept,'Disability');assert.ok(m.acceptedPaperTerms.includes('Roland disability score'));assert.equal(m.recordId,r.id);});
test('Mapping learning is project scoped and excluded after unconfirm',()=>{const r=finalize(fresh());assert.equal(ICO.learned([r],{reviewName:'another review'}).length,0);assert.equal(ICO.learned([D.apply(r,{type:'REOPEN_OUTCOME',id:'O3'})],context).length,0);});
test('Learned terminology is advisory and cannot cross constructs',()=>{const learned=[{reviewConcept:'Pain',acceptedPaperTerms:['Symptom bothersomeness'],construct:'bothersomeness'}];assert.equal(ICO.outcome({reportedName:'Symptom bothersomeness'},{outcomes:['Pain']},learned),null);});
test('Existing version 1 records without mapping remain readable',()=>{const r=fresh();for(const o of Object.values(r.outcomes))delete o.reviewMapping;D.assertRecord(r);assert.ok(finalize(r).outcomes.O3.reviewMapping);assert.equal(D.VERSION,1);});
if(process.env.DATAEX_CHERKIN_RAW){
 test('Cherkin 2009: Raw 6.3 / Final 6.4, reopen and both CSVs',()=>{const raw=JSON.parse(fs.readFileSync(process.env.DATAEX_CHERKIN_RAW,'utf8')),before=JSON.stringify(raw),study=F.buildStudy(raw,{pdfId:raw.pdfId,filename:raw.sources[0].pdfFile,pageCount:22},[]);let r=D.make({...study,extractionContext:context});const p=Object.values(r.points).find(p=>p.raw.mean===6.3&&p.raw.sd===5.7&&/Standardized/i.test(p.raw.arm)&&p.raw.timepoint==='8 weeks');assert.ok(p);r=D.apply(r,{type:'FINALIZE_OUTCOME',id:p.outcomeId,edits:[{id:p.id,patch:{mean:6.4}}],allowIncomplete:true});r=D.apply(r,{type:'REOPEN_OUTCOME',id:p.outcomeId});assert.equal(r.points[p.id].raw.mean,6.3);assert.equal(r.points[p.id].decision.finalValue.mean,6.4);r=D.apply(finalize(r,p.outcomeId),{type:'CONFIRM_STUDY'});assert.ok(D.exportData([r]).rows.some(x=>x.mean===6.4));const audit=D.exportData([r],{format:'audit'}).rows.find(x=>x.raw_id===p.id);assert.equal(JSON.parse(audit.raw_value).mean,6.3);assert.equal(JSON.parse(audit.final_value).mean,6.4);assert.equal(JSON.stringify(r.snapshot.raw),before);});
}
console.log(JSON.stringify({checks,ok:true}));
