const {chromium}=require(process.env.DATAEX_PLAYWRIGHT_MODULE||'playwright'),{PDFDocument}=require(process.env.DATAEX_PDFLIB_MODULE||'pdf-lib');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=process.env.DATAEX_ARTIFACT_DIR||__dirname,assets=process.env.DATAEX_PDF_DIR||path.join(__dirname,'test-assets');
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1500,height:1600}}),errors=[],requests=[],passed=[];try{
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(r.method()!=='GET')requests.push(r.url());});
 await page.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.registeredTools[t.name]=t;}}});});
 const ready=()=>page.waitForFunction(()=>Object.keys(window.registeredTools).length===10);await page.goto(process.env.DATAEX_URL||'http://127.0.0.1:8766/dataex-chatgpt.html');await ready();
 const call=(name,args={})=>page.evaluate(({name,args})=>window.registeredTools[name].execute(args),{name,args});
 const load=async file=>{await page.locator('#pdf-file').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#pdf-status').textContent.startsWith('✓'));};
 const showConditions=async()=>{if(!await page.locator('#condition-content').isVisible())await page.locator('#toggle-conditions').click();};
 const conditions=async outcome=>{await showConditions();await page.locator('#intervention').fill('FYB201');await page.locator('#comparator').fill('Reference ranibizumab');await page.locator('#outcomes').fill(outcome);await page.locator('#timepoint').fill('');};
 const select=async(n,r)=>{await page.locator('#page-number').fill(String(n));await page.locator('#page-number').dispatchEvent('change');await page.waitForFunction(n=>document.querySelector('#pdf-page-'+n+' canvas'),n);await page.locator('#selection-region').click();await page.locator('#pdf-page-'+n).scrollIntoViewIfNeeded();const b=await page.locator('#pdf-page-'+n).boundingBox();await page.mouse.move(b.x+r.x*b.width,b.y+r.y*b.height);await page.mouse.down();await page.mouse.move(b.x+(r.x+r.width)*b.width,b.y+(r.y+r.height)*b.height,{steps:8});await page.mouse.up();await page.locator('#selection-preview').click();await page.locator('#selection-dialog').waitFor({state:'visible'});await page.locator('#crop-use').click();};
 const audit={valuesClearlyVisible:true,labelsClearlyVisible:true,unitsClearlyVisible:true,timepointClearlyVisible:true,uncertaintyTypeClearlyVisible:true,notes:'Table labels and raw arm values visually inspected in test fixture.'};
 const arm=(name,mean,sd,denominator)=>({name,valueText:`Mean ${mean} / SD ${sd} / n ${denominator}`,numerator:null,denominator,mean,sd,se:null});
 const name='Change in BCVA from baseline to 8 to 12 weeks';
 const outcome={outcome:name,timepoint:'week 8',population:'US-relevant population, full analysis set; assessed patients',unit:'ETDRS letters',analysisUnit:'participant',variableType:'continuous',arms:[arm('FYB201',5.1,7.52,228),arm('Reference ranibizumab',5.6,8.63,233)],directVisibleValues:['Mean change from baseline, ETDRS letters (SD): 5.1 (7.52), 5.6 (8.63)','Patients with assessment: 228, 233'],derivedValues:[],approximate:false,reason:'Raw Table 2 mean/SD and observed n; ANCOVA LS mean/SE excluded.',reviewFlags:[]};
 await load(path.join(assets,'Holz 2020.pdf'));await conditions(name);await select(5,{x:.065,y:.062,width:.88,height:.263});
 let c=await call('dataex_get_selection_context');assert.ok(c.selectionId);assert.equal(c.cropVisible,false);assert.ok(JSON.stringify(c).length<6000);assert.ok(!/base64,|data:image|blob:/.test(JSON.stringify(c)));
 let payload={selectionId:c.selectionId,sourceKind:'TABLE_DIRECT',resultStatus:'READY',outcomes:[outcome],visualAudit:audit};assert.equal((await call('dataex_set_selection_result',payload)).isError,true);
 await page.locator('#selection-extract').click();await page.waitForFunction(()=>document.querySelector('#selection-preview-title').textContent.includes('AI確認用'));assert.equal((await call('dataex_get_selection_context')).cropVisible,true);
 await page.setViewportSize({width:1450,height:1000});await page.screenshot({path:path.join(out,'phase32-ai-table.png')});const tableImage=await page.locator('#selection-image').screenshot();
 const fit=await page.locator('#selection-image').boundingBox(),stage=await page.locator('#selection-image-stage').boundingBox();assert.ok(fit.width<=stage.width&&fit.height<=stage.height,'crop fully visible');
 let result=await call('dataex_set_selection_result',payload);assert.equal(result.ok,true,JSON.stringify(result));assert.deepEqual(result.summaryCounts,{use:1,review:0,doNotUse:0,total:1});assert.equal(await page.locator('.visual-result-card').count(),1);
 assert.equal((await call('dataex_set_selection_result',payload)).summaryCounts.total,1,'idempotent retry');await page.locator('#crop-back-pdf').click();
 assert.match(await page.locator('.visual-result-card').innerText(),/解析投入可/);assert.match(await page.locator('.visual-result-card .review-state').innerText(),/未確認/);for(const label of ['承認','要確認','却下']){await page.locator('.visual-result-card').getByRole('button',{name:label,exact:true}).click();assert.match(await page.locator('#review-summary').innerText(),/解析投入可 1.*要確認 0/);}
 await page.locator('.visual-result-card').getByRole('button',{name:'選択範囲を見る'}).click();assert.equal(await page.locator('#pdf-page-5 .manual-selection').count(),1);
 // A separate text result must stay alongside visual results, with one shared summary.
 const src={use:'mean',page:5,printedPage:null,section:'Table 2',tableFigure:null,row:null,column:null,evidenceText:'Mean change from baseline, ETDRS letters (SD) 5.1 (7.52) 5.6 (8.63) 5.4 (8.10)',focusQuery:'5.1 (7.52)',verification:'SOURCE_VERIFIED_TEXT'};
 const text={study:'Holz 2020',summaryStatus:'PARTIAL',outcomes:[{outcome:'Text candidate',timepoint:'week 8',population:'FAS',analysisUnit:'participant',variableType:'continuous',status:'CANDIDATE_ONLY',compatibility:'EXACT',requestedValue:'Raw BCVA',relatedEvidence:[],reason:'Test existing text candidate.',analysisAction:'REVIEW',searchAudit:{searchComplete:false,queries:[],pagesChecked:[],sectionsChecked:[],notes:null},arms:[arm('FYB201',5.1,7.52,228)],effect:null,derivation:null,sources:[src],note:null,reviewFlags:[]}],unresolved:[]};
 result=await call('dataex_set_results',text);assert.equal(result.displayed,2);assert.equal(await page.locator('.result-card').count(),2);assert.ok((await call('dataex_focus_evidence',{page:5,query:'5.1 (7.52)'})).ok);assert.equal(await page.locator('.manual-selection').count(),1);
 await page.reload();await ready();assert.equal(await page.locator('.visual-result-card').count(),1);assert.equal(await page.locator('.visual-result-card button').first().isDisabled(),true);await load(path.join(assets,'Holz 2020.pdf'));await page.locator('.visual-result-card button').first().click();await page.locator('#pdf-page-5 .manual-selection').waitFor({state:'visible'});assert.equal(await page.locator('#pdf-page-5 .manual-selection').count(),1);assert.equal(await page.evaluate(()=>window.DataExSelection.getActiveCropBlob()),null,'no image persisted');
 passed.push('Holz Table 2 READY; append and deduplicate; shared summary with text; source rectangle after reload; independent human review');
 // New selection and condition-bound result registration.
 await conditions(name);await page.setViewportSize({width:1500,height:1600});await select(5,{x:.065,y:.062,width:.88,height:.263});c=await call('dataex_get_selection_context');payload.selectionId=c.selectionId;await call('dataex_prepare_selection_for_ai',{selectionId:c.selectionId});
 const bad=async mutate=>{const p=structuredClone(payload);mutate(p);return call('dataex_set_selection_result',p);};
 assert.equal((await bad(p=>p.selectionId='stale')).isError,true);assert.equal((await bad(p=>p.outcomes[0].arms[0].sd=-1)).isError,true);assert.equal((await bad(p=>p.outcomes[0].outcome='Unrequested')).isError,true);assert.equal((await bad(p=>p.outcomes[0].arms[0].name='Wrong arm')).isError,true);
 result=await bad(p=>p.outcomes[0].arms[0].denominator=null);assert.equal(result.outcomes[0].status,'CANDIDATE_ONLY');result=await bad(p=>p.visualAudit.unitsClearlyVisible=false);assert.equal(result.outcomes[0].status,'CANDIDATE_ONLY');result=await bad(p=>p.outcomes[0].arms[0].sd=null);assert.equal(result.outcomes[0].status,'CANDIDATE_ONLY');result=await bad(p=>p.resultStatus='READY_DERIVED');assert.equal(result.outcomes[0].status,'CANDIDATE_ONLY');
 await page.locator('#crop-back-pdf').click();await conditions('BCVA at week 24');assert.equal((await call('dataex_set_selection_result',payload)).isError,true);
 await select(5,{x:.06,y:.635,width:.88,height:.28});c=await call('dataex_get_selection_context');await call('dataex_prepare_selection_for_ai',{selectionId:c.selectionId});const figure={selectionId:c.selectionId,sourceKind:'FIGURE_ESTIMATE',resultStatus:'READY',outcomes:[{...structuredClone(outcome),outcome:'BCVA at week 24',timepoint:'week 24',arms:[arm('FYB201',69,null,null),arm('Reference ranibizumab',69,null,null)],directVisibleValues:['Figure 2, Mean ETDRS letters (±SD), Study Week, two series'],approximate:false,reason:'Approximate bar heights only; n not printed.',figureContext:{figurePanel:'Figure 2',xAxis:'Study Week',yAxis:'Mean ETDRS Letters',axisScale:'broken axis at 0–40',series:'FYB201 / Reference ranibizumab',timepoint:'week 24',unit:'ETDRS letters',errorBarType:'SD (caption)',nBasis:'not printed'}}],visualAudit:audit};result=await call('dataex_set_selection_result',figure);assert.equal(result.outcomes[0].status,'CANDIDATE_ONLY');await page.setViewportSize({width:1450,height:1000});await page.screenshot({path:path.join(out,'phase32-ai-figure.png')});await page.locator('#crop-back-pdf').click();const figureCard=page.locator('.visual-result-card').last();assert.match(await figureCard.innerText(),/図からの推定・要確認/);assert.match(await figureCard.innerText(),/約/);assert.match(await figureCard.locator('.review-state').innerText(),/未確認/);
 passed.push('Missing n/SD/units and unvalidated derivation stay candidate; stale selection/conditions rejected; Figure estimate forced approximate candidate');
 // Image-only table PDF: no text layer exists, but printed values may be read visually.
 const pdf=await PDFDocument.create(),png=await pdf.embedPng(tableImage),sheet=pdf.addPage([600,280]);sheet.drawImage(png,{x:10,y:20,width:580,height:232});const scan=path.join(out,'scanned-table.pdf');fs.writeFileSync(scan,await pdf.save());await load(scan);await conditions(name);await page.setViewportSize({width:1500,height:1600});await select(1,{x:.01,y:.03,width:.98,height:.93});c=await call('dataex_get_selection_context');assert.equal((await call('dataex_get_page_text',{page:1})).normalizedText,'');await call('dataex_prepare_selection_for_ai',{selectionId:c.selectionId});const scanned={...structuredClone(payload),selectionId:c.selectionId,sourceKind:'SCANNED_TABLE_DIRECT'};result=await call('dataex_set_selection_result',scanned);assert.equal(result.outcomes[0].status,'READY');await page.setViewportSize({width:1450,height:1000});await page.screenshot({path:path.join(out,'phase32-ai-scanned.png')});await page.locator('#crop-back-pdf').click();assert.equal(await page.locator('.visual-result-card').count(),1);assert.match(await page.locator('.review-state').innerText(),/未確認/);
 await page.locator('.visual-result-card').getByRole('button',{name:'修正',exact:true}).click();await page.locator('.visual-result-card .correction-editor input').nth(2).fill('5.2');await page.getByRole('textbox',{name:'修正理由',exact:true}).fill('Manual review test');await page.getByRole('button',{name:'修正を保存',exact:true}).click();assert.match(await page.locator('.review-state').innerText(),/修正済み/);assert.match(await page.locator('#review-summary').innerText(),/解析投入可 0.*要確認 1/);
 assert.match(await page.locator('.visual-result-card .verification').innerText(),/未解決/);
 // Profile confirmation cannot be bypassed via visual tools.
 await page.locator('#profile-open').click();await page.locator('[data-field=profileName]').fill('Visual guard');await page.locator('[data-field=reviewOutcomeName]').fill(name);await page.locator('#profile-save').click();assert.equal((await call('dataex_get_selection_context')).extractionBlocked,true);assert.equal((await call('dataex_prepare_selection_for_ai',{selectionId:c.selectionId})).isError,true);
 passed.push('Image-only scanned table READY with unreviewed human state; numeric correction requires review; PDF scoping; activation guard blocks visual workflow');
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);passed.push('10 tools (7 existing + 3 visual), zero console errors, no uploads; context has no image bytes');fs.writeFileSync(path.join(out,'phase32-test-result.json'),JSON.stringify({passed,consoleErrors:errors,nonGetRequests:requests},null,2));fs.writeFileSync(path.join(out,'phase32-table-fixture.json'),JSON.stringify({...payload,outcomes:[outcome]},null,2));passed.forEach(x=>console.log('PASS '+x));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
