/* v5 A–M integration. Isolated browser storage; dummy Final edits are never clinical results. */
const {chromium}=require(process.env.DATAEX_PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {PDFDocument,StandardFonts}=require(process.env.DATAEX_PDFLIB_MODULE||'pdf-lib');
const repo=__dirname,url=process.env.DATAEX_URL||'http://127.0.0.1:8766/dataex-chatgpt.html';
const out=process.env.DATAEX_ARTIFACT_DIR||path.join(repo,'test-artifacts','paper-v5');fs.mkdirSync(out,{recursive:true});
const cherkin=JSON.parse(fs.readFileSync(process.env.DATAEX_CHERKIN_RAW,'utf8'));
const van=()=>{
 const arms=[{id:'SEQ_GP',label:'Gabapentin → Placebo (GBP starter)',role:'Original randomized crossover sequence',randomizedN:29,analyzedN:22},{id:'SEQ_PG',label:'Placebo → Gabapentin (Placebo starter)',role:'Original randomized crossover sequence',randomizedN:29,analyzedN:24},{id:'GBP_POOLED',label:'Gabapentin (both periods; same participants)',role:'Intervention treatment summary; not an independent randomized arm'},{id:'PBO_POOLED',label:'Placebo (both periods; same participants)',role:'Comparator treatment summary; not an independent randomized arm'}].map(a=>({treatedN:null,safetyN:null,randomizedN:null,analyzedN:null,sourceIds:[],...a}));
 const times=['End of each 3-week treatment; both periods (paired)','T1: 3 weeks, period 1 (Gabapentin)','T1: 3 weeks, period 1 (Placebo)'];
 const cells=[['r137','GBP_POOLED',20,46,'Total GBP',times[0]],['r141','PBO_POOLED',8,46,'Total placebo',times[0]],['r125','SEQ_GP',13,22,'GBP-1',times[1]],['r128','SEQ_PG',4,24,'Placebo-1',times[2]]];
 return {requestId:'test',pdfId:'aa13b288c7e77d43bf143891a227d946',study:{label:'van de Vusse 2004',design:'Randomized double-blind crossover RCT; two randomized sequences, both-period paired analysis',analysisUnit:'participant; paired within person',followUp:'3-week treatments separated by 2-week washout',arms,sourceIds:[]},outcomes:[{id:'GPE_ANY',reportedName:'Global perceived pain relief — some or much improvement',conceptCandidate:'Global perceived pain relief',dataType:'binary',instrument:'Seven-point GPE',scale:{min:null,max:null,unit:'participants',direction:'higher = better'},timepoints:times,resultType:'event',confidence:.95,mapping:{target:null,relation:'DISCOVERED',reason:'Clinical pain relief result, distinct from VAS'}}],rawValues:cells.map(([id,armId,events,total,column,timepoint])=>({id,outcomeId:'GPE_ANY',armId,comparatorArmId:null,timepoint,population:'Both-period completers; paired participants',nBasis:'OUTCOME_ANALYZED',resultType:'event',statistics:{events,total},sourceRefs:{events:'s-'+id,total:'s-'+id},effectMeasure:null,adjustment:null,confidence:.95})),sources:cells.map(([id,armId,events,total,column,timepoint])=>({id:'s-'+id,pdfFile:'van de Vusse 200.pdf',pdfPage:7,printedPage:'7',section:'Results',tableFigure:'Table 3',row:'% total (n/N)',column,directValue:events+'/'+total,evidenceText:timepoint===times[0]?'% total (n/N) 43% (20/46) a 17% (8/46)':'% total (n/N) 59% (13/22) a 17% (4/24) 1 29% (7/24) 18% (4/22)',kind:'TABLE',selectionId:null})),proposals:[],limitations:['Crossover: discordant-pair counts not reported; do not use independent-group binary analysis.']};
};
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1100},permissions:['clipboard-read','clipboard-write'],acceptDownloads:true}),page=await context.newPage(),checks=[],errors=[];
 const pass=name=>{checks.push(name);console.log('PASS '+name);};
 const idle=()=>page.waitForFunction(()=>window.DataExReview?.ready());
 const record=()=>page.evaluate(()=>DataExReview.snapshot());
 async function submit(pdf,raw){await page.locator('#pdf-file').setInputFiles(pdf);await page.waitForFunction(()=>DataExFuzzy.brief().pdfLoaded);const b=await page.evaluate(()=>DataExFuzzy.brief());assert.equal(b.pdfId,raw.pdfId);const result=await page.evaluate(input=>registeredTools.dataex_set_results.execute(input),{...structuredClone(raw),requestId:b.requestId});assert.ok(result.ok,JSON.stringify(result));await idle();}
 try{
  await page.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){registeredTools[t.name]=t;}}});});page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);await page.waitForFunction(()=>window.DataExFuzzy&&window.DataExPaperModel);
  assert.equal(await page.locator('#sr-context').getAttribute('open'),null);assert.ok(await page.getByRole('button',{name:'このPDFから使えるデータを探す',exact:true}).isVisible());assert.match(await page.locator('#fuzzy-mode').innerText(),/Paper-only/);
  await page.locator('#sr-context > summary').click();await page.locator('#review-name').fill('V5 acceptance — dummy edits');await page.locator('#intervention').fill('Acupuncture');await page.locator('#comparator').fill('Usual care');await page.locator('#outcomes').fill('Disability');
  for(const id of ['intervention','comparator','outcomes']){await page.locator('[data-clear-sr="'+id+'"]').click();assert.equal(await page.locator('#'+id).inputValue(),'');}
  await page.locator('#intervention').fill('Acupuncture');await page.locator('#clear-sr').click();assert.equal((await page.evaluate(()=>DataExFuzzy.brief())).mode,'DISCOVERY');assert.equal(await page.locator('#review-name').inputValue(),'V5 acceptance — dummy edits');await page.locator('#sr-context > summary').click();pass('A. Default Paper-only, optional ICO and individual/all clear preserve review identity');
  await submit(process.env.DATAEX_CHERKIN_PDF,cherkin);const frozen=JSON.stringify((await record()).snapshot.raw);
  // The detailed A–M checks below use the actual production UI and are completed with the UI integration.
  assert.match(await page.locator('#fuzzy-results').innerText(),/Roland/);assert.match(await page.locator('#fuzzy-results').innerText(),/bothersomeness/i);assert.equal((await record()).snapshot.raw.rawValues.length,163);pass('B. Paper-only Cherkin discovers primary clinical outcomes and retains all 163 Raw values');
  assert.equal(await page.locator('.paper-comparison-card').count(),3);assert.match(await page.locator('#fuzzy-study-summary').innerText(),/共有対照/);
  const roland=page.locator('.outcome-card[data-outcome-id="O1"]');assert.equal(await roland.locator('.paper-three-layers tbody tr').count(),3);assert.match(await roland.locator('.paper-three-layers').innerText(),/介入前/);assert.match(await roland.locator('.paper-three-layers').innerText(),/介入後/);assert.match(await roland.locator('.paper-three-layers').innerText(),/変化量/);
  await roland.getByRole('button',{name:'26 週',exact:true}).click();assert.ok(await roland.locator('[data-raw-id="t2-O1-A2-2"]').isVisible());assert.equal(JSON.stringify((await record()).snapshot.raw),frozen);await roland.getByRole('button',{name:'8 週',exact:true}).click();pass('F. Continuous baseline/post/change stay separate and time switching keeps Raw immutable');
  await page.screenshot({path:path.join(out,'cherkin-paper-first.png')});
  const before=(await page.evaluate(()=>DataExReview.all())).length;
  await page.locator('#new-paper').click();await page.locator('[name=next-paper-ico][value=clear]').check();await page.locator('#new-paper-confirm').click();await page.waitForFunction(()=>!DataExFuzzy.brief().pdfLoaded);assert.equal(await page.locator('#pdf-viewer .pdf-page').count(),0);assert.equal(await page.locator('#fuzzy-results .outcome-card').count(),0);assert.equal((await page.evaluate(()=>DataExReview.all())).length,before);assert.equal(await page.locator('#review-name').inputValue(),'V5 acceptance — dummy edits');pass('M. New paper clears PDF and candidates without deleting Review Workspace');
  await submit(process.env.DATAEX_VAN_PDF,van());await page.screenshot({path:path.join(out,'van-paper-first.png')});assert.equal((await record()).snapshot.raw.rawValues.length,4);assert.match(await page.locator('#fuzzy-results').innerText(),/Gabapentin/);pass('C. Real van de Vusse PDF connects to source-linked crossover candidates');
  assert.match(await page.locator('#fuzzy-study-summary').innerText(),/Gabapentin vs Placebo/);assert.ok(!(await page.locator('#fuzzy-study-summary').innerText()).includes('→'));assert.ok(await page.locator('[data-raw-id=r137]').isVisible());assert.ok(await page.locator('[data-raw-id=r141]').isVisible());assert.equal(await page.locator('[data-raw-id=r125]:visible').count(),0);
  await page.locator('[data-raw-id=r137]').click();await page.waitForFunction(()=>document.querySelector('#page-number').value==='7'&&document.querySelectorAll('.bbox-highlight').length>0);assert.match(await page.locator('#evidence-message').innerText(),/Table 3|値を特定|根拠/);await page.screenshot({path:path.join(out,'van-gpe-table3-source.png')});pass('D. Pooled GPE 20/46 and 8/46 lead; value click reaches PDF p7 Table3 yellow highlight');
  assert.match(await page.locator('#fuzzy-results').innerText(),/独立.*2群|parallel-group|paired/i);pass('E. Crossover counts stay binary candidates with explicit paired-analysis guidance');
  // Known statistical types on a generated local PDF; these are UI fixtures, not invented results for either real paper.
  const statPdf=await PDFDocument.create(),font=await statPdf.embedFont(StandardFonts.Helvetica),sheet=statPdf.addPage();
  const defs=[['SE','continuous',{mean:4.2,se:.3,n:100},null,'Mean 4.2 SE 0.3 n 100'],['CI','continuous',{mean:4.2,ciLow:3.6,ciHigh:4.8,ciLevel:95,n:100},null,'Mean 4.2 95% CI 3.6 to 4.8 n 100'],['HR','time-to-event',{estimate:.74,ciLow:.60,ciHigh:.91,ciLevel:95},'HR','HR 0.74 95% CI 0.60 to 0.91']];
  defs.forEach((d,i)=>sheet.drawText(d[4],{x:30,y:740-i*70,size:14,font}));const statFile=path.join(out,'statistical-types-fixture.pdf');fs.writeFileSync(statFile,await statPdf.save());
  await page.locator('#sr-context > summary').click();await page.locator('#review-name').fill('V5 second review');await page.locator('#sr-context > summary').click();
  await page.locator('#pdf-file').setInputFiles(statFile);await page.waitForFunction(()=>DataExFuzzy.brief().pdfLoaded);const sb=await page.evaluate(()=>DataExFuzzy.brief()),testRaw={requestId:sb.requestId,pdfId:sb.pdfId,study:{label:'Statistical type UI fixture',design:'Parallel randomized controlled trial',analysisUnit:'participant',followUp:'8 weeks',arms:[{id:'I',label:'Intervention',role:'Intervention',randomizedN:100,treatedN:100,analyzedN:100,safetyN:100,sourceIds:[]},{id:'C',label:'Placebo',role:'Comparator',randomizedN:100,treatedN:100,analyzedN:100,safetyN:100,sourceIds:[]}],sourceIds:[]},outcomes:defs.map(([id,dataType])=>({id,reportedName:id==='HR'?'Overall survival':id+' continuous measurement',conceptCandidate:id,dataType,instrument:'Fixture',scale:{min:null,max:null,unit:'score',direction:'unknown'},timepoints:['8 weeks'],resultType:id==='HR'?'effect':'endpoint',confidence:1,mapping:{target:null,relation:'DISCOVERED',reason:'Primary reported numeric result'}})),rawValues:defs.map(([id,dataType,statistics,effectMeasure])=>({id:'r-'+id,outcomeId:id,armId:'I',comparatorArmId:id==='HR'?'C':null,timepoint:'8 weeks',population:'ITT',nBasis:'OUTCOME_ANALYZED',resultType:id==='HR'?'effect':'endpoint',statistics,sourceRefs:Object.fromEntries(Object.keys(statistics).map(k=>[k,'s-'+id])),effectMeasure,adjustment:null,confidence:1})),sources:defs.map(([id,dataType,s,e,text])=>({id:'s-'+id,pdfFile:path.basename(statFile),pdfPage:1,printedPage:'1',section:'Results',tableFigure:null,row:id,column:null,directValue:text,evidenceText:text,kind:'TEXT',selectionId:null})),proposals:[],limitations:[]};
  assert.ok((await page.evaluate(input=>registeredTools.dataex_set_results.execute(input),testRaw)).ok);await idle();
  const seCard=page.locator('.outcome-card[data-outcome-id=SE]');assert.match(await seCard.innerText(),/SDではなくSE|SDではない/);assert.match(await seCard.innerText(),/Mean \+ SE/);pass('G. Mean+SE explicitly says SE is not SD; no raw substitution');
  const hrCard=page.locator('.outcome-card[data-outcome-id=HR]');assert.match(await hrCard.innerText(),/log\(HR\)|log\(ratio\)/);assert.match(await hrCard.innerText(),/Generic inverse variance|GIV/);assert.equal((await record()).snapshot.raw.rawValues.find(r=>r.id==='r-HR').effectMeasure,'HR');pass('H. HR+CI offers log(HR)/SE GIV guidance, preserving Raw HR and CI');
  await page.setViewportSize({width:375,height:1000});await seCard.scrollIntoViewIfNeeded();assert.ok(await seCard.isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'paper-375.png')});pass('375px keeps primary actions accessible without document overflow');
  await page.setViewportSize({width:1440,height:1100});await page.locator('#review-workspace').getByRole('combobox',{name:'保存先レビュー'}).selectOption({label:'V5 acceptance — dummy edits'});await page.locator('#review-workspace').getByRole('button',{name:'van de Vusse 2004',exact:true}).click();await idle();assert.equal(await page.locator('#review-name').inputValue(),'V5 acceptance — dummy edits');
  await page.locator('#sr-context > summary').click();await page.locator('#intervention').fill('Gabapentin');await page.locator('#comparator').fill('Placebo');const workspaceBefore=JSON.stringify(await page.evaluate(()=>DataExReview.all()));await page.locator('#clear-sr').click();assert.equal(JSON.stringify(await page.evaluate(()=>DataExReview.all())),workspaceBefore);assert.equal((await page.evaluate(()=>DataExFuzzy.brief())).mode,'DISCOVERY');pass('Clear after stored studies preserves complete Review Workspace and audit');
  await page.locator('#intervention').fill('Gabapentin');await page.locator('#new-paper').click();await page.locator('[name=next-paper-ico][value=keep]').check();await page.locator('#new-paper-confirm').click();await page.waitForFunction(()=>!DataExFuzzy.brief().pdfLoaded);assert.equal(await page.locator('#intervention').inputValue(),'Gabapentin');assert.equal(await page.locator('#review-name').inputValue(),'V5 acceptance — dummy edits');assert.equal(JSON.stringify(await page.evaluate(()=>DataExReview.all())),workspaceBefore);pass('New paper keep preserves ICO and follows the selected Review rather than an old form project');
  assert.deepEqual(errors,[]);pass('No JavaScript page errors');
  fs.writeFileSync(path.join(out,'acceptance-v5.json'),JSON.stringify({checks,errors,mode:'Real PDFs with frozen Cherkin data and four source-linked van de Vusse regression rows; UI validation, not new AI extraction.'},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
