const {chromium}=require(process.env.DATAEX_PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const builder=require('./dataex-prompt-builder.js'),core=require('./dataex-core-prompt.js');
const url=process.env.DATAEX_URL||'http://127.0.0.1:8766/dataex-chatgpt.html',source=process.env.DATAEX_SOURCE_DIR;
const out=process.env.DATAEX_ARTIFACT_DIR||path.join(__dirname,'test-artifacts'),assets=process.env.DATAEX_PDF_DIR||path.join(__dirname,'test-assets');
assert.equal(new URL(url).origin,'http://127.0.0.1:8766');fs.mkdirSync(out,{recursive:true});
(async()=>{
  const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1450,height:1000}});
  const page=await context.newPage(),errors=[],requests=[],passed=[];
  const pass=name=>{passed.push(name);console.log('PASS '+name);};
  try{
    if(source)await context.route('http://127.0.0.1:8766/**',route=>{
      const name=decodeURIComponent(new URL(route.request().url()).pathname).slice(1);
      if(!name.includes('/')&&/\.(?:html|js|css)$/.test(name)&&fs.existsSync(path.join(source,name)))return route.fulfill({status:200,contentType:name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css':'text/javascript; charset=utf-8',body:fs.readFileSync(path.join(source,name))});
      return route.continue();
    });
    await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:new URL(url).origin});
    await page.addInitScript(()=>{
      window.registeredTools={};window.toolExecutions=0;window.networkCalls=[];
      Object.defineProperty(document,'modelContext',{value:{registerTool(t){const execute=t.execute;window.registeredTools[t.name]={...t,execute(...args){window.toolExecutions++;return execute(...args);}};}}});
      const originalFetch=window.fetch;window.fetch=function(...args){window.networkCalls.push(['fetch',String(args[0])]);return originalFetch.apply(this,args);};
      const originalOpen=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(...args){window.networkCalls.push(['xhr',String(args[1])]);return originalOpen.apply(this,args);};
      const OriginalSocket=window.WebSocket;window.WebSocket=class extends OriginalSocket{constructor(...args){window.networkCalls.push(['websocket',String(args[0])]);super(...args);}};
    });
    page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),method:r.method(),kind:r.resourceType()}));
    await page.goto(url);await page.waitForFunction(()=>Object.keys(window.registeredTools).length===10);
    const call=(name,args={})=>page.evaluate(({name,args})=>window.registeredTools[name].execute(args),{name,args});
    const generate=()=>page.locator('#generate-prompt').click(),prompt=()=>page.locator('#builder-prompt').inputValue();
    const clickAdvanced=async()=>{if(!await page.locator('#builder-data-type').isVisible())await page.locator('#builder-advanced > summary').click();};
    const requestStart=requests.length;
    await page.locator('#outcomes').fill('Pain intensity');await generate();
    assert.equal(await page.locator('#builder-result').isVisible(),true);let output=await prompt();
    assert.ok(output.startsWith('# SR・メタ分析用'));assert.ok(output.endsWith(core.CORE_PROMPT_TEMPLATE.split('# 21.')[1]));
    assert.match(await page.locator('#builder-warning').innerText(),/候補抽出は可能ですが、最終analysis-ready値を一意に決められない可能性/);
    assert.equal(await page.locator('#builder-warning.error').count(),0);assert.equal((await call('dataex_get_state')).pdfLoaded,false);
    pass('Generation without PDF or complete specification produces the entire core and a nonblocking warning');
    await page.locator('#intervention').fill('Intervention Alpha');await generate();assert.match(await prompt(),/## 介入\nIntervention Alpha/);pass('Intervention is included');
    await page.locator('#comparator').fill('Comparator Beta');await generate();assert.match(await prompt(),/## 比較\nComparator Beta/);pass('Comparator is included');
    await page.locator('#outcomes').fill('Pain intensity\nQuality of life\nAdverse events');await generate();
    for(const [i,name]of ['Pain intensity','Quality of life','Adverse events'].entries())assert.ok((await prompt()).includes(`### O${i+1}: ${name}`));pass('Three textarea outcomes generate O1/O2/O3');
    await page.locator('#timepoint').fill('8–12 weeks');await generate();assert.ok((await prompt()).includes('Timepoint / target window: 8–12 weeks'));pass('Timepoint is included');
    await clickAdvanced();await page.locator('#builder-study-design').selectOption('crossover-rct');await page.locator('#builder-data-type').selectOption('continuous');
    for(const value of ['mean','SD','SE','n','change mean','change SD'])await page.locator('#builder-statistics').getByLabel(value,{exact:true}).check();
    await page.locator('#population-rule').fill('FAS; matching row-specific denominator');await page.locator('#builder-scale').fill('0–100');
    await page.locator('#builder-time-origin').selectOption('treatment start');await page.locator('#builder-time-rule').selectOption('closest to target');
    await page.locator('#builder-analysis-unit').fill('participant');await page.locator('#builder-node-rule').fill('Keep doses separate');await page.locator('#extra-rules').fill('No mixing adjusted SE with raw means');
    await generate();output=await prompt();
    for(const value of ['クロスオーバーRCT','continuous','mean, SD, SE, n, change mean, change SD','FAS; matching row-specific denominator','0–100','treatment start','closest to target','participant','Keep doses separate','No mixing adjusted SE with raw means'])assert.ok(output.includes(value),value);
    assert.equal(await page.locator('#builder-warning').isVisible(),false);pass('Every Advanced setting and all continuous statistics reach the prompt');
    const options=await page.locator('#builder-study-design option').allTextContents();assert.equal(options.length,8);assert.doesNotMatch(options.join(','),/case.?control|ケースコントロール/i);pass('Study Design contains the eight requested options and no case-control');
    const clipboardText=async()=>(await page.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n');
    await page.locator('#builder-copy').click();assert.equal(await clipboardText(),output);pass('Full prompt copied through the real Clipboard API (Windows newline normalization only)');
    await page.evaluate(()=>{navigator.clipboard.writeText=()=>Promise.reject(Error('Test denied'));});
    await page.locator('#builder-copy').click();assert.equal(await clipboardText(),output);assert.match(await page.locator('#builder-status').innerText(),/代替方式/);pass('Clipboard denial falls back to selecting the entire textarea and real copy');
    await page.evaluate(()=>{document.execCommand=()=>false;});await page.locator('#builder-copy').click();
    const selected=await page.locator('#builder-prompt').evaluate(e=>[e.selectionStart,e.selectionEnd,e.value.length]);assert.deepEqual(selected,[0,output.length,output.length]);assert.match(await page.locator('#builder-status').innerText(),/Ctrl\+C/);pass('If both copy methods fail the entire prompt stays selected with manual-copy guidance');
    let downloadPromise=page.waitForEvent('download');await page.locator('#builder-save-txt').click();let download=await downloadPromise;
    await download.saveAs(path.join(out,download.suggestedFilename()));assert.equal(fs.readFileSync(path.join(out,download.suggestedFilename()),'utf8'),output);pass('TXT download contains the exact full prompt');
    downloadPromise=page.waitForEvent('download');await page.locator('#builder-save-json').click();download=await downloadPromise;await download.saveAs(path.join(out,download.suggestedFilename()));
    const saved=JSON.parse(fs.readFileSync(path.join(out,download.suggestedFilename()),'utf8'));
    assert.equal(saved.corePromptVersion,'0.9');assert.equal(saved.builderVersion,'1.0.0');assert.equal(saved.reviewConfiguration.outcomes.length,3);
    assert.deepEqual(saved.reviewConfiguration.outcomes[2].requestedStatistics,['mean','SD','SE','n','change mean','change SD']);assert.equal(saved.reviewConfiguration.nodeRule,'Keep doses separate');assert.equal('prompt' in saved,false);pass('Configuration JSON download has versions and complete outcome settings without a prompt');
    assert.equal(await page.locator('#builder-prompt').getAttribute('readonly'),'');assert.equal(await page.locator('#builder-prompt').evaluate(e=>e.maxLength),-1);
    assert.equal(await page.locator('#builder-result [contenteditable=true], #builder-result textarea:not([readonly])').count(),0);pass('Core and generated prompt have no editing UI; no text truncation limit');
    const inputInfo=await page.locator('input,textarea,select').evaluateAll(nodes=>nodes.map(n=>[n.id,n.name,n.type,n.getAttribute('aria-label'),n.getAttribute('placeholder')].join(' ')).join('\n'));
    assert.doesNotMatch(inputInfo,/api[ _-]?key|APIキー/i);pass('No API key field exists');
    const keys=await page.evaluate(()=>Object.fromEntries(Object.keys(localStorage).map(k=>[k,localStorage.getItem(k)])));
    assert.ok(keys[builder.STORAGE_KEY]);assert.doesNotMatch(JSON.stringify(keys),/# SR・メタ分析用|CORE_PROMPT_TEMPLATE|pdfBytes|data:application\/pdf/);
    assert.deepEqual(Object.keys(JSON.parse(keys[builder.STORAGE_KEY])).sort(),['reviewConfiguration','ui','version']);pass('Browser storage contains only builder configuration and UI state, never prompt/core/PDF bytes');
    assert.deepEqual(await page.evaluate(()=>window.networkCalls),[]);assert.deepEqual(requests.slice(requestStart).filter(r=>['fetch','xhr','websocket'].includes(r.kind)||!['GET','HEAD'].includes(r.method)),[]);
    assert.equal(await page.evaluate(()=>window.toolExecutions),1);pass('Generation, copy and downloads execute no extraction tool, fetch, XHR, WebSocket or upload');
    await page.locator('#intervention').fill('Updated intervention');assert.equal(await page.locator('#builder-stale').isVisible(),true);
    downloadPromise=page.waitForEvent('download');await page.locator('#builder-save-txt').click();download=await downloadPromise;await download.saveAs(path.join(out,'updated-prompt.txt'));
    assert.match(fs.readFileSync(path.join(out,'updated-prompt.txt'),'utf8'),/## 介入\nUpdated intervention/);assert.equal(await page.locator('#builder-stale').isVisible(),false);pass('Exports after an input change regenerate the current configuration and keep panel/content consistent');
    await page.reload();await page.waitForFunction(()=>Object.keys(window.registeredTools).length===10);
    assert.equal(await page.locator('#intervention').inputValue(),'Updated intervention');assert.equal(await page.locator('#builder-study-design').inputValue(),'crossover-rct');assert.equal(await page.locator('#builder-data-type').inputValue(),'continuous');
    assert.equal(await page.locator('#builder-statistics input:checked').count(),6);assert.equal(await page.locator('#builder-result').isVisible(),false);assert.equal(await prompt(),'');
    await generate();assert.match(await prompt(),/closest to target/);pass('Reload restores review settings and UI but does not restore or store prompt text');
    await clickAdvanced();await page.locator('#builder-data-type').selectOption('binary');assert.deepEqual(await page.locator('#builder-statistics label').allTextContents(),['events','total']);
    for(const value of ['events','total'])await page.locator('#builder-statistics').getByLabel(value,{exact:true}).check();await generate();assert.match(await prompt(),/Requested statistics: events, total/);
    await page.locator('#builder-data-type').selectOption('time-to-event');assert.deepEqual(await page.locator('#builder-statistics label').allTextContents(),['HR','95% CI']);pass('Changing data type offers the correct binary and time-to-event statistics without leaking continuous choices');
    await page.setViewportSize({width:375,height:812});await page.locator('#builder-data-type').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(out,'builder-375-advanced.png'),fullPage:true});await generate();
    for(const id of ['generate-prompt','builder-copy','builder-save-txt','builder-save-json']){
      const button=page.locator('#'+id);await button.scrollIntoViewIfNeeded();const box=await button.boundingBox();assert.ok(box.width>50&&box.x>=0&&box.x+box.width<=375,id);
    }
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=375));await page.screenshot({path:path.join(out,'builder-375-output.png')});pass('At 375px all main operations fit and remain accessible without horizontal page overflow');
    await page.setViewportSize({width:1500,height:1600});await page.locator('#pdf-file').setInputFiles(path.join(assets,'Holz 2020.pdf'));await page.waitForFunction(()=>document.querySelector('#pdf-status').textContent.startsWith('✓'));
    await page.locator('#page-number').fill('5');await page.locator('#page-number').dispatchEvent('change');await page.waitForFunction(()=>document.querySelector('#pdf-page-5 canvas'));
    await page.locator('#selection-region').click();await page.locator('#pdf-page-5').scrollIntoViewIfNeeded();const box=await page.locator('#pdf-page-5').boundingBox();
    await page.mouse.move(box.x+.12*box.width,box.y+.64*box.height);await page.mouse.down();await page.mouse.move(box.x+.92*box.width,box.y+.876*box.height,{steps:8});await page.mouse.up();
    await page.locator('#selection-preview').click();await page.locator('#crop-use').click();let selection=await call('dataex_get_selection_context');assert.equal(selection.captionStatus,'MATCHED');assert.match(selection.nearbyMetadata[0].label,/Figure 2/);
    await call('dataex_focus_evidence',{page:5,query:'Figure 2'});const highlightCount=await page.locator('#pdf-page-5 .bbox-highlight,#pdf-page-5 .highlight-hook').count();assert.ok(highlightCount);
    const rect=await page.locator('#pdf-page-5 .manual-selection').getAttribute('style');const before=await call('dataex_get_state');await generate();
    const after=await call('dataex_get_state'),next=await call('dataex_get_selection_context');
    assert.equal(after.filename,before.filename);assert.equal(after.pageCount,before.pageCount);assert.equal(next.selectionId,selection.selectionId);assert.deepEqual(next.nearbyMetadata,selection.nearbyMetadata);
    assert.equal(await page.locator('#pdf-page-5 .manual-selection').getAttribute('style'),rect);assert.equal(await page.locator('#pdf-page-5 .bbox-highlight,#pdf-page-5 .highlight-hook').count(),highlightCount);
    await page.setViewportSize({width:1450,height:1000});await page.screenshot({path:path.join(out,'builder-pdf-selection.png')});pass('Prompt generation preserves the loaded PDF, figure selection, nearby caption and yellow highlight');
    assert.deepEqual(errors,[]);assert.equal(Object.keys(await page.evaluate(()=>window.registeredTools)).length,10);pass('All ten existing site tools still register; no JavaScript errors');
    fs.writeFileSync(path.join(out,'builder-browser-result.json'),JSON.stringify({passed,consoleErrors:errors,requests},null,2));
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
