const {chromium}=require(process.env.DATAEX_PLAYWRIGHT_MODULE||'playwright'),{PDFDocument,StandardFonts}=require(process.env.DATAEX_PDFLIB_MODULE||'pdf-lib');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=process.env.DATAEX_ARTIFACT_DIR||__dirname,assets=process.env.DATAEX_PDF_DIR||path.join(__dirname,'test-assets'),url=process.env.DATAEX_URL||'http://127.0.0.1:8766/dataex-chatgpt.html';
assert.equal(new URL(url).origin,'http://127.0.0.1:8766');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1500,height:1600}}),errors=[],uploads=[],passed=[];
 try{
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))uploads.push(r.url());});
  if(process.env.DATAEX_SOURCE_DIR)for(const name of ['dataex-chatgpt.html','dataex-visual.js','dataex-selection.js','dataex-caption.js','dataex-webmcp.js'])await page.route(new URL(name,url).href,r=>r.fulfill({status:200,contentType:name.endsWith('.html')?'text/html; charset=utf-8':'text/javascript; charset=utf-8',body:fs.readFileSync(path.join(process.env.DATAEX_SOURCE_DIR,name))}));
  await page.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.registeredTools[t.name]=t;}}});window.addEventListener('dataex-evidence-focus',e=>window.lastCaptionFocus=e.detail);});
  const ready=()=>page.waitForFunction(()=>Object.keys(window.registeredTools).length===10);
  const call=(name,args={})=>page.evaluate(({name,args})=>window.registeredTools[name].execute(args),{name,args});
  const load=async file=>{await page.locator('#pdf-file').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#pdf-status').textContent.startsWith('✓'));};
  const conditions=async(outcome,timepoint)=>{if(!await page.locator('#condition-content').isVisible())await page.locator('#toggle-conditions').click();await page.locator('#intervention').fill('FYB201');await page.locator('#comparator').fill('Reference ranibizumab');await page.locator('#outcomes').fill(outcome);await page.locator('#timepoint').fill(timepoint);};
  const select=async(n,r)=>{await page.setViewportSize({width:1500,height:1600});await page.locator('#page-number').fill(String(n));await page.locator('#page-number').dispatchEvent('change');await page.waitForFunction(n=>document.querySelector('#pdf-page-'+n+' canvas'),n);await page.locator('#selection-region').click();await page.locator('#pdf-page-'+n).scrollIntoViewIfNeeded();const b=await page.locator('#pdf-page-'+n).boundingBox();await page.mouse.move(b.x+r.x*b.width,b.y+r.y*b.height);await page.mouse.down();await page.mouse.move(b.x+(r.x+r.width)*b.width,b.y+(r.y+r.height)*b.height,{steps:8});await page.mouse.up();await page.locator('#selection-preview').click();await page.locator('#selection-dialog').waitFor({state:'visible'});await page.locator('#crop-use').click();const c=await call('dataex_get_selection_context');assert.ok(c.selectionId);assert.equal((await call('dataex_prepare_selection_for_ai',{selectionId:c.selectionId})).ok,true);return c;};
  const arm=(name,mean,sd,denominator)=>({name,valueText:`Mean ${mean}`,numerator:null,denominator,mean,sd,se:null});
  const audit={valuesClearlyVisible:false,labelsClearlyVisible:true,unitsClearlyVisible:true,timepointClearlyVisible:true,uncertaintyTypeClearlyVisible:true,notes:'Only the chart, axes and legend are in the manual crop. Caption is a separate PDF text source.'};
  const figureName='Study eye BCVA at week 24',figureOutcome={outcome:figureName,timepoint:'week 24',population:null,unit:'ETDRS letters',analysisUnit:'study eye',variableType:'continuous',arms:[arm('FYB201',69,null,null),arm('Reference ranibizumab',68,null,null)].map(a=>({...a,nStatus:'NOT_SHOWN_FOR_TIMEPOINT',uncertaintyValueStatus:'UNKNOWN'})),directVisibleValues:['Study Week','Mean ETDRS Letters (+SD)','FYB201','Reference ranibizumab','24'],derivedValues:[],approximate:false,reason:'Central values estimated from week 24 bars. Figure number and population are outside the image.',reviewFlags:[],figureMetadata:{figureNumber:null,panel:null,caption:null,xAxis:'Study Week',yAxis:'Mean ETDRS Letters (+SD)',unit:'ETDRS letters',series:['FYB201','Reference ranibizumab'],errorBarType:'SD',population:null,analysisSet:null,timepoint:'week 24',metadataVerification:'VISUALLY_VERIFIED_DIRECT_METADATA'}};
  await page.goto(url);await ready();await load(path.join(assets,'Holz 2020.pdf'));await conditions(figureName,'week 24');
  const figureRect={x:.12,y:.64,width:.8,height:.236};let c=await select(5,figureRect);
  fs.writeFileSync(path.join(out,'holz-selection-context.json'),JSON.stringify(c,null,2));
  assert.equal(c.captionStatus,'MATCHED',JSON.stringify(c.nearbyMetadata));assert.equal(c.nearbyMetadata.length,1);assert.match(c.nearbyMetadata[0].label,/Figure 2/);assert.match(c.nearbyMetadata[0].text,/US-relevant population, full analysis set/);assert.equal(c.nearbyMetadata[0].verification,'SOURCE_VERIFIED_TEXT');
  assert.ok(c.nearbyMetadata.reduce((n,s)=>n+s.text.length,0)<1000);assert.ok(!/data:image|base64,|blob:/.test(JSON.stringify(c)));
  await page.setViewportSize({width:1450,height:1000});await page.screenshot({path:path.join(out,'phase322-crop-without-caption.png')});
  let payload={selectionId:c.selectionId,sourceKind:'FIGURE_ESTIMATE',resultStatus:'READY',outcomes:[figureOutcome],visualAudit:audit};
  let result=await call('dataex_set_selection_result',payload);assert.equal(result.ok,true,JSON.stringify(result));const figure=result.outcomes[0];
  assert.equal(figure.figureMetadata.figureNumber,'Figure 2');assert.equal(figure.figureMetadata.errorBarType,'SD');assert.equal(figure.figureMetadata.population,'US-relevant population, full analysis set');assert.equal(figure.figureMetadata.unit,'ETDRS letters');assert.equal(figure.figureMetadata.timepoint,'week 24');assert.equal(figure.status,'CANDIDATE_ONLY');assert.equal(figure.analysisAction,'REVIEW');assert.equal(figure.approximate,true);
  assert.deepEqual(figure.arms.map(a=>a.mean),[69,68]);assert.ok(figure.arms.every(a=>a.n===null&&a.uncertainty.sd===null));assert.equal(figure.metadataProvenance.population.sourceType,'PDF_TEXT_CAPTION');assert.equal(figure.metadataProvenance.figureNumber.verification,'SOURCE_VERIFIED_TEXT');assert.equal(figure.metadataProvenance.errorBarType.sourceType,'VISUAL_REGION');assert.equal(figure.figureMetadata.caption,null);
  assert.deepEqual(figure.unresolved,['week 24の対応n','SDの数値']);assert.match(figure.figureSummary,/近接captionで確認/);
  let records=await page.evaluate(()=>window.dataexVisual.snapshot());const bundle=records[0].visualSourceBundle;
  assert.equal(bundle.selectionSource.selectionId,c.selectionId);assert.equal(bundle.nearbyMetadataSources[0].sourceType,'PDF_TEXT_CAPTION');assert.ok(bundle.nearbyMetadataSources[0].normalizedRect.y>=figureRect.y+figureRect.height,'caption really is outside crop');assert.equal(records[0].input.outcomes[0].figureMetadata.population,null,'no rewrite of the image audit');
  await page.locator('#crop-back-pdf').click();const card=page.locator('.visual-result-card').first();assert.match(await card.locator('.figure-metadata').innerText(),/近接caption/);assert.doesNotMatch(await card.innerText(),/SD不明|解析集団の確認が必要/);
  await card.getByRole('button',{name:'選択範囲を見る',exact:true}).click();const rectStyle=await page.locator('#pdf-page-5 .manual-selection').getAttribute('style');
  await card.getByRole('button',{name:'Figure 2 captionを見る',exact:true}).click();await page.waitForFunction(()=>window.lastCaptionFocus?.anchor.label==='Figure 2 caption');let focus=await page.evaluate(()=>window.lastCaptionFocus.result);assert.equal(focus.ok,true,JSON.stringify(focus));assert.match(focus.matchedText,/US-relevant population, full analysis set/);assert.equal(await page.locator('#pdf-page-5 .manual-selection').getAttribute('style'),rectStyle);assert.ok(await page.locator('#pdf-page-5 .bbox-highlight').count()>0);
  await page.screenshot({path:path.join(out,'phase322-caption-highlight.png')});await card.locator('summary').click();assert.match(await card.locator('.provenance-selection').innerText(),/選択画像から確認/);assert.doesNotMatch(await card.locator('.provenance-selection').innerText(),/US-relevant/);assert.match(await card.locator('.provenance-caption').innerText(),/PDF_TEXT_CAPTION/);await card.locator('.provenance-caption').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'phase322-provenance.png')});
  passed.push('Holz chart-only crop: automatic Figure 2 caption association; approx 69/68; SD/US-relevant FAS; null n/SD values; image/text provenance separated; CANDIDATE_ONLY / REVIEW');
  await page.reload();await ready();assert.equal(await card.getByRole('button',{name:'Figure 2 captionを見る',exact:true}).isDisabled(),true);await load(path.join(assets,'Holz 2020.pdf'));await card.getByRole('button',{name:'Figure 2 captionを見る',exact:true}).click();await page.waitForFunction(()=>window.lastCaptionFocus?.anchor.label==='Figure 2 caption');assert.equal((await page.evaluate(()=>window.lastCaptionFocus.result)).ok,true);assert.equal(await page.locator('#pdf-page-5 .manual-selection').getAttribute('style'),rectStyle);assert.match(await card.locator('.figure-metadata').innerText(),/US-relevant population, full analysis set/);
  passed.push('Caption yellow highlight and independent purple selection overlay; source bundle persists and reopens after PDF reload');
  const tableName='Change in BCVA from baseline to 8 to 12 weeks';await conditions(tableName,'week 8');c=await select(5,{x:.065,y:.062,width:.88,height:.263});assert.equal(c.captionStatus,'MATCHED',JSON.stringify(c.nearbyMetadata));assert.match(c.nearbyMetadata[0].label,/Table 2/);const tableImage=await page.locator('#selection-image').screenshot();
  const tableOutcome={outcome:tableName,timepoint:'week 8',population:'US-relevant population, full analysis set; assessed patients',unit:'ETDRS letters',analysisUnit:'participant',variableType:'continuous',arms:[arm('FYB201',5.1,7.52,228),arm('Reference ranibizumab',5.6,8.63,233)],directVisibleValues:['Mean change from baseline, ETDRS letters (SD): 5.1 (7.52), 5.6 (8.63)','Patients with assessment: 228, 233'],derivedValues:[],approximate:false,reason:'Table 2 raw mean, SD and observed n, excluding ANCOVA estimates.',reviewFlags:[]};
  const table={selectionId:c.selectionId,sourceKind:'TABLE_DIRECT',resultStatus:'READY',outcomes:[tableOutcome],visualAudit:{...audit,valuesClearlyVisible:true,notes:'Direct Table 2 print.'}};
  result=await call('dataex_set_selection_result',table);assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.outcomes[0].status,'READY');assert.deepEqual(result.summaryCounts,{use:1,review:1,doNotUse:0,total:2});await page.locator('#crop-back-pdf').click();const tableCard=page.locator('.visual-result-card').last();assert.match(await tableCard.innerText(),/Mean 5.1 \/ SD 7.52 \/ n 228/);assert.match(await tableCard.innerText(),/Mean 5.6 \/ SD 8.63 \/ n 233/);await tableCard.getByRole('button',{name:'Table 2 titleを見る',exact:true}).click();await page.waitForFunction(()=>window.lastCaptionFocus?.anchor.label==='Table 2 title');assert.equal((await page.evaluate(()=>window.lastCaptionFocus.result)).ok,true);
  passed.push('Table 2 title associated; 5.1/7.52/228 and 5.6/8.63/233 unchanged, TABLE_DIRECT / READY');
  // Image-only PDF: even a caption visible in the raster cannot become PDF_TEXT_CAPTION.
  let doc=await PDFDocument.create(),png=await doc.embedPng(tableImage),sheet=doc.addPage([600,280]);sheet.drawImage(png,{x:10,y:20,width:580,height:232});const scan=path.join(out,'scanned-table.pdf');fs.writeFileSync(scan,await doc.save());await load(scan);await conditions(tableName,'week 8');c=await select(1,{x:.01,y:.03,width:.98,height:.93});assert.equal(c.captionStatus,'NOT_FOUND');assert.deepEqual(c.nearbyMetadata,[]);result=await call('dataex_set_selection_result',{...table,selectionId:c.selectionId,sourceKind:'SCANNED_TABLE_DIRECT'});assert.equal(result.outcomes[0].status,'READY');await page.locator('#crop-back-pdf').click();
  passed.push('Scanned table: NOT_FOUND text caption, no invented metadata; visual direct extraction stays READY');
  // Synthetic ambiguous same-page captions; no nearest-only metadata supplement.
  doc=await PDFDocument.create();const font=await doc.embedFont(StandardFonts.Helvetica);sheet=doc.addPage([600,800]);sheet.drawText('Figure 2. Mean and SD (population A).',{x:60,y:285,size:10,font});sheet.drawText('Figure 3. Mean and SE (population B).',{x:60,y:254,size:10,font});sheet.drawText('Synthetic plot',{x:100,y:480,size:14,font});const ambiguous=path.join(out,'ambiguous-figures.pdf');fs.writeFileSync(ambiguous,await doc.save());await load(ambiguous);await conditions(figureName,'week 24');c=await select(1,{x:.1,y:.3,width:.8,height:.3});assert.equal(c.captionStatus,'AMBIGUOUS',JSON.stringify(c.nearbyMetadata));assert.equal(c.nearbyMetadata.length,2);payload={...payload,selectionId:c.selectionId};result=await call('dataex_set_selection_result',payload);assert.equal(result.outcomes[0].figureMetadata.population,null);assert.equal(result.outcomes[0].figureMetadata.figureNumber,null);const bad=structuredClone(payload);bad.outcomes[0].captionMetadata={sourceRef:c.nearbyMetadata[0].sourceId,population:'population A'};assert.equal((await call('dataex_set_selection_result',bad)).isError,true);await page.locator('#crop-back-pdf').click();
  // Existing Review Profile activation guard still blocks the visual workflow.
  await page.locator('#profile-open').click();await page.locator('[data-field=profileName]').fill('Caption guard regression');await page.locator('[data-field=reviewOutcomeName]').fill(figureName);await page.locator('#profile-save').click();assert.equal((await call('dataex_get_selection_context')).extractionBlocked,true);assert.equal((await call('dataex_prepare_selection_for_ai',{selectionId:c.selectionId})).isError,true);
  passed.push('Ambiguous captions not adopted or forceable via sourceRef; Review Profile guard remains active');
  assert.deepEqual(errors,[]);assert.deepEqual(uploads,[]);passed.push('10 site tools, no image bytes in context, no external API/uploads, zero console errors');
  fs.writeFileSync(path.join(out,'phase322-test-result.json'),JSON.stringify({passed,figure,bundle,captionHighlight:focus,consoleErrors:errors,uploads},null,2));passed.forEach(x=>console.log('PASS '+x));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
