const assert=require('node:assert/strict');
const paper=require('./dataex-paper-model.js'), results=require('./dataex-results-model.js');
const {fixture}=require('./dataex-fuzzy-fixture.cjs');
let checks=0;
function test(name,fn){fn();checks++;console.log('PASS '+name);}
const parallel={design:'parallel RCT'}, cross={design:'Randomized double-blind cross-over RCT'};
const continuous={id:'O',reportedName:'Pain intensity',conceptCandidate:'Pain intensity',dataType:'continuous',confidence:.95};
const binary={...continuous,reportedName:'Global perceived pain relief',dataType:'binary'};
const row=(statistics,extra={})=>({id:'raw-1',outcomeId:'O',armId:'A1',comparatorArmId:null,timepoint:'8 weeks',population:'Observed participants',nBasis:'OUTCOME_ANALYZED',resultType:'endpoint',statistics,sourceRefs:{mean:'s1',sd:'s1',se:'s1',n:'s1',estimate:'s1',ciLow:'s1',ciHigh:'s1'},confidence:.95,...extra});
const classify=(statistics,extra={},outcome=continuous,study=parallel)=>paper.classify(row(statistics,extra),outcome,study);
test('Mean SD n is structurally ready without changing Raw',()=>{const r=row({mean:6.3,sd:5.7,n:40}),before=JSON.stringify(r);const c=paper.classify(r,continuous,parallel);assert.equal(c.readiness,'DIRECT');assert.equal(c.statisticType,'Mean + SD');assert.equal(JSON.stringify(r),before);});
test('Mean SE n provides a separate source-linked SD proposal',()=>{const r=row({mean:4.2,se:.3,n:25}),before=JSON.stringify(r),c=paper.classify(r,continuous,parallel);assert.equal(c.readiness,'CONVERTIBLE');assert.match(c.hint,/SDではなくSE/);assert.equal(c.derived.statistics.sd,1.5);assert.equal(c.derived.status,'PROPOSED');assert.equal(c.derived.sourceRefs.se,'s1');assert.equal(JSON.stringify(r),before);});
test('SE without outcome-specific n stays visible and unconverted',()=>{const c=classify({mean:4.2,se:.3});assert.equal(c.readiness,'REVIEW');assert.equal(c.derived,undefined);});
test('Randomized N is not silently substituted for analyzed n',()=>{assert.equal(classify({mean:4.2,se:.3,n:100},{nBasis:'RANDOMIZED'}).derived,undefined);assert.equal(classify({mean:4.2,sd:2,n:100},{nBasis:'RANDOMIZED'}).readiness,'REVIEW');});
test('Change mean SD retains change identity',()=>{const c=classify({mean:-4,sd:2,n:30},{resultType:'change'});assert.equal(c.statisticType,'Change mean + SD');assert.match(c.hint,/Change/);});
test('Baseline mean SD includes endpoint mixing caution',()=>{const c=classify({mean:10,sd:4,n:40},{timepoint:'Baseline'});assert.ok(c.details.some(x=>x.includes('介入前')));});
test('Mean only is not hidden or declared ready',()=>assert.equal(classify({mean:3.4}).readiness,'REVIEW'));
test('Mean CI is not guessed into SD using an unknown t critical value',()=>{const c=classify({mean:5,ciLow:4,ciHigh:6,ciLevel:95,n:20});assert.equal(c.statisticType,'Mean + CI');assert.equal(c.readiness,'REVIEW');assert.equal(c.derived,undefined);});
test('Large-sample Mean CI offers an explicit normal-approximation proposal',()=>{const c=classify({mean:5,ciLow:4,ciHigh:6,ciLevel:95,n:121});assert.equal(c.readiness,'CONVERTIBLE');assert.equal(c.derived.statistics.sd,2/3.92*11);assert.ok(c.derived.assumptions.some(x=>x.includes('正規近似')));});
test('LS mean SE cannot become an ordinary arm SD',()=>{const c=classify({mean:4,se:.2,n:40},{adjustment:'Adjusted for baseline pain'}, {...continuous,reportedName:'LS mean pain'});assert.equal(c.statisticType,'LS mean + SE');assert.equal(c.derived,undefined);assert.equal(c.readiness,'REVIEW');});
test('Adjusted arm means remain separate from comparative effects',()=>{const c=classify({mean:4,sd:2,n:40},{adjustment:'Adjusted age and baseline'});assert.equal(c.readiness,'REVIEW');assert.match(c.statisticType,/Adjusted mean/);});
test('Median IQR has no silent mean imputation',()=>{const c=classify({estimate:5},{effectMeasure:'Median (IQR)'});assert.equal(c.statisticType,'Median + IQR');assert.equal(c.readiness,'REVIEW');assert.equal(c.derived,undefined);});
test('Median range is distinguished from IQR',()=>assert.equal(classify({estimate:5},{effectMeasure:'Median (range)'}).statisticType,'Median + range'));
test('Mean rank never becomes a scale mean',()=>{const c=classify({estimate:16.8,n:22},{effectMeasure:'Mean rank'},{...continuous,dataType:'other'});assert.equal(c.statisticType,'Mean rank');assert.equal(c.readiness,'UNUSABLE');});
test('Zero binary events with a valid denominator is usable',()=>assert.equal(classify({events:0,total:40},{resultType:'event'},binary).readiness,'DIRECT'));
test('Missing binary denominator is not reverse-calculated',()=>{const c=classify({events:20},{resultType:'event'},binary);assert.equal(c.readiness,'UNUSABLE');assert.equal(c.derived,undefined);});
test('Percentage only cannot become events/total',()=>{const c=classify({estimate:43},{effectMeasure:'Reported percentage (%)'},binary);assert.equal(c.statisticType,'Percentage only');assert.equal(c.readiness,'UNUSABLE');});
test('Events exceeding total are not ready candidates',()=>assert.equal(classify({events:45,total:40},{resultType:'event'},binary).readiness,'UNUSABLE'));
test('HR 95 CI yields log HR and log-scale SE with explicit assumptions',()=>{const c=classify({estimate:.74,ciLow:.60,ciHigh:.91,ciLevel:95},{resultType:'effect',effectMeasure:'HR'},{...continuous,dataType:'time-to-event'});assert.equal(c.statisticType,'HR');assert.equal(c.readiness,'CONVERTIBLE');assert.equal(c.derived.statistics.estimate,Math.log(.74));assert.ok(Math.abs(c.derived.statistics.se-(Math.log(.91)-Math.log(.60))/3.92)<1e-12);assert.match(c.hint,/HRはRRではありません/);assert.ok(c.derived.assumptions.some(s=>s.includes('Wald')));});
test('HR confidence bounds never populate SD',()=>{const c=classify({estimate:.74,ciLow:.60,ciHigh:.91,ciLevel:95},{resultType:'effect',effectMeasure:'HR'});assert.equal(c.derived.statistics.sd,undefined);});
test('OR RR and RD retain distinct effect measures',()=>{for(const type of ['OR','RR','RD']){const c=classify({estimate:type==='RD'?-.1:.7,ciLow:type==='RD'?-.2:.5,ciHigh:type==='RD'?0:.98,ciLevel:95},{resultType:'effect',effectMeasure:type});assert.equal(c.statisticType,type);assert.equal(c.readiness,'CONVERTIBLE');}});
test('Adjusted OR remains a GIV effect and not participant counts',()=>{const c=classify({estimate:.7,ciLow:.5,ciHigh:.98,ciLevel:95},{resultType:'effect',effectMeasure:'OR',adjustment:'Adjusted age'});assert.equal(c.statisticType,'Adjusted OR');assert.equal(c.derived.statistics.events,undefined);});
test('Adjusted MD CI is separate from arm-level mean SD',()=>{const c=classify({estimate:-2.63,ciLow:-3.69,ciHigh:-1.56,ciLevel:95},{effectMeasure:'MD',resultType:'effect',adjustment:'Adjusted baseline disability'});assert.equal(c.statisticType,'Adjusted MD');assert.equal(c.readiness,'CONVERTIBLE');assert.match(c.hint,/arm別Mean\/SDとは別/);assert.equal(c.derived.statistics.sd,undefined);});
test('SMD with SE stays an SMD GIV candidate',()=>{const c=classify({estimate:-.4,se:.1},{effectMeasure:'SMD',resultType:'effect'});assert.equal(c.statisticType,'SMD');assert.equal(c.readiness,'DIRECT');});
test('Unknown CI level is not assumed to be 95 percent',()=>{const c=classify({estimate:.74,ciLow:.60,ciHigh:.91},{effectMeasure:'HR',resultType:'effect'});assert.equal(c.readiness,'REVIEW');assert.equal(c.derived,undefined);});
test('Unspecified ratio SE scale cannot be exported as log SE',()=>{const c=classify({estimate:.74,se:.1},{effectMeasure:'HR',resultType:'effect'});assert.equal(c.readiness,'REVIEW');assert.equal(c.derived,undefined);});
test('Explicit log HR with reported SE is directly usable for GIV',()=>{const c=classify({estimate:Math.log(.74),se:.1},{effectMeasure:'log HR',resultType:'effect'});assert.equal(c.statisticType,'log HR');assert.equal(c.readiness,'DIRECT');});
test('Nonpositive ratio CI is never log-transformed',()=>{const c=classify({estimate:.74,ciLow:0,ciHigh:1,ciLevel:95},{effectMeasure:'HR',resultType:'effect'});assert.equal(c.readiness,'UNUSABLE');assert.equal(c.derived,undefined);});
test('Strongly asymmetric intervals require the original CI method',()=>{const c=classify({estimate:.5,ciLow:.49,ciHigh:3,ciLevel:95},{effectMeasure:'HR',resultType:'effect'});assert.equal(c.readiness,'REVIEW');assert.equal(c.derived,undefined);});
test('Crossover binary complete totals still require paired analysis',()=>{const c=classify({events:20,total:46},{resultType:'event'},binary,cross);assert.equal(c.readiness,'REVIEW');assert.ok(c.details.some(x=>x.includes('不一致ペア')));});
test('Crossover arm Mean SD n is not labeled parallel-group ready',()=>assert.equal(classify({mean:6,sd:3,n:46},{},continuous,cross).readiness,'REVIEW'));
test('Crossover mean SE cannot be converted using independent n',()=>{const c=classify({mean:6,se:.4,n:46},{},continuous,cross);assert.equal(c.derived,undefined);assert.equal(c.readiness,'REVIEW');});
test('A reported paired comparative effect with SE can be ready',()=>assert.equal(classify({estimate:-2,se:.3},{resultType:'effect',effectMeasure:'MD',adjustment:'Paired within-person difference analysis'},continuous,cross).readiness,'DIRECT'));
test('A note that paired variance is missing is not proof of a paired analysis',()=>assert.equal(classify({estimate:-2,se:.3},{resultType:'effect',effectMeasure:'MD',adjustment:'paired variance not reported'},continuous,cross).readiness,'REVIEW'));
test('Low-confidence visual values remain review candidates',()=>assert.equal(classify({mean:60,sd:20,n:40},{confidence:.55}).readiness,'REVIEW'));
test('Recurrent event counts require person-time and stay distinct from binary data',()=>{assert.equal(classify({eventCount:10,personTime:25},{}, {...continuous,dataType:'count/rate'}).statisticType,'Count / person-time');assert.equal(classify({eventCount:10},{}, {...continuous,dataType:'count/rate'}).readiness,'UNUSABLE');});
test('An endpoint mean cannot borrow a baseline SD source',()=>{const r=row({mean:4,sd:3,n:40});r.sourceRefs={mean:'post',sd:'base',n:'post'};const s={study:parallel,rawValues:[r],sources:[{id:'base',row:'Baseline',column:'SD'},{id:'post',row:'8 weeks',column:'Mean'}]};assert.equal(paper.classify(r,continuous,s).readiness,'REVIEW');});

// Explicitly synthetic examples: these fixtures test presentation, not re-extraction accuracy.
function cherkinShape(){const f=fixture();f.study.label='SYNTHETIC Cherkin 2009 presentation fixture';f.outcomes[0].reportedName='Symptom bothersomeness';f.outcomes[0].conceptCandidate='Symptom bothersomeness';f.outcomes[0].mapping.reason='Primary outcome';f.outcomes[2].mapping.reason='Primary outcome';return f;}
function vusseShape(){
  const f=fixture();f.study={label:'SYNTHETIC van de Vusse 2004 presentation fixture',design:cross.design,analysisUnit:'participant',followUp:'3-week treatment periods',sourceIds:['structure'],arms:[
    {id:'SEQ_GP',label:'Gabapentin→Placebo',role:'randomized sequence',randomizedN:29,analyzedN:22},
    {id:'SEQ_PG',label:'Placebo→Gabapentin',role:'randomized sequence',randomizedN:29,analyzedN:24},
    {id:'GBP',label:'Gabapentin (both treatment periods; paired completers)',role:'treatment summary',randomizedN:null,analyzedN:46,safetyN:54},
    {id:'PBO',label:'Placebo (both treatment periods; paired completers)',role:'treatment summary comparator',randomizedN:null,analyzedN:46,safetyN:51}]};
  f.outcomes=[{...f.outcomes[0],id:'VAS',reportedName:'VAS pain intensity',timepoints:['Baseline','3 weeks','8 weeks'],mapping:{target:null,relation:'DISCOVERED',reason:'Primary outcome'}},
    {...f.outcomes[4],id:'GPE',reportedName:'Global perceived pain relief (some or much)',conceptCandidate:'Global pain relief',timepoints:['Both treatment periods']},
    {...f.outcomes[4],id:'AE',reportedName:'Participants with adverse events',timepoints:['Both treatment periods']}];
  f.rawValues=[row({estimate:58},{id:'vas1',outcomeId:'VAS',armId:'SEQ_GP',timepoint:'3 weeks',effectMeasure:'Visual bar height',confidence:.55}),row({estimate:73},{id:'vas2',outcomeId:'VAS',armId:'SEQ_PG',timepoint:'3 weeks',effectMeasure:'Visual bar height',confidence:.55}),
    row({events:20,total:46},{id:'gpe1',outcomeId:'GPE',armId:'GBP',timepoint:'Both treatment periods',population:'Paired completers',resultType:'event'}),row({events:8,total:46},{id:'gpe2',outcomeId:'GPE',armId:'PBO',timepoint:'Both treatment periods',population:'Paired completers',resultType:'event'}),
    row({events:13,total:22},{id:'gpe-p1',outcomeId:'GPE',armId:'SEQ_GP',timepoint:'3 weeks',population:'First period',resultType:'event'}),
    row({events:20,total:54},{id:'ae1',outcomeId:'AE',armId:'GBP',timepoint:'Both treatment periods',population:'Safety set',nBasis:'SAFETY',resultType:'event'}),row({events:2,total:51},{id:'ae2',outcomeId:'AE',armId:'PBO',timepoint:'Both treatment periods',population:'Safety set',nBasis:'SAFETY',resultType:'event'})];
  f.proposals=[];return f;
}
test('Paper-only four-arm presentation proposes three comparisons with a shared control',()=>{const c=paper.comparisons(cherkinShape());assert.equal(c.items.length,3);assert.ok(c.items.every(x=>x.sharedControl));assert.ok(c.items.every(x=>x.comparator==='Usual care'));});
test('Paper-only Cherkin fixture prioritizes Roland and bothersomeness without ICO',()=>{const b=paper.build(cherkinShape());assert.ok(b.mainOutcomes.some(x=>/Roland/.test(x.reportedName)));assert.ok(b.mainOutcomes.some(x=>/bothersomeness/.test(x.reportedName)));assert.ok(b.mainOutcomes.length<=5);});
test('Adjusted effect variants remain with their parent, outside main clinical cards',()=>{const f=cherkinShape();f.outcomes.push({...f.outcomes[2],id:'ADJ',reportedName:'Adjusted mean difference in Roland disability score',dataType:'comparative effect',resultType:'effect'});f.rawValues.push(row({estimate:-2.63,se:.5},{id:'adj',outcomeId:'ADJ',armId:'A1',comparatorArmId:'A4',resultType:'effect',effectMeasure:'MD',adjustment:'Adjusted baseline'}));const b=paper.build(f);assert.ok(!b.mainOutcomes.some(o=>o.id==='ADJ'));assert.ok(b.mainOutcomes.find(o=>o.id==='O3').variants.some(o=>o.id==='ADJ'));});
test('Arm-specific descriptions of the same analyzed population form one comparison set',()=>{const f=fixture();for(const r of f.rawValues)r.population=`Randomized ${f.study.arms.find(a=>a.id===r.armId).label} group with available observations; n not imputed`;const b=paper.build(f),s=b.resultSets.find(s=>s.outcomeId==='O1'&&s.timepoint==='8 weeks'&&s.comparisonId==='comparison:A2:A4');assert.deepEqual(s.armIds,['A2','A4']);});
test('Distinct analysis strata are not merged merely because both say Safety set',()=>{const f=fixture();f.rawValues=[row({events:2,total:20},{id:'adult',outcomeId:'O5',armId:'A1',population:'Adult Safety set',nBasis:'SAFETY',resultType:'event'}),row({events:1,total:20},{id:'child',outcomeId:'O5',armId:'A4',population:'Children Safety set',nBasis:'SAFETY',resultType:'event'})];const b=paper.build(f);assert.ok(!b.resultSets.some(s=>s.rawValueIds.includes('adult')&&s.rawValueIds.includes('child')));});
test('Unspecified multi-arm control is not guessed as the last arm',()=>{const f=fixture();f.study.arms.forEach((a,i)=>{a.role='active intervention';a.label='Treatment '+i;});assert.equal(paper.comparisons(f).items.length,0);});
test('Crossover top comparison uses treatments, not sequences',()=>{const c=paper.comparisons(vusseShape());assert.equal(c.items.length,1);assert.equal(c.items[0].label,'Gabapentin vs Placebo');assert.deepEqual(c.items[0].armIds,['GBP','PBO']);assert.equal(c.isCrossover,true);assert.ok(c.details.some(x=>x.isSequence));});
test('Crossover summary never adds paired sample sizes or creates four independent arms',()=>{const f=vusseShape(),before=JSON.stringify(f),b=paper.build(f);assert.equal(b.comparisons.items.length,1);assert.equal(b.comparisons.items[0].totalN,undefined);assert.equal(JSON.stringify(f),before);});
test('Crossover GPE pooled result appears before period detail with both original denominators',()=>{const b=paper.build(vusseShape()),o=b.mainOutcomes.find(o=>o.id==='GPE'),main=o.paperResultSets.find(s=>!s.sequenceDetail);assert.deepEqual(main.rows.map(v=>v.raw.statistics),[{events:20,total:46},{events:8,total:46}]);assert.equal(main.readiness.readiness,'REVIEW');assert.ok(o.paperResultSets.some(s=>s.sequenceDetail));});
test('VAS remains a main crossover outcome even when only sequence-specific values exist',()=>assert.ok(paper.build(vusseShape()).mainOutcomes.some(o=>o.id==='VAS')));
test('Safety denominator 54/51 is not replaced by GPE paired-completer 46',()=>{const b=paper.build(vusseShape()),s=b.resultSets.find(s=>s.outcomeId==='AE'&&!s.sequenceDetail);assert.deepEqual(s.rows.map(v=>v.raw.statistics.total),[54,51]);});
test('Sequence period values remain accessible without becoming top treatment rows',()=>{const b=paper.build(vusseShape());assert.ok(b.resultSets.some(s=>s.sequenceDetail&&s.rawValueIds.includes('vas1')));assert.ok(!b.resultSets.filter(s=>!s.sequenceDetail).some(s=>s.rawValueIds.includes('vas1')));});
test('Sequence-only input can name a clinical comparison without assigning sequence n to treatments',()=>{const f=vusseShape();f.study.arms=f.study.arms.slice(0,2);const c=paper.comparisons(f);assert.equal(c.items[0].label,'Gabapentin vs Placebo');assert.deepEqual(c.items[0].armIds,[]);});
test('Endpoint, change and baseline remain separate result sets',()=>{const f=fixture(),r=f.rawValues[0];f.rawValues.push({...r,id:'base',timepoint:'Baseline'}, {...r,id:'change',resultType:'change'});const b=paper.build(f);const s=b.resultSets.filter(s=>s.outcomeId===r.outcomeId);assert.ok(s.some(s=>s.resultType==='baseline'));assert.ok(s.some(s=>s.resultType==='endpoint'));assert.ok(s.some(s=>s.resultType==='change'));assert.ok(s.every(s=>!(s.rawValueIds.includes('change')&&s.rawValueIds.includes(r.id))));});
test('Distinct follow-up times are not silently clustered',()=>{const b=paper.build(fixture()),sets=b.resultSets.filter(s=>s.outcomeId==='O1'&&s.comparisonId===b.comparisons.items[0].id);assert.ok(sets.some(s=>s.timepoint==='8 weeks'));assert.ok(sets.some(s=>s.timepoint==='12 weeks'));});
test('Result-set identities are stable when unrelated Raw order changes',()=>{const f=fixture(),first=paper.build(f).resultSets.find(s=>s.rawValueIds.includes('R1')).id;f.rawValues.reverse();assert.equal(paper.build(f).resultSets.find(s=>s.rawValueIds.includes('R1')).id,first);});
test('Result set retains original source anchors for Click-to-Source',()=>{const f=fixture(),m=results.build({raw:f,analysisReadyCandidates:[]}),b=paper.build(m);const first=b.resultSets.flatMap(s=>s.rows).find(v=>v.raw.id===f.rawValues[0].id);assert.equal(first.sourceAnchor.sourceId,f.rawValues[0].sourceRefs.mean);assert.equal(first.raw,f.rawValues[0]);});
test('Frozen Raw and original presentation model remain immutable',()=>{const f=vusseShape(),m=results.build({raw:f,analysisReadyCandidates:[]}),before=JSON.stringify(m);const freeze=x=>{if(x&&typeof x==='object'){Object.values(x).forEach(freeze);Object.freeze(x);}return x;};freeze(m);paper.build(m);assert.equal(JSON.stringify(m),before);});
test('Baseline-only psychometric inventory stays outside initial main outcomes',()=>{const f=fixture();f.outcomes.push({...f.outcomes[0],id:'SCL',reportedName:'SCL-90 anxiety',timepoints:['Baseline']});f.rawValues.push(row({mean:1,sd:1,n:20},{id:'sclbase',outcomeId:'SCL',timepoint:'Baseline'}));const b=paper.build(f);assert.ok(!b.mainOutcomes.some(o=>o.id==='SCL'));assert.ok(b.otherOutcomes.some(o=>o.id==='SCL'));});
console.log(JSON.stringify({checks,ok:true}));
